/**
 * English names for the starter catalogue, keyed by slug.
 *
 * Separate from `ingredients.ts` because that file is about **nutrition** — the
 * macros are the same figure in every language, and re-listing them beside each
 * translation would invite the two copies to drift on the one thing that must
 * not. The slug is the join.
 *
 * A slug here with no seed row, or a seed row with no entry here, fails
 * `seed.test.ts`. That is deliberate: a missing translation should be a red test
 * rather than an English user reading "Calabacín" on their shopping list.
 *
 * British English, matching the `en-GB` dictionary in `apps/web`: courgette,
 * aubergine, rocket, mince, wholemeal.
 */
export const INGREDIENT_NAMES_EN_GB: Record<string, string> = {
  'aceite-de-coco': 'Coconut oil',
  'aceite-de-girasol': 'Sunflower oil',
  'aceite-de-oliva-virgen-extra': 'Extra virgin olive oil',
  'aceitunas-negras': 'Black olives',
  'aceitunas-verdes': 'Green olives',
  aguacate: 'Avocado',
  ajo: 'Garlic',
  alcachofa: 'Artichoke',
  alcaparras: 'Capers',
  almeja: 'Clams',
  almendras: 'Almonds',
  'alubias-blancas-cocidas': 'Cooked white beans',
  'alubias-pintas-cocidas': 'Cooked pinto beans',
  anacardos: 'Cashews',
  apio: 'Celery',
  'arroz-basmati-cocido': 'Cooked basmati rice',
  'arroz-blanco-cocido': 'Cooked white rice',
  'arroz-integral-cocido': 'Cooked brown rice',
  'atun-al-natural': 'Tuna in brine',
  avellanas: 'Hazelnuts',
  'azucar-blanco': 'White sugar',
  'bacalao-desalado': 'Desalted cod',
  bagel: 'Bagel',
  berenjena: 'Aubergine',
  boniato: 'Sweet potato',
  brocoli: 'Broccoli',
  'brocoli-congelado': 'Frozen broccoli',
  'bulgur-cocido': 'Cooked bulgur',
  cacahuetes: 'Peanuts',
  'cacao-en-polvo-puro': 'Pure cocoa powder',
  'cafe-solo': 'Black coffee',
  calabacin: 'Courgette',
  calabaza: 'Pumpkin',
  calamar: 'Squid',
  'caldo-de-pollo': 'Chicken stock',
  'caldo-de-verduras': 'Vegetable stock',
  'canela-molida': 'Ground cinnamon',
  'carne-picada-de-ternera': 'Beef mince',
  cebolla: 'Onion',
  cebolleta: 'Spring onion',
  chalota: 'Shallot',
  champinon: 'Mushroom',
  'chocolate-negro-70': 'Dark chocolate 70%',
  chorizo: 'Chorizo',
  cilantro: 'Fresh coriander',
  'clara-de-huevo': 'Egg white',
  'coco-rallado': 'Desiccated coconut',
  'col-rizada': 'Kale',
  coliflor: 'Cauliflower',
  'comino-molido': 'Ground cumin',
  conejo: 'Rabbit',
  'copos-de-avena': 'Rolled oats',
  'copos-de-maiz': 'Cornflakes',
  'costillas-de-cerdo': 'Pork ribs',
  croissant: 'Croissant',
  'curcuma-molida': 'Ground turmeric',
  'curry-en-polvo': 'Curry powder',
  'cuscus-cocido': 'Cooked couscous',
  dorada: 'Sea bream',
  'edamame-cocido': 'Cooked edamame',
  escarola: 'Endive',
  'esparrago-verde': 'Green asparagus',
  espinaca: 'Spinach',
  'espinacas-congeladas': 'Frozen spinach',
  'extracto-de-vainilla': 'Vanilla extract',
  'fideos-de-arroz-cocidos': 'Cooked rice noodles',
  'filete-de-merluza-congelado': 'Frozen hake fillet',
  fresa: 'Strawberry',
  'frutos-rojos-congelados': 'Frozen berries',
  gambas: 'Prawns',
  'garbanzos-cocidos': 'Cooked chickpeas',
  'gelatina-neutra': 'Unflavoured gelatine',
  'germen-de-trigo': 'Wheatgerm',
  guacamole: 'Guacamole',
  'guisantes-congelados': 'Frozen peas',
  'harina-de-almendra': 'Ground almonds',
  'harina-de-avena': 'Oat flour',
  'harina-de-trigo': 'Plain flour',
  huevo: 'Egg',
  hummus: 'Hummus',
  'jamon-cocido': 'Cooked ham',
  'jamon-serrano': 'Serrano ham',
  'jengibre-en-polvo': 'Ground ginger',
  'judia-verde': 'Green bean',
  'judia-verde-congelada': 'Frozen green beans',
  kefir: 'Kefir',
  ketchup: 'Ketchup',
  kiwi: 'Kiwi',
  laurel: 'Bay leaf',
  'leche-de-almendra': 'Almond milk',
  'leche-de-avena': 'Oat milk',
  'leche-de-soja': 'Soy milk',
  'leche-desnatada': 'Skimmed milk',
  'leche-entera': 'Whole milk',
  'leche-semidesnatada': 'Semi-skimmed milk',
  lechuga: 'Lettuce',
  'lentejas-cocidas': 'Cooked lentils',
  'lentejas-rojas-cocidas': 'Cooked red lentils',
  'levadura-nutricional': 'Nutritional yeast',
  'levadura-quimica': 'Baking powder',
  limon: 'Lemon',
  'lomo-de-cerdo': 'Pork loin',
  lubina: 'Sea bass',
  magdalena: 'Muffin',
  maicena: 'Cornflour',
  'maiz-congelado': 'Frozen sweetcorn',
  'maiz-dulce': 'Cooked sweetcorn',
  mantequilla: 'Butter',
  'mantequilla-de-cacahuete': 'Peanut butter',
  manzana: 'Apple',
  mayonesa: 'Mayonnaise',
  mejillon: 'Mussels',
  melocoton: 'Peach',
  melon: 'Melon',
  merluza: 'Hake',
  'mermelada-de-fresa': 'Strawberry jam',
  miel: 'Honey',
  'mix-de-verduras-congelado': 'Frozen mixed vegetables',
  'mostaza-amarilla': 'Yellow mustard',
  'mostaza-de-dijon': 'Dijon mustard',
  muesli: 'Muesli',
  'muslo-de-pollo': 'Chicken thigh',
  nabo: 'Turnip',
  naranja: 'Orange',
  'nata-para-cocinar': 'Single cream',
  nueces: 'Walnuts',
  'nuez-moscada': 'Nutmeg',
  'oregano-seco': 'Dried oregano',
  'pan-blanco': 'White bread',
  'pan-de-centeno': 'Rye bread',
  'pan-de-hamburguesa': 'Burger bun',
  'pan-de-molde': 'Sliced bread',
  'pan-integral': 'Wholemeal bread',
  'pan-rallado': 'Breadcrumbs',
  panceta: 'Pork belly',
  'pasta-cocida': 'Cooked pasta',
  'pasta-integral-cocida': 'Cooked wholemeal pasta',
  patata: 'Potato',
  pavo: 'Turkey',
  'pechuga-de-pollo': 'Chicken breast',
  'pepinillos-en-vinagre': 'Pickled gherkins',
  pepino: 'Cucumber',
  pera: 'Pear',
  perejil: 'Fresh parsley',
  'pesto-genovese': 'Genovese pesto',
  'picos-de-pan': 'Breadsticks',
  'pimenton-dulce': 'Sweet paprika',
  'pimiento-rojo': 'Red pepper',
  'pimiento-verde': 'Green pepper',
  'pipas-de-girasol': 'Sunflower seeds',
  pistachos: 'Pistachios',
  platano: 'Banana',
  puerro: 'Leek',
  'pulpo-cocido': 'Cooked octopus',
  'queso-cottage': 'Cottage cheese',
  'queso-curado': 'Mature cheese',
  'queso-de-burgos': 'Burgos fresh cheese',
  'queso-fresco-de-cabra': "Fresh goat's cheese",
  'queso-mozzarella': 'Mozzarella',
  'queso-parmesano': 'Parmesan',
  'quinoa-cocida': 'Cooked quinoa',
  rabano: 'Radish',
  remolacha: 'Beetroot',
  requeson: 'Curd cheese',
  rucula: 'Rocket',
  sal: 'Salt',
  salmon: 'Salmon',
  'salsa-alioli': 'Aioli',
  'salsa-barbacoa': 'Barbecue sauce',
  'salsa-de-soja': 'Soy sauce',
  'salsa-picante-tabasco': 'Tabasco-style hot sauce',
  'salsa-sriracha': 'Sriracha sauce',
  sandia: 'Watermelon',
  sardina: 'Sardine',
  seitan: 'Seitan',
  'semillas-de-calabaza': 'Pumpkin seeds',
  'semillas-de-chia': 'Chia seeds',
  'semillas-de-lino': 'Flaxseeds',
  sesamo: 'Sesame seeds',
  'sirope-de-agave': 'Agave syrup',
  'soja-texturizada': 'Cooked textured soy protein',
  'solomillo-de-ternera': 'Beef fillet',
  tahini: 'Tahini',
  'te-verde': 'Green tea',
  tempeh: 'Tempeh',
  'ternera-magra': 'Lean beef',
  'tofu-firme': 'Firm tofu',
  tomate: 'Tomato',
  'tomate-frito': 'Tomato sauce',
  'tomate-triturado': 'Crushed tomatoes',
  'tortilla-de-trigo': 'Wheat tortilla',
  'tortitas-de-arroz': 'Rice cakes',
  'tortitas-de-maiz': 'Corn cakes',
  uva: 'Grapes',
  'vinagre-de-jerez': 'Sherry vinegar',
  'vinagre-de-manzana': 'Cider vinegar',
  'vinagre-de-vino-tinto': 'Red wine vinegar',
  'yogur-griego-natural': 'Natural Greek yoghurt',
  'yogur-natural-desnatado': 'Fat-free natural yoghurt',
  zanahoria: 'Carrot'
};
