import type { IngredientSeed } from './types';

/**
 * Cheeses, yoghurts, creams and milks beyond the starter set. Every row carries
 * `milk`; `lactose` goes on the fresh and liquid ones, where it is still there
 * to react to, and not on the aged cheeses, where it is gone. Plant-based
 * yoghurts live here too because a shop shelves them here — they carry no
 * milk, and so no dairy class.
 */
export const DAIRY: readonly IngredientSeed[] = [
  // ── Fresh and soft cheeses ────────────────────────────────────────────
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 3.9, category: 'dairy', fat: 21.5, kcal: 265, name: 'Queso feta', protein: 14.2, slug: 'queso-feta', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 2.2, category: 'dairy', fat: 25, kcal: 321, name: 'Queso halloumi', protein: 22, slug: 'queso-halloumi' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 7.3, category: 'dairy', fat: 10.2, kcal: 150, name: 'Ricotta', protein: 7.5, slug: 'ricotta', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4.8, category: 'dairy', fat: 44, kcal: 429, name: 'Mascarpone', protein: 4.6, slug: 'mascarpone' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 5.5, category: 'dairy', fat: 34.4, kcal: 350, name: 'Queso crema', protein: 6.2, slug: 'queso-crema', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 5, category: 'dairy', fat: 12, kcal: 160, name: 'Queso de untar light', protein: 8, slug: 'queso-de-untar-light' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 2.4, category: 'dairy', fat: 22.1, kcal: 299, name: 'Mozzarella fresca', protein: 22.2, slug: 'mozzarella-fresca', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 2, category: 'dairy', fat: 29, kcal: 330, name: 'Burrata', protein: 14, slug: 'burrata' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 2, category: 'dairy', fat: 24, kcal: 300, name: 'Queso tierno', protein: 20, slug: 'queso-tierno' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 0, category: 'dairy', fat: 21.1, kcal: 264, name: 'Rulo de cabra', protein: 18.5, slug: 'rulo-de-cabra', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 0.5, category: 'dairy', fat: 27.7, kcal: 334, name: 'Queso brie', protein: 20.8, slug: 'queso-brie', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 0.5, category: 'dairy', fat: 24.3, kcal: 300, name: 'Queso camembert', protein: 19.8, slug: 'queso-camembert', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 1, category: 'dairy', fat: 27, kcal: 340, name: 'Queso de tetilla', protein: 23, slug: 'queso-de-tetilla' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4, category: 'dairy', fat: 0.2, kcal: 47, name: 'Queso batido desnatado', protein: 8, slug: 'queso-batido-desnatado' },
  // ── Aged cheeses ──────────────────────────────────────────────────────
  { allergens: [{ key: 'milk' }], carbs: 2.1, category: 'dairy', fat: 33.8, kcal: 410, name: 'Queso cheddar', protein: 24.2, slug: 'queso-cheddar', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 2.2, category: 'dairy', fat: 27.4, kcal: 356, name: 'Queso gouda', protein: 24.9, slug: 'queso-gouda', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 1.4, category: 'dairy', fat: 31, kcal: 393, name: 'Queso emmental', protein: 27, slug: 'queso-emmental', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 0.4, category: 'dairy', fat: 32.3, kcal: 413, name: 'Queso gruyère', protein: 29.8, slug: 'queso-gruyere', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 2.3, category: 'dairy', fat: 28.7, kcal: 353, name: 'Queso azul', protein: 21.4, slug: 'queso-azul', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 1, category: 'dairy', fat: 33, kcal: 380, name: 'Queso de Cabrales', protein: 21, slug: 'queso-cabrales' },
  { allergens: [{ key: 'milk' }], carbs: 1, category: 'dairy', fat: 32, kcal: 392, name: 'Queso manchego semicurado', protein: 26, slug: 'queso-manchego-semicurado' },
  { allergens: [{ key: 'milk' }], carbs: 0.5, category: 'dairy', fat: 34, kcal: 420, name: 'Queso de oveja curado', protein: 28, slug: 'queso-de-oveja-curado' },
  { allergens: [{ key: 'milk' }], carbs: 0.5, category: 'dairy', fat: 35, kcal: 430, name: 'Queso Idiazábal', protein: 27, slug: 'queso-idiazabal' },
  { allergens: [{ key: 'milk' }], carbs: 2.1, category: 'dairy', fat: 26.6, kcal: 351, name: 'Queso provolone', protein: 25.6, slug: 'queso-provolone', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 3.6, category: 'dairy', fat: 26.9, kcal: 387, name: 'Queso pecorino', protein: 31.8, slug: 'queso-pecorino', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 2, category: 'dairy', fat: 29, kcal: 380, name: 'Queso rallado', protein: 27, slug: 'queso-rallado' },
  { allergens: [{ key: 'milk' }], carbs: 3, category: 'dairy', fat: 26, kcal: 330, name: 'Queso en lonchas', protein: 22, slug: 'queso-en-lonchas' },
  // ── Yoghurts and fermented ────────────────────────────────────────────
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4, category: 'dairy', fat: 0.2, kcal: 63, name: 'Skyr', protein: 11, slug: 'skyr' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 14, category: 'dairy', defaultUnit: 'unit', fat: 2.5, gramsPerUnit: 125, kcal: 90, name: 'Yogur de sabores', protein: 3.5, slug: 'yogur-de-sabores' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 12, category: 'dairy', defaultUnit: 'ml', fat: 1.5, kcal: 75, name: 'Yogur bebible', protein: 2.8, slug: 'yogur-bebible' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 13, category: 'dairy', defaultUnit: 'unit', fat: 4.5, gramsPerUnit: 60, kcal: 120, name: 'Petit suisse', protein: 6.5, slug: 'petit-suisse' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 8, category: 'dairy', defaultUnit: 'unit', fat: 4.5, gramsPerUnit: 135, kcal: 90, name: 'Cuajada', protein: 4.5, slug: 'cuajada' },
  { allergens: [{ key: 'soy' }], carbs: 3, category: 'dairy', defaultUnit: 'unit', fat: 2.3, gramsPerUnit: 125, kcal: 50, name: 'Yogur de soja', protein: 4, slug: 'yogur-de-soja' },
  { carbs: 8, category: 'dairy', defaultUnit: 'unit', fat: 10, gramsPerUnit: 125, kcal: 130, name: 'Yogur de coco', protein: 1, slug: 'yogur-de-coco' },
  // ── Milks and creams ──────────────────────────────────────────────────
  { allergens: [{ key: 'milk' }], carbs: 4.7, category: 'dairy', defaultUnit: 'ml', fat: 1.6, kcal: 46, name: 'Leche sin lactosa', protein: 3.2, slug: 'leche-sin-lactosa' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4.5, category: 'dairy', defaultUnit: 'ml', fat: 4.1, kcal: 69, name: 'Leche de cabra', protein: 3.6, slug: 'leche-de-cabra', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 54.4, category: 'dairy', defaultUnit: 'tbsp', fat: 8.7, gramsPerUnit: 20, kcal: 321, name: 'Leche condensada', protein: 7.9, slug: 'leche-condensada', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 10, category: 'dairy', defaultUnit: 'ml', fat: 7.6, kcal: 134, name: 'Leche evaporada', protein: 6.8, slug: 'leche-evaporada', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 38.4, category: 'dairy', defaultUnit: 'tbsp', fat: 26.7, gramsPerUnit: 8, kcal: 496, name: 'Leche en polvo', protein: 26.3, slug: 'leche-en-polvo', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 2.8, category: 'dairy', defaultUnit: 'ml', fat: 36.1, kcal: 340, name: 'Nata para montar', protein: 2.8, slug: 'nata-para-montar', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 12.5, category: 'dairy', defaultUnit: 'tbsp', fat: 22.2, gramsPerUnit: 15, kcal: 257, name: 'Nata montada', protein: 3.2, slug: 'nata-montada', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4.6, category: 'dairy', defaultUnit: 'tbsp', fat: 19.4, gramsPerUnit: 15, kcal: 198, name: 'Crema agria', protein: 2.4, slug: 'crema-agria', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 0, category: 'dairy', defaultUnit: 'tbsp', fat: 99.5, gramsPerUnit: 14, kcal: 876, name: 'Ghee', protein: 0.3, slug: 'ghee', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 0.1, category: 'dairy', defaultUnit: 'tbsp', fat: 81.1, gramsPerUnit: 14, kcal: 717, name: 'Mantequilla sin sal', protein: 0.8, slug: 'mantequilla-sin-sal', source: 'usda' },
  // ── Second pass ───────────────────────────────────────────────────────
  { allergens: [{ key: 'milk' }], carbs: 2.2, category: 'dairy', fat: 35.6, kcal: 452, name: 'Queso de cabra curado', protein: 30.5, slug: 'queso-de-cabra-curado', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 1, category: 'dairy', fat: 31, kcal: 380, name: 'Queso de Mahón', protein: 25, slug: 'queso-de-mahon' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 1, category: 'dairy', fat: 27, kcal: 330, name: 'Queso de Arzúa', protein: 22, slug: 'queso-de-arzua' },
  { allergens: [{ key: 'milk' }], carbs: 1, category: 'dairy', fat: 32, kcal: 370, name: 'Queso de la Serena', protein: 20, slug: 'queso-de-la-serena' },
  { allergens: [{ key: 'milk' }], carbs: 1, category: 'dairy', fat: 30, kcal: 370, name: 'Queso havarti', protein: 24, slug: 'queso-havarti' },
  { allergens: [{ key: 'milk' }], carbs: 1.4, category: 'dairy', fat: 28.6, kcal: 357, name: 'Queso edam', protein: 25, slug: 'queso-edam', source: 'usda' },
  { allergens: [{ key: 'milk' }], carbs: 1, category: 'dairy', fat: 28, kcal: 350, name: 'Queso raclette', protein: 23, slug: 'queso-raclette' },
  { allergens: [{ key: 'milk' }], carbs: 1, category: 'dairy', fat: 25, kcal: 330, name: 'Queso scamorza', protein: 25, slug: 'queso-scamorza' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 5, category: 'dairy', defaultUnit: 'tbsp', fat: 21, gramsPerUnit: 15, kcal: 250, name: 'Queso fundido para untar', protein: 11, slug: 'queso-fundido' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4, category: 'dairy', defaultUnit: 'unit', fat: 0.1, gramsPerUnit: 200, kcal: 60, name: 'Yogur proteico', protein: 10, slug: 'yogur-proteico' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 5.4, category: 'dairy', defaultUnit: 'ml', fat: 7, kcal: 108, name: 'Leche de oveja', protein: 6, slug: 'leche-de-oveja', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4, category: 'dairy', defaultUnit: 'ml', fat: 19, kcal: 200, name: 'Nata ligera', protein: 2.5, slug: 'nata-ligera' }
];

export const DAIRY_NAMES_EN_GB: Record<string, string> = {
  burrata: 'Burrata',
  'crema-agria': 'Soured cream',
  cuajada: 'Cuajada (milk curd)',
  ghee: 'Ghee',
  'leche-condensada': 'Condensed milk',
  'leche-de-cabra': "Goat's milk",
  'leche-de-oveja': "Sheep's milk",
  'leche-en-polvo': 'Milk powder',
  'leche-evaporada': 'Evaporated milk',
  'leche-sin-lactosa': 'Lactose-free milk',
  'mantequilla-sin-sal': 'Unsalted butter',
  mascarpone: 'Mascarpone',
  'mozzarella-fresca': 'Fresh mozzarella',
  'nata-ligera': 'Light cream',
  'nata-montada': 'Whipped cream',
  'nata-para-montar': 'Whipping cream',
  'petit-suisse': 'Petit suisse',
  'queso-azul': 'Blue cheese',
  'queso-batido-desnatado': 'Fat-free quark',
  'queso-brie': 'Brie',
  'queso-cabrales': 'Cabrales cheese',
  'queso-camembert': 'Camembert',
  'queso-cheddar': 'Cheddar',
  'queso-crema': 'Cream cheese',
  'queso-de-arzua': 'Arzúa cheese',
  'queso-de-cabra-curado': "Aged goat's cheese",
  'queso-de-la-serena': 'La Serena cheese',
  'queso-de-mahon': 'Mahón cheese',
  'queso-de-oveja-curado': "Aged sheep's cheese",
  'queso-de-tetilla': 'Tetilla cheese',
  'queso-de-untar-light': 'Light cream cheese',
  'queso-edam': 'Edam',
  'queso-emmental': 'Emmental',
  'queso-en-lonchas': 'Sliced cheese',
  'queso-feta': 'Feta',
  'queso-fundido': 'Processed cheese spread',
  'queso-gouda': 'Gouda',
  'queso-gruyere': 'Gruyère',
  'queso-halloumi': 'Halloumi',
  'queso-havarti': 'Havarti',
  'queso-idiazabal': 'Idiazabal cheese',
  'queso-manchego-semicurado': 'Semi-cured Manchego',
  'queso-pecorino': 'Pecorino',
  'queso-provolone': 'Provolone',
  'queso-raclette': 'Raclette cheese',
  'queso-rallado': 'Grated cheese',
  'queso-scamorza': 'Scamorza',
  'queso-tierno': 'Mild soft cheese',
  ricotta: 'Ricotta',
  'rulo-de-cabra': "Goat's cheese log",
  skyr: 'Skyr',
  'yogur-bebible': 'Drinking yoghurt',
  'yogur-de-coco': 'Coconut yoghurt',
  'yogur-de-sabores': 'Flavoured yoghurt',
  'yogur-de-soja': 'Soya yoghurt',
  'yogur-proteico': 'High-protein yoghurt'
};
