import type { IngredientSeed } from './types';

/**
 * Prepared foods, dips, desserts and sweets — things a shop sells ready to
 * eat. Each carries the allergens of what it is made from and the food class
 * of its filling: a liver pâté is pork, a fabada is pork, a lasagne is meat,
 * a polvorón is pork through its lard. A tinned dish with meat in it says so
 * here for the same reason a croquette does — so it is never offered as a
 * swap into a dish that had none.
 */
export const OTHER: readonly IngredientSeed[] = [
  // ── Dips and spreads ──────────────────────────────────────────────────
  { allergens: [{ key: 'sesame' }], carbs: 14, category: 'other', defaultUnit: 'tbsp', fat: 9, fiber: 4, gramsPerUnit: 15, kcal: 160, name: 'Hummus de remolacha', protein: 6, slug: 'hummus-de-remolacha' },
  { allergens: [{ key: 'sesame' }], carbs: 8, category: 'other', defaultUnit: 'tbsp', fat: 10, fiber: 3, gramsPerUnit: 15, kcal: 130, name: 'Baba ganoush', protein: 3, slug: 'baba-ganoush' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4, category: 'other', defaultUnit: 'tbsp', fat: 8, gramsPerUnit: 15, kcal: 100, name: 'Tzatziki', protein: 4, slug: 'tzatziki' },
  { allergens: [{ key: 'fish', presence: 'may_contain' }], carbs: 5, category: 'other', defaultUnit: 'tbsp', fat: 25, fiber: 3, gramsPerUnit: 15, kcal: 250, name: 'Tapenade', protein: 2, slug: 'tapenade' },
  { allergens: [{ key: 'milk', presence: 'may_contain' }, { key: 'eggs', presence: 'may_contain' }], carbs: 3, category: 'other', classes: ['pork'], defaultUnit: 'tbsp', fat: 29, gramsPerUnit: 15, kcal: 320, name: 'Paté de hígado', protein: 12, slug: 'pate-de-higado' },
  { allergens: [{ key: 'tree_nuts', presence: 'may_contain' }, { key: 'gluten', presence: 'may_contain' }], carbs: 8, category: 'other', defaultUnit: 'tbsp', fat: 18, fiber: 3, gramsPerUnit: 15, kcal: 220, name: 'Paté vegetal', protein: 7, slug: 'pate-vegetal' },
  // ── Ready meals and soups ─────────────────────────────────────────────
  { allergens: [{ key: 'eggs' }], carbs: 14, category: 'other', fat: 11, kcal: 180, name: 'Tortilla de patatas envasada', protein: 6, slug: 'tortilla-de-patatas-envasada' },
  { carbs: 4, category: 'other', defaultUnit: 'ml', fat: 3, fiber: 1, kcal: 45, name: 'Gazpacho envasado', protein: 0.9, slug: 'gazpacho-envasado' },
  { allergens: [{ key: 'gluten' }], carbs: 8, category: 'other', defaultUnit: 'ml', fat: 8, fiber: 1, kcal: 110, name: 'Salmorejo envasado', protein: 1.5, slug: 'salmorejo-envasado' },
  { allergens: [{ key: 'milk', presence: 'may_contain' }, { key: 'celery', presence: 'may_contain' }], carbs: 5, category: 'other', defaultUnit: 'ml', fat: 2.2, fiber: 1.2, kcal: 45, name: 'Crema de verduras envasada', protein: 1.2, slug: 'crema-de-verduras-envasada' },
  { allergens: [{ key: 'milk', presence: 'may_contain' }], carbs: 5, category: 'other', defaultUnit: 'ml', fat: 2.2, fiber: 1.2, kcal: 45, name: 'Crema de calabaza envasada', protein: 1.2, slug: 'crema-de-calabaza-envasada' },
  { allergens: [{ key: 'eggs' }, { key: 'fish' }, { key: 'mustard', presence: 'may_contain' }], carbs: 10, category: 'other', fat: 13, kcal: 170, name: 'Ensaladilla rusa envasada', protein: 3, slug: 'ensaladilla-rusa-envasada' },
  { allergens: [{ key: 'gluten' }, { key: 'fish' }, { key: 'eggs' }], carbs: 28, category: 'other', fat: 13, kcal: 260, name: 'Empanada de atún', protein: 8, slug: 'empanada-de-atun' },
  { allergens: [{ key: 'gluten' }, { key: 'milk' }, { key: 'lactose' }, { key: 'eggs', presence: 'may_contain' }, { key: 'celery', presence: 'may_contain' }], carbs: 14, category: 'other', classes: ['meat'], fat: 7, kcal: 150, name: 'Lasaña preparada', protein: 7, slug: 'lasana-preparada' },
  { allergens: [{ key: 'gluten' }, { key: 'milk' }, { key: 'lactose' }, { key: 'eggs', presence: 'may_contain' }], carbs: 15, category: 'other', classes: ['meat'], fat: 8, kcal: 160, name: 'Canelones preparados', protein: 7, slug: 'canelones-preparados' },
  { carbs: 0, category: 'other', classes: ['meat'], fat: 12, kcal: 200, name: 'Pollo asado envasado', protein: 22, slug: 'pollo-asado-envasado' },
  { allergens: [{ key: 'gluten' }, { key: 'eggs' }, { key: 'milk', presence: 'may_contain' }], carbs: 8, category: 'other', classes: ['pork'], fat: 13, kcal: 200, name: 'Albóndigas envasadas', protein: 12, slug: 'albondigas-envasadas' },
  { carbs: 11, category: 'other', classes: ['pork'], fat: 7, fiber: 3, kcal: 130, name: 'Fabada en lata', protein: 6, slug: 'fabada-en-lata' },
  { carbs: 11, category: 'other', classes: ['pork'], fat: 4, fiber: 3, kcal: 110, name: 'Lentejas con chorizo en lata', protein: 6, slug: 'lentejas-con-chorizo-en-lata' },
  { allergens: [{ key: 'gluten' }, { key: 'celery', presence: 'may_contain' }], carbs: 8, category: 'other', classes: ['meat'], defaultUnit: 'ml', fat: 1, kcal: 50, name: 'Sopa de fideos envasada', protein: 2, slug: 'sopa-de-fideos-envasada' },
  { allergens: [{ key: 'gluten' }, { key: 'soy' }], carbs: 60, category: 'other', defaultUnit: 'unit', fat: 19, gramsPerUnit: 85, kcal: 450, name: 'Ramen instantáneo', protein: 9, slug: 'ramen-instantaneo' },
  { allergens: [{ key: 'milk', presence: 'may_contain' }], carbs: 75, category: 'other', fat: 1, fiber: 6, kcal: 350, name: 'Puré de patatas en copos', protein: 8, slug: 'pure-de-patatas-en-copos' },
  // ── Fruit, preserved ──────────────────────────────────────────────────
  { carbs: 14, category: 'other', fat: 0.1, fiber: 1.5, kcal: 60, name: 'Puré de manzana', protein: 0.2, slug: 'pure-de-manzana' },
  { carbs: 17, category: 'other', fat: 0.1, fiber: 1.5, kcal: 70, name: 'Compota de fruta', protein: 0.3, slug: 'compota-de-fruta' },
  { carbs: 19, category: 'other', fat: 0.1, fiber: 1, kcal: 80, name: 'Fruta en almíbar', protein: 0.4, slug: 'fruta-en-almibar' },
  { carbs: 17, category: 'other', fat: 0.1, fiber: 1, kcal: 70, name: 'Macedonia en conserva', protein: 0.4, slug: 'macedonia-en-conserva' },
  // ── Desserts and sweets ───────────────────────────────────────────────
  { allergens: [{ key: 'milk' }, { key: 'lactose' }, { key: 'eggs' }], carbs: 18, category: 'other', defaultUnit: 'unit', fat: 4, gramsPerUnit: 125, kcal: 120, name: 'Natillas', protein: 3.5, slug: 'natillas' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }, { key: 'eggs' }], carbs: 22, category: 'other', defaultUnit: 'unit', fat: 3, gramsPerUnit: 110, kcal: 130, name: 'Flan de huevo', protein: 4, slug: 'flan-de-huevo' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 22, category: 'other', defaultUnit: 'unit', fat: 3, gramsPerUnit: 130, kcal: 130, name: 'Arroz con leche', protein: 3.5, slug: 'arroz-con-leche' },
  { carbs: 15, category: 'other', classes: ['animal'], defaultUnit: 'unit', fat: 0, gramsPerUnit: 100, kcal: 65, name: 'Gelatina de sabores preparada', protein: 1.5, slug: 'gelatina-de-sabores-preparada' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }, { key: 'eggs' }, { key: 'soy', presence: 'may_contain' }], carbs: 25, category: 'other', defaultUnit: 'unit', fat: 11, gramsPerUnit: 80, kcal: 220, name: 'Mousse de chocolate', protein: 5, slug: 'mousse-de-chocolate' },
  { allergens: [{ key: 'tree_nuts' }, { key: 'eggs', presence: 'may_contain' }, { key: 'milk', presence: 'may_contain' }], carbs: 40, category: 'other', fat: 38, fiber: 5, kcal: 540, name: 'Turrón de Jijona', protein: 14, slug: 'turron-de-jijona' },
  { allergens: [{ key: 'tree_nuts' }, { key: 'eggs' }], carbs: 50, category: 'other', fat: 28, fiber: 4, kcal: 500, name: 'Turrón de Alicante', protein: 12, slug: 'turron-de-alicante' },
  { allergens: [{ key: 'tree_nuts' }, { key: 'eggs', presence: 'may_contain' }], carbs: 55, category: 'other', fat: 22, fiber: 4, kcal: 460, name: 'Mazapán', protein: 9, slug: 'mazapan' },
  { allergens: [{ key: 'gluten' }, { key: 'tree_nuts' }], carbs: 60, category: 'other', classes: ['pork'], defaultUnit: 'unit', fat: 28, gramsPerUnit: 30, kcal: 520, name: 'Polvorón', protein: 6, slug: 'polvoron' },
  { carbs: 6.9, category: 'other', defaultUnit: 'tbsp', fat: 0.2, gramsPerUnit: 15, kcal: 22, name: 'Zumo de limón envasado', protein: 0.4, slug: 'zumo-de-limon-envasado' },
  // ── Second pass ───────────────────────────────────────────────────────
  { carbs: 3, category: 'other', fat: 0.3, fiber: 1.5, kcal: 20, name: 'Ensalada envasada', protein: 1.5, slug: 'ensalada-envasada' },
  { allergens: [{ key: 'gluten' }, { key: 'milk' }], carbs: 30, category: 'other', fat: 9, kcal: 250, name: 'Pizza fresca refrigerada', protein: 11, slug: 'pizza-fresca-refrigerada' },
  { allergens: [{ key: 'gluten' }, { key: 'eggs' }, { key: 'milk' }, { key: 'lactose' }], carbs: 20, category: 'other', defaultUnit: 'slice', fat: 18, gramsPerUnit: 120, kcal: 280, name: 'Quiche de verduras', protein: 9, slug: 'quiche-de-verduras' },
  { carbs: 3, category: 'other', classes: ['pork'], fat: 7, kcal: 120, name: 'Callos en lata', protein: 12, slug: 'callos-en-lata' },
  { carbs: 10, category: 'other', classes: ['pork'], fat: 4.5, fiber: 2, kcal: 110, name: 'Cocido madrileño en lata', protein: 7, slug: 'cocido-madrileno-en-lata' },
  { carbs: 12, category: 'other', fat: 3, fiber: 4, kcal: 100, name: 'Garbanzos con espinacas en lata', protein: 5, slug: 'garbanzos-con-espinacas-en-lata' },
  { carbs: 11, category: 'other', fat: 1.5, fiber: 4, kcal: 80, name: 'Alubias con verduras en lata', protein: 4, slug: 'alubias-con-verduras-en-lata' },
  { allergens: [{ key: 'celery', presence: 'may_contain' }], carbs: 4, category: 'other', defaultUnit: 'ml', fat: 0.5, fiber: 1, kcal: 25, name: 'Sopa de verduras envasada', protein: 1, slug: 'sopa-de-verduras-envasada' },
  { allergens: [{ key: 'milk' }], carbs: 6, category: 'other', defaultUnit: 'ml', fat: 3.5, kcal: 60, name: 'Crema de champiñones envasada', protein: 1.5, slug: 'crema-de-champinones-envasada' },
  { allergens: [{ key: 'tree_nuts' }, { key: 'eggs' }], carbs: 45, category: 'other', defaultUnit: 'slice', fat: 24, gramsPerUnit: 80, kcal: 430, name: 'Tarta de Santiago', protein: 10, slug: 'tarta-de-santiago' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }, { key: 'eggs' }], carbs: 22, category: 'other', defaultUnit: 'unit', fat: 5, gramsPerUnit: 120, kcal: 150, name: 'Crema catalana', protein: 4, slug: 'crema-catalana' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }, { key: 'eggs' }, { key: 'gluten' }], carbs: 30, category: 'other', defaultUnit: 'unit', fat: 15, gramsPerUnit: 100, kcal: 280, name: 'Tiramisú', protein: 5, slug: 'tiramisu' },
  { carbs: 78, category: 'other', classes: ['animal'], fat: 0, kcal: 340, name: 'Gominolas', protein: 6, slug: 'gominolas' },
  { allergens: [{ key: 'milk' }, { key: 'soy', presence: 'may_contain' }, { key: 'tree_nuts', presence: 'may_contain' }], carbs: 50, category: 'other', defaultUnit: 'unit', fat: 36, gramsPerUnit: 12, kcal: 550, name: 'Bombones', protein: 6, slug: 'bombones' }
];

export const OTHER_NAMES_EN_GB: Record<string, string> = {
  'albondigas-envasadas': 'Jarred meatballs',
  'alubias-con-verduras-en-lata': 'Tinned beans with vegetables',
  'arroz-con-leche': 'Rice pudding',
  'baba-ganoush': 'Baba ganoush',
  bombones: 'Chocolates',
  'callos-en-lata': 'Tinned tripe stew (callos)',
  'canelones-preparados': 'Ready-made cannelloni',
  'cocido-madrileno-en-lata': 'Tinned Madrid stew (cocido)',
  'compota-de-fruta': 'Fruit compote',
  'crema-catalana': 'Crema catalana',
  'crema-de-calabaza-envasada': 'Packaged pumpkin soup',
  'crema-de-champinones-envasada': 'Packaged mushroom soup',
  'crema-de-verduras-envasada': 'Packaged vegetable soup',
  'empanada-de-atun': 'Tuna empanada',
  'ensalada-envasada': 'Bagged salad',
  'ensaladilla-rusa-envasada': 'Packaged Russian salad',
  'fabada-en-lata': 'Tinned fabada',
  'flan-de-huevo': 'Crème caramel',
  'fruta-en-almibar': 'Fruit in syrup',
  'garbanzos-con-espinacas-en-lata': 'Tinned chickpeas with spinach',
  'gazpacho-envasado': 'Packaged gazpacho',
  'gelatina-de-sabores-preparada': 'Flavoured jelly',
  gominolas: 'Gummy sweets',
  'hummus-de-remolacha': 'Beetroot hummus',
  'lasana-preparada': 'Ready-made lasagne',
  'lentejas-con-chorizo-en-lata': 'Tinned lentils with chorizo',
  'macedonia-en-conserva': 'Tinned fruit cocktail',
  mazapan: 'Marzipan',
  'mousse-de-chocolate': 'Chocolate mousse',
  natillas: 'Custard (natillas)',
  'pate-de-higado': 'Liver pâté',
  'pate-vegetal': 'Vegetable pâté',
  'pizza-fresca-refrigerada': 'Chilled fresh pizza',
  'pollo-asado-envasado': 'Rotisserie chicken',
  polvoron: 'Polvorón shortbread',
  'pure-de-manzana': 'Apple purée',
  'pure-de-patatas-en-copos': 'Instant mashed potato',
  'quiche-de-verduras': 'Vegetable quiche',
  'ramen-instantaneo': 'Instant ramen',
  'salmorejo-envasado': 'Packaged salmorejo',
  'sopa-de-fideos-envasada': 'Packaged noodle soup',
  'sopa-de-verduras-envasada': 'Packaged vegetable soup',
  tapenade: 'Tapenade',
  'tarta-de-santiago': 'Santiago almond tart',
  tiramisu: 'Tiramisu',
  'tortilla-de-patatas-envasada': 'Packaged Spanish omelette',
  'turron-de-alicante': 'Alicante turrón (hard nougat)',
  'turron-de-jijona': 'Jijona turrón (soft nougat)',
  tzatziki: 'Tzatziki',
  'zumo-de-limon-envasado': 'Bottled lemon juice'
};
