import type { IngredientSeed } from './types';

/**
 * The dry and tinned aisles: grains, flours, pasta, pulses in tins, nuts, dried
 * fruit, oils, sauces, spices. Spices are real numbers per 100 g even though a
 * dish uses a gram; the ratio test skips nothing here, so they have to add up.
 * Wine for cooking carries `sulphites`; its kcal fall under the ratio floor
 * because alcohol is energy the macro formula cannot see. Thai curry pastes
 * carry `crustaceans` and `fish` as `may_contain` — shrimp paste is traditional
 * and the jar decides. Lard is pork to the substitution rule.
 */
export const PANTRY: readonly IngredientSeed[] = [
  // ── Grains, raw ───────────────────────────────────────────────────────
  { carbs: 79.2, category: 'pantry', fat: 0.5, fiber: 0, kcal: 358, name: 'Arroz bomba', protein: 6.5, slug: 'arroz-bomba-crudo', source: 'usda' },
  { carbs: 80, category: 'pantry', fat: 0.7, fiber: 1.3, kcal: 365, name: 'Arroz largo', protein: 7.1, slug: 'arroz-largo-crudo', source: 'usda' },
  {
    carbs: 76.2,
    category: 'pantry',
    fat: 2.7,
    fiber: 3.4,
    kcal: 362,
    name: 'Arroz integral',
    protein: 7.5,
    slug: 'arroz-integral-crudo',
    source: 'usda'
  },
  {
    carbs: 74.9,
    category: 'pantry',
    fat: 1.1,
    fiber: 6.2,
    kcal: 357,
    name: 'Arroz salvaje',
    protein: 14.7,
    slug: 'arroz-salvaje-crudo',
    source: 'usda'
  },
  {
    carbs: 79.2,
    category: 'pantry',
    fat: 0.5,
    fiber: 0,
    kcal: 358,
    name: 'Arroz para sushi',
    protein: 6.5,
    slug: 'arroz-para-sushi',
    source: 'usda'
  },
  { carbs: 73, category: 'pantry', fat: 2, fiber: 4, kcal: 350, name: 'Arroz negro', protein: 8, slug: 'arroz-negro-crudo' },
  { carbs: 64.2, category: 'pantry', fat: 6.1, fiber: 7, kcal: 368, name: 'Quinoa', protein: 14.1, slug: 'quinoa-cruda', source: 'usda' },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 75.9,
    category: 'pantry',
    fat: 1.3,
    fiber: 12.5,
    kcal: 342,
    name: 'Bulgur',
    protein: 12.3,
    slug: 'bulgur-crudo',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 77.4,
    category: 'pantry',
    fat: 0.6,
    fiber: 5,
    kcal: 376,
    name: 'Cuscús',
    protein: 12.8,
    slug: 'cuscus-crudo',
    source: 'usda'
  },
  { carbs: 72.8, category: 'pantry', fat: 4.2, fiber: 8.5, kcal: 378, name: 'Mijo', protein: 11, slug: 'mijo', source: 'usda' },
  {
    carbs: 71.5,
    category: 'pantry',
    fat: 3.4,
    fiber: 10,
    kcal: 343,
    name: 'Trigo sarraceno',
    protein: 13.2,
    slug: 'trigo-sarraceno',
    source: 'usda'
  },
  { carbs: 65.2, category: 'pantry', fat: 7, fiber: 6.7, kcal: 371, name: 'Amaranto', protein: 13.6, slug: 'amaranto', source: 'usda' },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 77.7,
    category: 'pantry',
    fat: 1.2,
    fiber: 15.6,
    kcal: 352,
    name: 'Cebada perlada',
    protein: 9.9,
    slug: 'cebada-perlada',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 70.2,
    category: 'pantry',
    fat: 2.4,
    fiber: 10.7,
    kcal: 338,
    name: 'Espelta en grano',
    protein: 14.6,
    slug: 'espelta-en-grano',
    source: 'usda'
  },
  {
    carbs: 79.5,
    category: 'pantry',
    fat: 1.8,
    fiber: 3.9,
    kcal: 370,
    name: 'Polenta (sémola de maíz)',
    protein: 7.1,
    slug: 'polenta',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 72.8,
    category: 'pantry',
    fat: 1.1,
    fiber: 3.9,
    kcal: 360,
    name: 'Sémola de trigo',
    protein: 12.7,
    slug: 'semola-de-trigo',
    source: 'usda'
  },
  // ── Grains, cooked ────────────────────────────────────────────────────
  { carbs: 23.7, category: 'pantry', fat: 1, fiber: 1.3, kcal: 119, name: 'Mijo cocido', protein: 3.5, slug: 'mijo-cocido', source: 'usda' },
  {
    carbs: 19.9,
    category: 'pantry',
    fat: 0.6,
    fiber: 2.7,
    kcal: 92,
    name: 'Trigo sarraceno cocido',
    protein: 3.4,
    slug: 'trigo-sarraceno-cocido',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 28.2,
    category: 'pantry',
    fat: 0.4,
    fiber: 3.8,
    kcal: 123,
    name: 'Cebada cocida',
    protein: 2.3,
    slug: 'cebada-cocida',
    source: 'usda'
  },
  { carbs: 15, category: 'pantry', fat: 0.3, fiber: 1, kcal: 70, name: 'Polenta cocida', protein: 1.7, slug: 'polenta-cocida' },
  {
    carbs: 21.3,
    category: 'pantry',
    fat: 0.3,
    fiber: 1.8,
    kcal: 101,
    name: 'Arroz salvaje cocido',
    protein: 4,
    slug: 'arroz-salvaje-cocido',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 26.4,
    category: 'pantry',
    fat: 0.8,
    fiber: 3.9,
    kcal: 127,
    name: 'Espelta cocida',
    protein: 5.5,
    slug: 'espelta-cocida',
    source: 'usda'
  },
  // ── Flours and baking ─────────────────────────────────────────────────
  {
    carbs: 57.8,
    category: 'pantry',
    fat: 6.7,
    fiber: 10.8,
    kcal: 387,
    name: 'Harina de garbanzo',
    protein: 22.4,
    slug: 'harina-de-garbanzo',
    source: 'usda'
  },
  { carbs: 76.8, category: 'pantry', fat: 3.9, fiber: 7.3, kcal: 361, name: 'Harina de maíz', protein: 6.9, slug: 'harina-de-maiz', source: 'usda' },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 74.5,
    category: 'pantry',
    fat: 1.9,
    fiber: 13.1,
    kcal: 332,
    name: 'Harina integral de trigo',
    protein: 9.6,
    slug: 'harina-integral',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 68,
    category: 'pantry',
    fat: 2.5,
    fiber: 8,
    kcal: 340,
    name: 'Harina de espelta',
    protein: 14,
    slug: 'harina-de-espelta'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 75.4,
    category: 'pantry',
    fat: 1.5,
    fiber: 11.8,
    kcal: 349,
    name: 'Harina de centeno',
    protein: 10.9,
    slug: 'harina-de-centeno',
    source: 'usda'
  },
  { carbs: 80.1, category: 'pantry', fat: 1.4, fiber: 2.4, kcal: 366, name: 'Harina de arroz', protein: 6, slug: 'harina-de-arroz', source: 'usda' },
  { carbs: 60, category: 'pantry', fat: 13, fiber: 38, kcal: 400, name: 'Harina de coco', protein: 18, slug: 'harina-de-coco' },
  {
    carbs: 83.1,
    category: 'pantry',
    fat: 0.3,
    fiber: 5.9,
    kcal: 357,
    name: 'Fécula de patata',
    protein: 6.9,
    slug: 'fecula-de-patata',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 72.5,
    category: 'pantry',
    fat: 1.7,
    fiber: 2.4,
    kcal: 361,
    name: 'Harina de fuerza',
    protein: 12,
    slug: 'harina-de-fuerza',
    source: 'usda'
  },
  { carbs: 80, category: 'pantry', fat: 3, fiber: 3, kcal: 370, name: 'Pan rallado sin gluten', protein: 4, slug: 'pan-rallado-sin-gluten' },
  { allergens: [{ key: 'gluten' }], carbs: 72, category: 'pantry', fat: 3, fiber: 4, kcal: 370, name: 'Panko', protein: 12, slug: 'panko' },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 75,
    category: 'pantry',
    fat: 1,
    kcal: 350,
    name: 'Harina para tempura',
    protein: 8,
    slug: 'harina-para-tempura'
  },
  {
    carbs: 41.2,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 7.6,
    fiber: 26.9,
    gramsPerUnit: 3,
    kcal: 325,
    name: 'Levadura seca de panadería',
    protein: 40.4,
    slug: 'levadura-seca-de-panaderia',
    source: 'usda'
  },
  {
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0,
    gramsPerUnit: 5,
    kcal: 0,
    name: 'Bicarbonato',
    protein: 0,
    slug: 'bicarbonato',
    source: 'usda'
  },
  {
    carbs: 80,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0.3,
    fiber: 60,
    gramsPerUnit: 2,
    kcal: 300,
    name: 'Agar-agar',
    protein: 6,
    slug: 'agar-agar'
  },
  {
    carbs: 88,
    category: 'pantry',
    classes: ['animal'],
    fat: 0,
    kcal: 380,
    name: 'Gelatina de sabores en polvo',
    protein: 8,
    slug: 'gelatina-de-sabores'
  },
  // ── Sugars and sweet ──────────────────────────────────────────────────
  {
    carbs: 98.1,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0,
    gramsPerUnit: 4,
    kcal: 380,
    name: 'Azúcar moreno',
    protein: 0.1,
    slug: 'azucar-moreno',
    source: 'usda'
  },
  {
    carbs: 99.8,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0,
    gramsPerUnit: 8,
    kcal: 389,
    name: 'Azúcar glas',
    protein: 0,
    slug: 'azucar-glas',
    source: 'usda'
  },
  { carbs: 95, category: 'pantry', defaultUnit: 'tsp', fat: 0.1, gramsPerUnit: 4, kcal: 375, name: 'Panela', protein: 0.5, slug: 'panela' },
  {
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0,
    gramsPerUnit: 4,
    kcal: 0,
    name: 'Edulcorante (eritritol)',
    protein: 0,
    slug: 'edulcorante'
  },
  {
    carbs: 67,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.1,
    gramsPerUnit: 20,
    kcal: 260,
    name: 'Sirope de arce',
    protein: 0,
    slug: 'sirope-de-arce',
    source: 'usda'
  },
  {
    allergens: [{ key: 'milk' }, { key: 'lactose' }, { key: 'soy', presence: 'may_contain' }, { key: 'tree_nuts', presence: 'may_contain' }],
    carbs: 59.4,
    category: 'pantry',
    fat: 29.7,
    fiber: 3.4,
    kcal: 535,
    name: 'Chocolate con leche',
    protein: 7.7,
    slug: 'chocolate-con-leche',
    source: 'usda'
  },
  {
    allergens: [{ key: 'milk' }, { key: 'lactose' }, { key: 'soy', presence: 'may_contain' }],
    carbs: 59.2,
    category: 'pantry',
    fat: 32.1,
    kcal: 539,
    name: 'Chocolate blanco',
    protein: 5.9,
    slug: 'chocolate-blanco',
    source: 'usda'
  },
  {
    allergens: [
      { key: 'soy', presence: 'may_contain' },
      { key: 'milk', presence: 'may_contain' }
    ],
    carbs: 45.9,
    category: 'pantry',
    fat: 42.6,
    fiber: 10.9,
    kcal: 598,
    name: 'Chocolate negro 85%',
    protein: 7.8,
    slug: 'chocolate-negro-85',
    source: 'usda'
  },
  {
    allergens: [
      { key: 'soy', presence: 'may_contain' },
      { key: 'milk', presence: 'may_contain' }
    ],
    carbs: 62,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 25,
    gramsPerUnit: 15,
    kcal: 480,
    name: 'Chips de chocolate',
    protein: 4,
    slug: 'chips-de-chocolate'
  },
  {
    carbs: 68.9,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.1,
    fiber: 1.1,
    gramsPerUnit: 20,
    kcal: 278,
    name: 'Mermelada de melocotón',
    protein: 0.4,
    slug: 'mermelada-de-melocoton',
    source: 'usda'
  },
  {
    carbs: 32,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.1,
    gramsPerUnit: 20,
    kcal: 130,
    name: 'Mermelada light',
    protein: 0.5,
    slug: 'mermelada-light'
  },
  { carbs: 60, category: 'pantry', fat: 0.1, kcal: 240, name: 'Dulce de membrillo', protein: 0.3, slug: 'dulce-de-membrillo' },
  // ── Dried fruit, nuts, seeds and spreads ──────────────────────────────
  { carbs: 80, category: 'pantry', fat: 0.2, fiber: 3.3, kcal: 301, name: 'Pasas', protein: 3.3, slug: 'pasas', source: 'usda' },
  {
    carbs: 75,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 0.4,
    fiber: 8,
    gramsPerUnit: 8,
    kcal: 282,
    name: 'Dátiles',
    protein: 2.5,
    slug: 'datiles',
    source: 'usda'
  },
  {
    allergens: [{ key: 'sulphites' }],
    carbs: 62.6,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 0.5,
    fiber: 7.3,
    gramsPerUnit: 8,
    kcal: 241,
    name: 'Orejones',
    protein: 3.4,
    slug: 'orejones',
    source: 'usda'
  },
  {
    carbs: 63.9,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 0.9,
    fiber: 9.8,
    gramsPerUnit: 20,
    kcal: 249,
    name: 'Higos secos',
    protein: 3.3,
    slug: 'higos-secos',
    source: 'usda'
  },
  {
    carbs: 63.9,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 0.4,
    fiber: 7.1,
    gramsPerUnit: 10,
    kcal: 240,
    name: 'Ciruelas pasas',
    protein: 2.2,
    slug: 'ciruelas-pasas',
    source: 'usda'
  },
  {
    carbs: 82.8,
    category: 'pantry',
    fat: 1.1,
    fiber: 5.3,
    kcal: 308,
    name: 'Arándanos deshidratados',
    protein: 0.2,
    slug: 'arandanos-deshidratados',
    source: 'usda'
  },
  {
    allergens: [{ key: 'tree_nuts' }, { key: 'peanuts' }],
    carbs: 15,
    category: 'pantry',
    fat: 50,
    fiber: 7,
    kcal: 600,
    name: 'Mix de frutos secos',
    protein: 20,
    slug: 'mix-de-frutos-secos'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 13.9,
    category: 'pantry',
    fat: 72,
    fiber: 9.6,
    kcal: 691,
    name: 'Nueces pecanas',
    protein: 9.2,
    slug: 'nueces-pecanas',
    source: 'usda'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 13.8,
    category: 'pantry',
    fat: 75.8,
    fiber: 8.6,
    kcal: 718,
    name: 'Nueces de macadamia',
    protein: 7.9,
    slug: 'nueces-de-macadamia',
    source: 'usda'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 11.7,
    category: 'pantry',
    fat: 67.1,
    fiber: 7.5,
    kcal: 659,
    name: 'Nueces de Brasil',
    protein: 14.3,
    slug: 'nueces-de-brasil',
    source: 'usda'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 13.1,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 68.4,
    fiber: 3.7,
    gramsPerUnit: 10,
    kcal: 673,
    name: 'Piñones',
    protein: 13.7,
    slug: 'pinones',
    source: 'usda'
  },
  { carbs: 53, category: 'pantry', fat: 2.2, fiber: 5.1, kcal: 245, name: 'Castañas asadas', protein: 3.2, slug: 'castanas-asadas', source: 'usda' },
  {
    carbs: 28.1,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 41.6,
    fiber: 19.5,
    gramsPerUnit: 9,
    kcal: 525,
    name: 'Semillas de amapola',
    protein: 18,
    slug: 'semillas-de-amapola',
    source: 'usda'
  },
  {
    carbs: 8.7,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 48.8,
    fiber: 4,
    gramsPerUnit: 10,
    kcal: 553,
    name: 'Semillas de cáñamo',
    protein: 31.6,
    slug: 'semillas-de-canamo',
    source: 'usda'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 18.8,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 55.5,
    fiber: 10.3,
    gramsPerUnit: 16,
    kcal: 614,
    name: 'Crema de almendras',
    protein: 21,
    slug: 'crema-de-almendras',
    source: 'usda'
  },
  {
    allergens: [{ key: 'tree_nuts' }, { key: 'milk' }, { key: 'soy', presence: 'may_contain' }],
    carbs: 57,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 31,
    gramsPerUnit: 15,
    kcal: 540,
    name: 'Crema de avellanas y cacao',
    protein: 6,
    slug: 'crema-de-avellanas-y-cacao'
  },
  // ── Pasta and noodles, dry ────────────────────────────────────────────
  {
    allergens: [{ key: 'gluten' }],
    carbs: 74.7,
    category: 'pantry',
    fat: 1.5,
    fiber: 3.2,
    kcal: 371,
    name: 'Espaguetis',
    protein: 13,
    slug: 'espaguetis-secos',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 74.7,
    category: 'pantry',
    fat: 1.5,
    fiber: 3.2,
    kcal: 371,
    name: 'Macarrones',
    protein: 13,
    slug: 'macarrones-secos',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 73.4,
    category: 'pantry',
    fat: 2.9,
    fiber: 9.2,
    kcal: 352,
    name: 'Pasta integral seca',
    protein: 13.9,
    slug: 'pasta-integral-seca',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'eggs', presence: 'may_contain' }],
    carbs: 72,
    category: 'pantry',
    fat: 1.5,
    fiber: 3,
    kcal: 360,
    name: 'Placas de lasaña',
    protein: 13,
    slug: 'placas-de-lasana'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'eggs' }],
    carbs: 54.7,
    category: 'pantry',
    fat: 2.3,
    fiber: 0,
    kcal: 288,
    name: 'Pasta fresca al huevo',
    protein: 11.3,
    slug: 'pasta-fresca-al-huevo',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'eggs' }, { key: 'milk' }],
    carbs: 40,
    category: 'pantry',
    fat: 7,
    kcal: 270,
    name: 'Raviolis frescos',
    protein: 11,
    slug: 'raviolis-frescos'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'eggs', presence: 'may_contain' }],
    carbs: 38,
    category: 'pantry',
    fat: 1.5,
    fiber: 2,
    kcal: 180,
    name: 'Ñoquis',
    protein: 4,
    slug: 'noquis'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 72,
    category: 'pantry',
    fat: 1.5,
    fiber: 3,
    kcal: 360,
    name: 'Fideos finos',
    protein: 13,
    slug: 'fideos-finos'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 72,
    category: 'pantry',
    fat: 4,
    fiber: 2.5,
    kcal: 370,
    name: 'Noodles de trigo',
    protein: 11,
    slug: 'noodles-de-trigo'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 70,
    category: 'pantry',
    fat: 1.5,
    fiber: 2,
    kcal: 340,
    name: 'Noodles udon',
    protein: 10,
    slug: 'noodles-udon'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 74.6,
    category: 'pantry',
    fat: 0.7,
    fiber: 0,
    kcal: 336,
    name: 'Fideos soba',
    protein: 14.4,
    slug: 'fideos-soba',
    source: 'usda'
  },
  {
    carbs: 80.2,
    category: 'pantry',
    fat: 0.6,
    fiber: 1.6,
    kcal: 364,
    name: 'Fideos de arroz secos',
    protein: 6,
    slug: 'fideos-de-arroz-secos',
    source: 'usda'
  },
  { carbs: 53, category: 'pantry', fat: 2, fiber: 8, kcal: 340, name: 'Pasta de lentejas', protein: 25, slug: 'pasta-de-lentejas' },
  { carbs: 56, category: 'pantry', fat: 5, fiber: 7, kcal: 350, name: 'Pasta de garbanzos', protein: 20, slug: 'pasta-de-garbanzos' },
  { carbs: 76, category: 'pantry', fat: 1.5, fiber: 2, kcal: 350, name: 'Pasta sin gluten', protein: 7, slug: 'pasta-sin-gluten' },
  // ── Tins and jars ─────────────────────────────────────────────────────
  {
    carbs: 11.8,
    category: 'pantry',
    fat: 0.9,
    fiber: 0,
    kcal: 71,
    name: 'Guisantes en conserva',
    protein: 4.3,
    slug: 'guisantes-en-conserva',
    source: 'usda'
  },
  { carbs: 11, category: 'pantry', fat: 0.6, fiber: 4, kcal: 80, name: 'Habas en conserva', protein: 5, slug: 'habas-en-conserva' },
  { carbs: 5.5, category: 'pantry', fat: 0.3, fiber: 1.5, kcal: 30, name: 'Pimientos del piquillo', protein: 1.2, slug: 'pimiento-del-piquillo' },
  {
    carbs: 5.5,
    category: 'pantry',
    fat: 0.3,
    fiber: 1.5,
    kcal: 30,
    name: 'Pimientos asados en conserva',
    protein: 1.2,
    slug: 'pimientos-asados-en-conserva'
  },
  {
    carbs: 2,
    category: 'pantry',
    fat: 0.2,
    fiber: 1.2,
    kcal: 18,
    name: 'Espárragos blancos en conserva',
    protein: 1.8,
    slug: 'esparragos-blancos-en-conserva'
  },
  { carbs: 5, category: 'pantry', fat: 0.5, fiber: 3, kcal: 35, name: 'Alcachofas en conserva', protein: 2.5, slug: 'alcachofas-en-conserva' },
  {
    carbs: 5.1,
    category: 'pantry',
    fat: 0.3,
    fiber: 2.4,
    kcal: 25,
    name: 'Champiñones en conserva',
    protein: 1.9,
    slug: 'champinones-en-conserva',
    source: 'usda'
  },
  {
    carbs: 7.2,
    category: 'pantry',
    fat: 0.1,
    fiber: 1.8,
    kcal: 31,
    name: 'Remolacha en conserva',
    protein: 0.9,
    slug: 'remolacha-en-conserva',
    source: 'usda'
  },
  { carbs: 23, category: 'pantry', fat: 14, fiber: 6, kcal: 210, name: 'Tomate seco en aceite', protein: 5, slug: 'tomate-seco-en-aceite' },
  {
    carbs: 3.5,
    category: 'pantry',
    fat: 0.2,
    fiber: 1.9,
    kcal: 16,
    name: 'Tomate entero pelado',
    protein: 0.8,
    slug: 'tomate-entero-pelado',
    source: 'usda'
  },
  {
    carbs: 18.9,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.5,
    fiber: 4.1,
    gramsPerUnit: 15,
    kcal: 82,
    name: 'Concentrado de tomate',
    protein: 4.3,
    slug: 'concentrado-de-tomate',
    source: 'usda'
  },
  { carbs: 8, category: 'pantry', fat: 6, fiber: 2, kcal: 90, name: 'Sofrito envasado', protein: 1.5, slug: 'sofrito-envasado' },
  {
    allergens: [{ key: 'fish' }],
    carbs: 1,
    category: 'pantry',
    fat: 15,
    kcal: 150,
    name: 'Aceitunas rellenas de anchoa',
    protein: 1.5,
    slug: 'aceitunas-rellenas-de-anchoa'
  },
  { carbs: 5, category: 'pantry', fat: 0.1, fiber: 1, kcal: 25, name: 'Cebolletas en vinagre', protein: 0.8, slug: 'cebolletas-en-vinagre' },
  { carbs: 3.5, category: 'pantry', fat: 0.3, fiber: 1.5, kcal: 20, name: 'Guindillas en vinagre', protein: 0.8, slug: 'guindillas-en-vinagre' },
  { carbs: 4.6, category: 'pantry', fat: 0.6, fiber: 2.4, kcal: 28, name: 'Palmitos', protein: 2.5, slug: 'palmitos', source: 'usda' },
  {
    allergens: [
      { key: 'fish', presence: 'may_contain' },
      { key: 'crustaceans', presence: 'may_contain' }
    ],
    carbs: 2.4,
    category: 'pantry',
    fat: 0.5,
    fiber: 1.6,
    kcal: 15,
    name: 'Kimchi',
    protein: 1.1,
    slug: 'kimchi',
    source: 'usda'
  },
  { carbs: 4.3, category: 'pantry', fat: 0.1, fiber: 2.9, kcal: 19, name: 'Chucrut', protein: 0.9, slug: 'chucrut', source: 'usda' },
  { carbs: 2.6, category: 'pantry', fat: 0.4, fiber: 1.7, kcal: 19, name: 'Brotes de bambú', protein: 1.8, slug: 'brotes-de-bambu' },
  {
    carbs: 44,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 3,
    fiber: 35,
    gramsPerUnit: 3,
    kcal: 350,
    name: 'Alga nori',
    protein: 41,
    slug: 'alga-nori'
  },
  { carbs: 50, category: 'pantry', fat: 2.5, fiber: 35, kcal: 300, name: 'Alga wakame', protein: 18, slug: 'alga-wakame' },
  { carbs: 55, category: 'pantry', fat: 1, fiber: 35, kcal: 250, name: 'Alga kombu', protein: 8, slug: 'alga-kombu' },
  {
    carbs: 23.9,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 7.7,
    fiber: 3.6,
    gramsPerUnit: 3,
    kcal: 290,
    name: 'Espirulina',
    protein: 57.5,
    slug: 'espirulina',
    source: 'usda'
  },
  {
    carbs: 2.8,
    category: 'pantry',
    defaultUnit: 'ml',
    fat: 21.3,
    kcal: 197,
    name: 'Leche de coco en lata',
    protein: 2,
    slug: 'leche-de-coco',
    source: 'usda'
  },
  {
    carbs: 6,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 34,
    gramsPerUnit: 15,
    kcal: 330,
    name: 'Crema de coco',
    protein: 3.5,
    slug: 'crema-de-coco'
  },
  {
    allergens: [{ key: 'soy' }],
    carbs: 5,
    category: 'pantry',
    defaultUnit: 'ml',
    fat: 14,
    kcal: 150,
    name: 'Nata vegetal de soja',
    protein: 3,
    slug: 'nata-vegetal-de-soja'
  },
  {
    allergens: [{ key: 'gluten', presence: 'may_contain' }],
    carbs: 8,
    category: 'pantry',
    defaultUnit: 'ml',
    fat: 12,
    kcal: 140,
    name: 'Nata vegetal de avena',
    protein: 1,
    slug: 'nata-vegetal-de-avena'
  },
  { carbs: 22, category: 'pantry', fat: 24, kcal: 300, name: 'Queso vegano', protein: 1, slug: 'queso-vegano' },
  // ── Oils and fats ─────────────────────────────────────────────────────
  {
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 100,
    gramsPerUnit: 14,
    kcal: 884,
    name: 'Aceite de oliva suave',
    protein: 0,
    slug: 'aceite-de-oliva-suave',
    source: 'usda'
  },
  {
    allergens: [{ key: 'sesame' }],
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 100,
    gramsPerUnit: 5,
    kcal: 884,
    name: 'Aceite de sésamo',
    protein: 0,
    slug: 'aceite-de-sesamo',
    source: 'usda'
  },
  {
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 100,
    gramsPerUnit: 14,
    kcal: 884,
    name: 'Aceite de aguacate',
    protein: 0,
    slug: 'aceite-de-aguacate',
    source: 'usda'
  },
  {
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 100,
    gramsPerUnit: 14,
    kcal: 884,
    name: 'Aceite de lino',
    protein: 0.1,
    slug: 'aceite-de-lino',
    source: 'usda'
  },
  {
    carbs: 0,
    category: 'pantry',
    classes: ['pork'],
    defaultUnit: 'tbsp',
    fat: 100,
    gramsPerUnit: 13,
    kcal: 902,
    name: 'Manteca de cerdo',
    protein: 0,
    slug: 'manteca-de-cerdo',
    source: 'usda'
  },
  {
    allergens: [
      { key: 'milk', presence: 'may_contain' },
      { key: 'soy', presence: 'may_contain' }
    ],
    carbs: 0.7,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 80.7,
    gramsPerUnit: 14,
    kcal: 717,
    name: 'Margarina',
    protein: 0.2,
    slug: 'margarina',
    source: 'usda'
  },
  // ── Stocks and wine ───────────────────────────────────────────────────
  {
    allergens: [{ key: 'fish' }],
    carbs: 0.5,
    category: 'pantry',
    defaultUnit: 'ml',
    fat: 0.2,
    kcal: 8,
    name: 'Caldo de pescado',
    protein: 1.2,
    slug: 'caldo-de-pescado'
  },
  {
    carbs: 0.5,
    category: 'pantry',
    classes: ['meat'],
    defaultUnit: 'ml',
    fat: 0.3,
    kcal: 10,
    name: 'Caldo de carne',
    protein: 1.5,
    slug: 'caldo-de-carne'
  },
  {
    allergens: [
      { key: 'celery', presence: 'may_contain' },
      { key: 'gluten', presence: 'may_contain' },
      { key: 'milk', presence: 'may_contain' }
    ],
    carbs: 20,
    category: 'pantry',
    classes: ['meat'],
    defaultUnit: 'unit',
    fat: 13,
    gramsPerUnit: 10,
    kcal: 250,
    name: 'Pastilla de caldo de pollo',
    protein: 12,
    slug: 'pastilla-de-caldo'
  },
  {
    allergens: [{ key: 'fish' }],
    carbs: 0.3,
    category: 'pantry',
    defaultUnit: 'ml',
    fat: 0,
    kcal: 5,
    name: 'Caldo dashi',
    protein: 0.8,
    slug: 'caldo-dashi'
  },
  {
    allergens: [{ key: 'sulphites' }],
    carbs: 2.6,
    category: 'pantry',
    defaultUnit: 'ml',
    fat: 0,
    kcal: 82,
    name: 'Vino blanco para cocinar',
    protein: 0.1,
    slug: 'vino-blanco',
    source: 'usda'
  },
  {
    allergens: [{ key: 'sulphites' }],
    carbs: 2.6,
    category: 'pantry',
    defaultUnit: 'ml',
    fat: 0,
    kcal: 85,
    name: 'Vino tinto para cocinar',
    protein: 0.1,
    slug: 'vino-tinto',
    source: 'usda'
  },
  // ── Vinegars, sauces and condiments ───────────────────────────────────
  {
    allergens: [{ key: 'sulphites', presence: 'may_contain' }],
    carbs: 17,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0,
    gramsPerUnit: 15,
    kcal: 88,
    name: 'Vinagre balsámico',
    protein: 0.5,
    slug: 'vinagre-balsamico',
    source: 'usda'
  },
  {
    carbs: 4.5,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0,
    gramsPerUnit: 15,
    kcal: 18,
    name: 'Vinagre de arroz',
    protein: 0,
    slug: 'vinagre-de-arroz'
  },
  {
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0,
    gramsPerUnit: 15,
    kcal: 18,
    name: 'Vinagre blanco',
    protein: 0,
    slug: 'vinagre-blanco',
    source: 'usda'
  },
  {
    allergens: [{ key: 'soy' }, { key: 'gluten' }],
    carbs: 15.6,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0,
    gramsPerUnit: 15,
    kcal: 89,
    name: 'Salsa teriyaki',
    protein: 5.9,
    slug: 'salsa-teriyaki',
    source: 'usda'
  },
  {
    allergens: [{ key: 'soy' }],
    carbs: 5.6,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.1,
    fiber: 0.8,
    gramsPerUnit: 15,
    kcal: 60,
    name: 'Tamari',
    protein: 10.5,
    slug: 'tamari',
    source: 'usda'
  },
  {
    allergens: [{ key: 'soy' }, { key: 'gluten' }],
    carbs: 6,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0,
    gramsPerUnit: 15,
    kcal: 50,
    name: 'Salsa de soja baja en sal',
    protein: 6,
    slug: 'salsa-de-soja-baja-en-sal'
  },
  {
    allergens: [{ key: 'molluscs' }, { key: 'gluten', presence: 'may_contain' }, { key: 'soy', presence: 'may_contain' }],
    carbs: 10.9,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.2,
    gramsPerUnit: 15,
    kcal: 51,
    name: 'Salsa de ostras',
    protein: 1.4,
    slug: 'salsa-de-ostras',
    source: 'usda'
  },
  {
    allergens: [{ key: 'fish' }],
    carbs: 3.6,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0,
    gramsPerUnit: 5,
    kcal: 35,
    name: 'Salsa de pescado',
    protein: 5.1,
    slug: 'salsa-de-pescado',
    source: 'usda'
  },
  {
    allergens: [{ key: 'soy' }, { key: 'gluten', presence: 'may_contain' }],
    carbs: 25.4,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 6,
    fiber: 5.4,
    gramsPerUnit: 17,
    kcal: 198,
    name: 'Miso',
    protein: 12.8,
    slug: 'miso',
    source: 'usda'
  },
  {
    allergens: [{ key: 'mustard', presence: 'may_contain' }],
    carbs: 24,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 1,
    fiber: 3,
    gramsPerUnit: 5,
    kcal: 110,
    name: 'Wasabi en pasta',
    protein: 2,
    slug: 'wasabi'
  },
  {
    allergens: [
      { key: 'crustaceans', presence: 'may_contain' },
      { key: 'fish', presence: 'may_contain' }
    ],
    carbs: 15,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 5,
    fiber: 2,
    gramsPerUnit: 15,
    kcal: 110,
    name: 'Pasta de curry rojo',
    protein: 3,
    slug: 'pasta-de-curry-rojo'
  },
  {
    allergens: [
      { key: 'crustaceans', presence: 'may_contain' },
      { key: 'fish', presence: 'may_contain' }
    ],
    carbs: 13,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 5,
    fiber: 2,
    gramsPerUnit: 15,
    kcal: 100,
    name: 'Pasta de curry verde',
    protein: 3,
    slug: 'pasta-de-curry-verde'
  },
  {
    allergens: [{ key: 'mustard' }],
    carbs: 8,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 10,
    fiber: 3,
    gramsPerUnit: 5,
    kcal: 150,
    name: 'Mostaza antigua',
    protein: 6,
    slug: 'mostaza-antigua'
  },
  {
    allergens: [{ key: 'mustard' }],
    carbs: 25,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 6,
    gramsPerUnit: 6,
    kcal: 170,
    name: 'Mostaza de miel',
    protein: 3,
    slug: 'mostaza-de-miel'
  },
  {
    allergens: [{ key: 'eggs' }, { key: 'milk' }, { key: 'fish' }, { key: 'mustard', presence: 'may_contain' }],
    carbs: 5,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 47,
    gramsPerUnit: 15,
    kcal: 450,
    name: 'Salsa césar',
    protein: 2,
    slug: 'salsa-cesar'
  },
  {
    allergens: [{ key: 'milk' }, { key: 'lactose' }],
    carbs: 8,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 8,
    gramsPerUnit: 15,
    kcal: 120,
    name: 'Salsa de yogur',
    protein: 4,
    slug: 'salsa-de-yogur'
  },
  {
    allergens: [{ key: 'eggs' }, { key: 'mustard', presence: 'may_contain' }],
    carbs: 8,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 38,
    gramsPerUnit: 15,
    kcal: 380,
    name: 'Salsa tártara',
    protein: 1.5,
    slug: 'salsa-tartara'
  },
  { carbs: 10, category: 'pantry', defaultUnit: 'tbsp', fat: 5, gramsPerUnit: 15, kcal: 90, name: 'Salsa brava', protein: 1.5, slug: 'salsa-brava' },
  {
    allergens: [{ key: 'fish' }, { key: 'gluten', presence: 'may_contain' }],
    carbs: 19.2,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0,
    gramsPerUnit: 5,
    kcal: 77,
    name: 'Salsa Worcestershire',
    protein: 0,
    slug: 'salsa-worcestershire',
    source: 'usda'
  },
  {
    allergens: [{ key: 'soy', presence: 'may_contain' }],
    carbs: 36,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.3,
    gramsPerUnit: 15,
    kcal: 150,
    name: 'Salsa agridulce',
    protein: 0.5,
    slug: 'salsa-agridulce'
  },
  {
    allergens: [{ key: 'soy' }, { key: 'gluten' }, { key: 'sesame', presence: 'may_contain' }],
    carbs: 44.1,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 3.4,
    fiber: 2.8,
    gramsPerUnit: 15,
    kcal: 220,
    name: 'Salsa hoisin',
    protein: 3.3,
    slug: 'salsa-hoisin',
    source: 'usda'
  },
  {
    allergens: [{ key: 'peanuts' }, { key: 'soy' }],
    carbs: 15,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 18,
    gramsPerUnit: 15,
    kcal: 250,
    name: 'Salsa satay',
    protein: 10,
    slug: 'salsa-satay'
  },
  {
    allergens: [{ key: 'tree_nuts' }, { key: 'milk' }],
    carbs: 8,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 31,
    gramsPerUnit: 16,
    kcal: 330,
    name: 'Pesto rojo',
    protein: 5,
    slug: 'pesto-rojo'
  },
  {
    allergens: [{ key: 'celery', presence: 'may_contain' }],
    carbs: 7,
    category: 'pantry',
    classes: ['meat'],
    fat: 4.5,
    kcal: 90,
    name: 'Salsa boloñesa envasada',
    protein: 5,
    slug: 'salsa-bolonesa-envasada'
  },
  {
    allergens: [{ key: 'milk' }, { key: 'lactose' }, { key: 'eggs' }],
    carbs: 5,
    category: 'pantry',
    classes: ['pork'],
    fat: 13,
    kcal: 150,
    name: 'Salsa carbonara envasada',
    protein: 4,
    slug: 'salsa-carbonara-envasada'
  },
  {
    allergens: [{ key: 'milk' }, { key: 'lactose' }],
    carbs: 6,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 15,
    gramsPerUnit: 15,
    kcal: 180,
    name: 'Salsa de queso',
    protein: 6,
    slug: 'salsa-de-queso'
  },
  { carbs: 10, category: 'pantry', defaultUnit: 'tsp', fat: 5, fiber: 4, gramsPerUnit: 5, kcal: 100, name: 'Harissa', protein: 3, slug: 'harissa' },
  { carbs: 5, category: 'pantry', defaultUnit: 'tbsp', fat: 25, gramsPerUnit: 15, kcal: 250, name: 'Chimichurri', protein: 1.5, slug: 'chimichurri' },
  {
    carbs: 48,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.3,
    gramsPerUnit: 15,
    kcal: 200,
    name: 'Chutney de mango',
    protein: 0.5,
    slug: 'chutney-de-mango'
  },
  {
    allergens: [{ key: 'mustard', presence: 'may_contain' }],
    carbs: 8,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 25,
    gramsPerUnit: 15,
    kcal: 250,
    name: 'Vinagreta envasada',
    protein: 0.5,
    slug: 'vinagreta-envasada'
  },
  // ── Spices and dried herbs ────────────────────────────────────────────
  {
    carbs: 64,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 3.3,
    fiber: 25.3,
    gramsPerUnit: 2,
    kcal: 251,
    name: 'Pimienta negra',
    protein: 10.4,
    slug: 'pimienta-negra',
    source: 'usda'
  },
  {
    carbs: 68.6,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 2.1,
    fiber: 26.2,
    gramsPerUnit: 2,
    kcal: 296,
    name: 'Pimienta blanca',
    protein: 10.4,
    slug: 'pimienta-blanca',
    source: 'usda'
  },
  {
    carbs: 56.6,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 17.3,
    fiber: 27.2,
    gramsPerUnit: 2,
    kcal: 318,
    name: 'Cayena molida',
    protein: 12,
    slug: 'cayena-molida',
    source: 'usda'
  },
  {
    carbs: 56,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 14,
    fiber: 28,
    gramsPerUnit: 1,
    kcal: 300,
    name: 'Guindilla seca',
    protein: 12,
    slug: 'guindilla-seca'
  },
  {
    carbs: 54,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 12.9,
    fiber: 34.9,
    gramsPerUnit: 2,
    kcal: 282,
    name: 'Pimentón picante',
    protein: 14.1,
    slug: 'pimenton-picante',
    source: 'usda'
  },
  {
    carbs: 54,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 12.9,
    fiber: 34.9,
    gramsPerUnit: 2,
    kcal: 282,
    name: 'Pimentón ahumado',
    protein: 14.1,
    slug: 'pimenton-ahumado',
    source: 'usda'
  },
  {
    carbs: 63.9,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 7.4,
    fiber: 37,
    gramsPerUnit: 1,
    kcal: 276,
    name: 'Tomillo seco',
    protein: 9.1,
    slug: 'tomillo-seco',
    source: 'usda'
  },
  {
    carbs: 64.1,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 15.2,
    fiber: 42.6,
    gramsPerUnit: 1,
    kcal: 331,
    name: 'Romero seco',
    protein: 4.9,
    slug: 'romero-seco',
    source: 'usda'
  },
  {
    carbs: 47.8,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 4.1,
    fiber: 37.7,
    gramsPerUnit: 1,
    kcal: 233,
    name: 'Albahaca seca',
    protein: 23,
    slug: 'albahaca-seca',
    source: 'usda'
  },
  {
    carbs: 50.6,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 5.5,
    fiber: 26.7,
    gramsPerUnit: 1,
    kcal: 292,
    name: 'Perejil seco',
    protein: 26.6,
    slug: 'perejil-seco',
    source: 'usda'
  },
  {
    carbs: 55.8,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 4.4,
    fiber: 13.6,
    gramsPerUnit: 1,
    kcal: 253,
    name: 'Eneldo seco',
    protein: 20,
    slug: 'eneldo-seco',
    source: 'usda'
  },
  {
    carbs: 50.2,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 7.2,
    fiber: 7.4,
    gramsPerUnit: 1,
    kcal: 295,
    name: 'Estragón seco',
    protein: 22.8,
    slug: 'estragon-seco',
    source: 'usda'
  },
  {
    carbs: 60,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 7,
    fiber: 30,
    gramsPerUnit: 1,
    kcal: 280,
    name: 'Hierbas provenzales',
    protein: 11,
    slug: 'hierbas-provenzales'
  },
  {
    carbs: 79.1,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 1,
    fiber: 15.2,
    gramsPerUnit: 2,
    kcal: 341,
    name: 'Cebolla en polvo',
    protein: 10.4,
    slug: 'cebolla-en-polvo',
    source: 'usda'
  },
  {
    carbs: 72.7,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0.7,
    fiber: 9,
    gramsPerUnit: 3,
    kcal: 331,
    name: 'Ajo en polvo',
    protein: 16.6,
    slug: 'ajo-en-polvo',
    source: 'usda'
  },
  {
    carbs: 45,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 15,
    fiber: 25,
    gramsPerUnit: 2,
    kcal: 380,
    name: 'Garam masala',
    protein: 14,
    slug: 'garam-masala'
  },
  {
    carbs: 50,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 12,
    fiber: 20,
    gramsPerUnit: 2,
    kcal: 350,
    name: 'Ras el hanout',
    protein: 12,
    slug: 'ras-el-hanout'
  },
  {
    carbs: 55,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 10,
    fiber: 20,
    gramsPerUnit: 2,
    kcal: 350,
    name: 'Cinco especias chinas',
    protein: 10,
    slug: 'cinco-especias-chinas'
  },
  {
    carbs: 68.5,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 6.7,
    fiber: 28,
    gramsPerUnit: 2,
    kcal: 311,
    name: 'Cardamomo molido',
    protein: 10.8,
    slug: 'cardamomo-molido',
    source: 'usda'
  },
  {
    carbs: 65.5,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 13,
    fiber: 33.9,
    gramsPerUnit: 2,
    kcal: 274,
    name: 'Clavo molido',
    protein: 6,
    slug: 'clavo-molido',
    source: 'usda'
  },
  {
    carbs: 50,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 15.9,
    fiber: 14.6,
    gramsPerUnit: 2,
    kcal: 337,
    name: 'Anís en grano',
    protein: 17.6,
    slug: 'anis-en-grano',
    source: 'usda'
  },
  {
    carbs: 65.4,
    category: 'pantry',
    defaultUnit: 'pinch',
    fat: 5.8,
    fiber: 3.9,
    gramsPerUnit: 0.1,
    kcal: 310,
    name: 'Azafrán',
    protein: 11.4,
    slug: 'azafran',
    source: 'usda'
  },
  {
    carbs: 52.3,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 14.9,
    fiber: 39.8,
    gramsPerUnit: 2,
    kcal: 345,
    name: 'Semillas de hinojo',
    protein: 15.8,
    slug: 'semillas-de-hinojo',
    source: 'usda'
  },
  {
    carbs: 55,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 17.8,
    fiber: 41.9,
    gramsPerUnit: 2,
    kcal: 298,
    name: 'Cilantro molido',
    protein: 12.4,
    slug: 'cilantro-molido',
    source: 'usda'
  },
  // ── Breakfast and snacks ──────────────────────────────────────────────
  {
    allergens: [{ key: 'gluten', presence: 'may_contain' }, { key: 'tree_nuts' }, { key: 'soy', presence: 'may_contain' }],
    carbs: 53.9,
    category: 'pantry',
    fat: 24.3,
    fiber: 8.9,
    kcal: 489,
    name: 'Granola',
    protein: 13.7,
    slug: 'granola',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 75,
    category: 'pantry',
    fat: 2.5,
    fiber: 10,
    kcal: 370,
    name: 'Cereales integrales de desayuno',
    protein: 9,
    slug: 'cereales-integrales'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'milk', presence: 'may_contain' }, { key: 'soy', presence: 'may_contain' }],
    carbs: 80,
    category: 'pantry',
    fat: 4,
    fiber: 5,
    kcal: 390,
    name: 'Cereales de chocolate',
    protein: 7,
    slug: 'cereales-de-chocolate'
  },
  {
    allergens: [{ key: 'gluten', presence: 'may_contain' }],
    carbs: 66.2,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 7,
    fiber: 15.4,
    gramsPerUnit: 8,
    kcal: 246,
    name: 'Salvado de avena',
    protein: 17.3,
    slug: 'salvado-de-avena',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 64.5,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 4.2,
    fiber: 42.8,
    gramsPerUnit: 6,
    kcal: 216,
    name: 'Salvado de trigo',
    protein: 15.6,
    slug: 'salvado-de-trigo',
    source: 'usda'
  },
  {
    allergens: [
      { key: 'gluten' },
      { key: 'milk', presence: 'may_contain' },
      { key: 'eggs', presence: 'may_contain' },
      { key: 'soy', presence: 'may_contain' }
    ],
    carbs: 70.5,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 10.6,
    fiber: 3.5,
    gramsPerUnit: 5,
    kcal: 406,
    name: 'Galletas maría',
    protein: 7,
    slug: 'galletas-maria',
    source: 'usda'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'milk', presence: 'may_contain' }, { key: 'eggs', presence: 'may_contain' }],
    carbs: 65,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 17,
    fiber: 5,
    gramsPerUnit: 10,
    kcal: 450,
    name: 'Galletas de avena',
    protein: 8,
    slug: 'galletas-de-avena'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'milk', presence: 'may_contain' }],
    carbs: 62,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 21,
    fiber: 4,
    gramsPerUnit: 15,
    kcal: 480,
    name: 'Galletas digestive',
    protein: 7,
    slug: 'galletas-digestive'
  },
  {
    allergens: [
      { key: 'milk', presence: 'may_contain' },
      { key: 'eggs', presence: 'may_contain' },
      { key: 'soy', presence: 'may_contain' }
    ],
    carbs: 70,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 18,
    gramsPerUnit: 8,
    kcal: 460,
    name: 'Galletas sin gluten',
    protein: 5,
    slug: 'galletas-sin-gluten'
  },
  {
    allergens: [
      { key: 'gluten' },
      { key: 'tree_nuts', presence: 'may_contain' },
      { key: 'milk', presence: 'may_contain' },
      { key: 'soy', presence: 'may_contain' }
    ],
    carbs: 65,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 12,
    fiber: 5,
    gramsPerUnit: 25,
    kcal: 400,
    name: 'Barritas de cereales',
    protein: 6,
    slug: 'barritas-de-cereales'
  },
  {
    allergens: [{ key: 'milk' }, { key: 'soy' }, { key: 'tree_nuts', presence: 'may_contain' }, { key: 'gluten', presence: 'may_contain' }],
    carbs: 30,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 12,
    fiber: 8,
    gramsPerUnit: 50,
    kcal: 380,
    name: 'Barritas de proteínas',
    protein: 30,
    slug: 'barritas-de-proteinas'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'sesame', presence: 'may_contain' }],
    carbs: 61.3,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 26.4,
    fiber: 2.3,
    gramsPerUnit: 7,
    kcal: 510,
    name: 'Crackers',
    protein: 6.6,
    slug: 'crackers',
    source: 'usda'
  },
  {
    carbs: 77.8,
    category: 'pantry',
    fat: 4.5,
    fiber: 14.5,
    kcal: 387,
    name: 'Palomitas de maíz (para hacer)',
    protein: 12.9,
    slug: 'palomitas-de-maiz',
    source: 'usda'
  },
  {
    carbs: 53.8,
    category: 'pantry',
    fat: 34,
    fiber: 3.1,
    kcal: 532,
    name: 'Patatas fritas de bolsa',
    protein: 6.4,
    slug: 'patatas-fritas-de-bolsa',
    source: 'usda'
  },
  { carbs: 67.8, category: 'pantry', fat: 20.7, fiber: 5.4, kcal: 472, name: 'Nachos', protein: 7.1, slug: 'nachos', source: 'usda' },
  // ── Second pass: grains, pasta and flours ─────────────────────────────
  {
    carbs: 80,
    category: 'pantry',
    fat: 0.7,
    fiber: 1.3,
    kcal: 365,
    name: 'Arroz basmati',
    protein: 7.1,
    slug: 'arroz-basmati-crudo',
    source: 'usda'
  },
  { carbs: 80, category: 'pantry', fat: 0.7, fiber: 1.3, kcal: 365, name: 'Arroz jazmín', protein: 7.1, slug: 'arroz-jazmin-crudo', source: 'usda' },
  {
    carbs: 80.9,
    category: 'pantry',
    fat: 1,
    fiber: 1.8,
    kcal: 374,
    name: 'Arroz vaporizado',
    protein: 7.5,
    slug: 'arroz-vaporizado',
    source: 'usda'
  },
  { allergens: [{ key: 'gluten' }], carbs: 72, category: 'pantry', fat: 2.5, fiber: 8, kcal: 350, name: 'Freekeh', protein: 13, slug: 'freekeh' },
  {
    allergens: [{ key: 'gluten', presence: 'may_contain' }],
    carbs: 66,
    category: 'pantry',
    fat: 7,
    fiber: 11,
    kcal: 389,
    name: 'Avena en grano',
    protein: 17,
    slug: 'avena-en-grano'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 62,
    category: 'pantry',
    fat: 2.5,
    fiber: 9,
    kcal: 340,
    name: 'Copos de espelta',
    protein: 14,
    slug: 'copos-de-espelta'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 65,
    category: 'pantry',
    fat: 1.7,
    fiber: 14,
    kcal: 335,
    name: 'Copos de centeno',
    protein: 10,
    slug: 'copos-de-centeno'
  },
  { carbs: 88.7, category: 'pantry', fat: 0, fiber: 0.9, kcal: 358, name: 'Tapioca', protein: 0.2, slug: 'tapioca', source: 'usda' },
  {
    allergens: [{ key: 'gluten' }, { key: 'eggs' }, { key: 'milk' }],
    carbs: 45,
    category: 'pantry',
    fat: 8,
    kcal: 300,
    name: 'Tortellini',
    protein: 12,
    slug: 'tortellini'
  },
  { carbs: 86, category: 'pantry', fat: 0, kcal: 350, name: 'Fideos de cristal', protein: 0.2, slug: 'fideos-de-cristal' },
  {
    carbs: 80,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 0.5,
    gramsPerUnit: 10,
    kcal: 330,
    name: 'Papel de arroz',
    protein: 3,
    slug: 'papel-de-arroz'
  },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 55,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 6,
    gramsPerUnit: 20,
    kcal: 300,
    name: 'Masa filo',
    protein: 7,
    slug: 'masa-filo'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'milk', presence: 'may_contain' }],
    carbs: 50,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 17,
    gramsPerUnit: 12,
    kcal: 380,
    name: 'Obleas de empanadillas',
    protein: 7,
    slug: 'obleas-de-empanadillas'
  },
  {
    carbs: 70.6,
    category: 'pantry',
    fat: 3.1,
    fiber: 10,
    kcal: 335,
    name: 'Harina de trigo sarraceno',
    protein: 12.6,
    slug: 'harina-de-trigo-sarraceno',
    source: 'usda'
  },
  {
    carbs: 85,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0.5,
    fiber: 80,
    gramsPerUnit: 4,
    kcal: 200,
    name: 'Psyllium',
    protein: 2,
    slug: 'psyllium'
  },
  { allergens: [{ key: 'gluten' }], carbs: 14, category: 'pantry', fat: 2, kcal: 370, name: 'Gluten de trigo', protein: 75, slug: 'gluten-de-trigo' },
  { carbs: 23, category: 'pantry', fat: 0.6, fiber: 1.5, kcal: 95, name: 'Jackfruit en conserva', protein: 1.7, slug: 'jackfruit' },
  // ── Second pass: tins and jars ────────────────────────────────────────
  {
    carbs: 3.5,
    category: 'pantry',
    fat: 0.2,
    fiber: 2,
    kcal: 20,
    name: 'Judías verdes en conserva',
    protein: 1.2,
    slug: 'judias-verdes-en-conserva'
  },
  { carbs: 7, category: 'pantry', fat: 0.5, fiber: 3.5, kcal: 45, name: 'Menestra en conserva', protein: 3, slug: 'menestra-en-conserva' },
  {
    carbs: 3.9,
    category: 'pantry',
    fat: 0.2,
    fiber: 1,
    kcal: 22,
    name: 'Tomate troceado en conserva',
    protein: 1,
    slug: 'tomate-troceado-en-conserva'
  },
  { carbs: 6, category: 'pantry', fat: 3.5, fiber: 2, kcal: 60, name: 'Pisto en conserva', protein: 1.5, slug: 'pisto-en-conserva' },
  { carbs: 1.5, category: 'pantry', defaultUnit: 'ml', fat: 7, kcal: 73, name: 'Leche de coco ligera', protein: 0.7, slug: 'leche-de-coco-ligera' },
  // ── Second pass: nuts, seeds, sweet ───────────────────────────────────
  { carbs: 70, category: 'pantry', fat: 6, fiber: 7, kcal: 380, name: 'Quinoa hinchada', protein: 13, slug: 'quinoa-hinchada' },
  { carbs: 88, category: 'pantry', fat: 0.5, fiber: 1.5, kcal: 380, name: 'Arroz hinchado', protein: 6, slug: 'arroz-hinchado' },
  { carbs: 65, category: 'pantry', fat: 16, fiber: 8, kcal: 450, name: 'Kikos (maíz tostado)', protein: 10, slug: 'kikos' },
  { carbs: 55, category: 'pantry', fat: 10, fiber: 15, kcal: 400, name: 'Garbanzos tostados', protein: 20, slug: 'garbanzos-tostados' },
  {
    carbs: 89,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.6,
    fiber: 40,
    gramsPerUnit: 8,
    kcal: 220,
    name: 'Harina de algarroba',
    protein: 4.6,
    slug: 'harina-de-algarroba'
  },
  {
    carbs: 30,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 50,
    fiber: 20,
    gramsPerUnit: 10,
    kcal: 600,
    name: 'Nibs de cacao',
    protein: 14,
    slug: 'nibs-de-cacao'
  },
  {
    carbs: 74.7,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.1,
    gramsPerUnit: 20,
    kcal: 290,
    name: 'Miel de caña',
    protein: 0,
    slug: 'miel-de-cana',
    source: 'usda'
  },
  {
    carbs: 68,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.2,
    gramsPerUnit: 20,
    kcal: 280,
    name: 'Sirope de dátiles',
    protein: 1,
    slug: 'sirope-de-datiles'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 25,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 50,
    gramsPerUnit: 16,
    kcal: 600,
    name: 'Crema de pistacho',
    protein: 20,
    slug: 'crema-de-pistacho'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 25,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 50,
    gramsPerUnit: 16,
    kcal: 590,
    name: 'Crema de anacardos',
    protein: 18,
    slug: 'crema-de-anacardos'
  },
  {
    carbs: 66.3,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0,
    fiber: 0.7,
    gramsPerUnit: 20,
    kcal: 246,
    name: 'Mermelada de naranja',
    protein: 0.3,
    slug: 'mermelada-de-naranja',
    source: 'usda'
  },
  {
    carbs: 68.9,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.1,
    fiber: 1.1,
    gramsPerUnit: 20,
    kcal: 278,
    name: 'Mermelada de frutos rojos',
    protein: 0.4,
    slug: 'mermelada-de-frutos-rojos',
    source: 'usda'
  },
  { carbs: 70, category: 'pantry', fat: 0.1, kcal: 280, name: 'Cabello de ángel', protein: 0.3, slug: 'cabello-de-angel' },
  {
    allergens: [
      { key: 'soy', presence: 'may_contain' },
      { key: 'milk', presence: 'may_contain' }
    ],
    carbs: 55,
    category: 'pantry',
    fat: 28,
    kcal: 500,
    name: 'Chocolate de cobertura',
    protein: 5,
    slug: 'chocolate-de-cobertura'
  },
  {
    allergens: [{ key: 'milk' }, { key: 'tree_nuts' }, { key: 'soy', presence: 'may_contain' }],
    carbs: 45,
    category: 'pantry',
    fat: 36,
    kcal: 550,
    name: 'Chocolate con almendras',
    protein: 9,
    slug: 'chocolate-con-almendras'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'soy' }, { key: 'milk', presence: 'may_contain' }],
    carbs: 70,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 20,
    gramsPerUnit: 11,
    kcal: 480,
    name: 'Galletas rellenas de chocolate',
    protein: 5,
    slug: 'galletas-rellenas-de-chocolate'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'milk' }, { key: 'eggs' }],
    carbs: 65,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 24,
    gramsPerUnit: 10,
    kcal: 500,
    name: 'Galletas de mantequilla',
    protein: 6,
    slug: 'galletas-de-mantequilla'
  },
  {
    allergens: [{ key: 'gluten' }, { key: 'eggs' }],
    carbs: 75,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 5,
    gramsPerUnit: 6,
    kcal: 390,
    name: 'Bizcochos de soletilla',
    protein: 10,
    slug: 'bizcochos-de-soletilla'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 60,
    category: 'pantry',
    fat: 5,
    fiber: 8,
    kcal: 300,
    name: 'Pan de higo',
    protein: 4,
    slug: 'pan-de-higo'
  },
  // ── Second pass: oils, vinegars, sauces ───────────────────────────────
  {
    allergens: [{ key: 'peanuts' }],
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 100,
    gramsPerUnit: 14,
    kcal: 884,
    name: 'Aceite de cacahuete',
    protein: 0,
    slug: 'aceite-de-cacahuete',
    source: 'usda'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 100,
    gramsPerUnit: 14,
    kcal: 884,
    name: 'Aceite de nuez',
    protein: 0,
    slug: 'aceite-de-nuez',
    source: 'usda'
  },
  {
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 100,
    gramsPerUnit: 5,
    kcal: 900,
    name: 'Aceite de guindilla',
    protein: 0,
    slug: 'aceite-de-guindilla'
  },
  {
    carbs: 0.3,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0,
    gramsPerUnit: 15,
    kcal: 18,
    name: 'Vinagre de vino blanco',
    protein: 0,
    slug: 'vinagre-de-vino-blanco'
  },
  {
    allergens: [{ key: 'sulphites', presence: 'may_contain' }],
    carbs: 48,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0,
    gramsPerUnit: 6,
    kcal: 200,
    name: 'Crema de vinagre balsámico',
    protein: 0.5,
    slug: 'crema-de-vinagre-balsamico'
  },
  {
    carbs: 8,
    category: 'pantry',
    fat: 2.5,
    fiber: 1.5,
    kcal: 60,
    name: 'Salsa de tomate para pizza',
    protein: 1.5,
    slug: 'salsa-de-tomate-para-pizza'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 6,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 40,
    gramsPerUnit: 16,
    kcal: 400,
    name: 'Pesto vegano',
    protein: 4,
    slug: 'pesto-vegano'
  },
  { carbs: 5, category: 'pantry', fat: 0.2, fiber: 1, kcal: 25, name: 'Salsa pico de gallo', protein: 1, slug: 'salsa-pico-de-gallo' },
  {
    carbs: 48,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.3,
    gramsPerUnit: 15,
    kcal: 200,
    name: 'Salsa de chile dulce',
    protein: 0.5,
    slug: 'salsa-de-chile-dulce'
  },
  {
    allergens: [{ key: 'soy' }, { key: 'gluten' }, { key: 'fish', presence: 'may_contain' }],
    carbs: 12,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0,
    gramsPerUnit: 15,
    kcal: 60,
    name: 'Salsa ponzu',
    protein: 3,
    slug: 'salsa-ponzu'
  },
  {
    allergens: [{ key: 'soy' }, { key: 'gluten' }],
    carbs: 45,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 1.5,
    gramsPerUnit: 15,
    kcal: 200,
    name: 'Gochujang',
    protein: 5,
    slug: 'gochujang'
  },
  {
    carbs: 37,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.1,
    gramsPerUnit: 15,
    kcal: 150,
    name: 'Salsa de arándanos',
    protein: 0.2,
    slug: 'salsa-de-arandanos'
  },
  {
    allergens: [{ key: 'tree_nuts' }],
    carbs: 10,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 22,
    gramsPerUnit: 15,
    kcal: 250,
    name: 'Salsa romesco',
    protein: 5,
    slug: 'salsa-romesco'
  },
  { carbs: 8, category: 'pantry', defaultUnit: 'tbsp', fat: 19, gramsPerUnit: 15, kcal: 200, name: 'Mojo picón', protein: 2, slug: 'mojo-picon' },
  { carbs: 8, category: 'pantry', defaultUnit: 'tbsp', fat: 19, gramsPerUnit: 15, kcal: 200, name: 'Mojo verde', protein: 2, slug: 'mojo-verde' },
  {
    allergens: [{ key: 'fish' }],
    carbs: 1,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 9,
    gramsPerUnit: 5,
    kcal: 180,
    name: 'Pasta de anchoas',
    protein: 25,
    slug: 'pasta-de-anchoas'
  },
  {
    carbs: 62,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 0.6,
    fiber: 5,
    gramsPerUnit: 15,
    kcal: 240,
    name: 'Pasta de tamarindo',
    protein: 2.8,
    slug: 'pasta-de-tamarindo'
  },
  {
    allergens: [
      { key: 'celery', presence: 'may_contain' },
      { key: 'gluten', presence: 'may_contain' }
    ],
    carbs: 25,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 11,
    gramsPerUnit: 10,
    kcal: 230,
    name: 'Pastilla de caldo de verduras',
    protein: 8,
    slug: 'pastilla-de-caldo-de-verduras'
  },
  {
    carbs: 0,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 0,
    gramsPerUnit: 6,
    kcal: 0,
    name: 'Sal gruesa',
    protein: 0,
    slug: 'sal-gruesa',
    source: 'usda'
  },
  // ── Second pass: spices ───────────────────────────────────────────────
  {
    carbs: 60,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 10,
    fiber: 20,
    gramsPerUnit: 2,
    kcal: 300,
    name: 'Pimienta rosa',
    protein: 10,
    slug: 'pimienta-rosa'
  },
  { carbs: 70, category: 'pantry', defaultUnit: 'tsp', fat: 8, fiber: 30, gramsPerUnit: 2, kcal: 300, name: 'Sumac', protein: 4, slug: 'sumac' },
  { carbs: 50, category: 'pantry', defaultUnit: 'tsp', fat: 15, fiber: 20, gramsPerUnit: 2, kcal: 330, name: "Za'atar", protein: 11, slug: 'zaatar' },
  {
    carbs: 58.4,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 6.4,
    fiber: 24.6,
    gramsPerUnit: 3,
    kcal: 323,
    name: 'Fenogreco',
    protein: 23,
    slug: 'fenogreco',
    source: 'usda'
  },
  {
    allergens: [{ key: 'mustard' }],
    carbs: 28.1,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 36.2,
    fiber: 12.2,
    gramsPerUnit: 3,
    kcal: 508,
    name: 'Semillas de mostaza',
    protein: 26.1,
    slug: 'semillas-de-mostaza',
    source: 'usda'
  },
  {
    carbs: 50,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 16,
    fiber: 15,
    gramsPerUnit: 1,
    kcal: 337,
    name: 'Anís estrellado',
    protein: 18,
    slug: 'anis-estrellado'
  },
  {
    carbs: 80.6,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 1.2,
    fiber: 53.1,
    gramsPerUnit: 3,
    kcal: 247,
    name: 'Canela en rama',
    protein: 4,
    slug: 'canela-en-rama',
    source: 'usda'
  },
  {
    carbs: 72.1,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 8.7,
    fiber: 21.6,
    gramsPerUnit: 2,
    kcal: 263,
    name: 'Pimienta de Jamaica',
    protein: 6.1,
    slug: 'pimienta-de-jamaica',
    source: 'usda'
  },
  {
    carbs: 56,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 13,
    fiber: 30,
    gramsPerUnit: 3,
    kcal: 280,
    name: 'Chile chipotle seco',
    protein: 12,
    slug: 'chile-chipotle-seco'
  },
  {
    allergens: [{ key: 'gluten', presence: 'may_contain' }],
    carbs: 60,
    category: 'pantry',
    defaultUnit: 'tbsp',
    fat: 5,
    fiber: 10,
    gramsPerUnit: 8,
    kcal: 300,
    name: 'Sazonador para tacos',
    protein: 8,
    slug: 'sazonador-para-tacos'
  },
  {
    carbs: 90,
    category: 'pantry',
    defaultUnit: 'pinch',
    fat: 0,
    gramsPerUnit: 0.5,
    kcal: 350,
    name: 'Colorante alimentario',
    protein: 0,
    slug: 'colorante-alimentario'
  },
  {
    carbs: 52,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 6,
    fiber: 29.8,
    gramsPerUnit: 1,
    kcal: 285,
    name: 'Hierbabuena seca',
    protein: 19.9,
    slug: 'hierbabuena-seca',
    source: 'usda'
  },
  {
    carbs: 60.6,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 7,
    fiber: 40.3,
    gramsPerUnit: 1,
    kcal: 271,
    name: 'Mejorana',
    protein: 12.7,
    slug: 'mejorana',
    source: 'usda'
  },
  {
    carbs: 60.7,
    category: 'pantry',
    defaultUnit: 'tsp',
    fat: 12.8,
    fiber: 40.3,
    gramsPerUnit: 1,
    kcal: 315,
    name: 'Salvia seca',
    protein: 10.6,
    slug: 'salvia-seca',
    source: 'usda'
  },
  // ── Second pass: snacks ───────────────────────────────────────────────
  { carbs: 55, category: 'pantry', fat: 28, fiber: 8, kcal: 480, name: 'Chips de verduras', protein: 4, slug: 'chips-de-verduras' },
  { carbs: 55, category: 'pantry', fat: 26, fiber: 10, kcal: 480, name: 'Palomitas hechas', protein: 7, slug: 'palomitas-hechas' },
  {
    allergens: [{ key: 'gluten' }],
    carbs: 80.4,
    category: 'pantry',
    fat: 2.9,
    fiber: 3.4,
    kcal: 384,
    name: 'Pretzels',
    protein: 10,
    slug: 'pretzels',
    source: 'usda'
  },
  {
    carbs: 18.1,
    category: 'pantry',
    defaultUnit: 'unit',
    fat: 1.9,
    fiber: 8.1,
    gramsPerUnit: 40,
    kcal: 105,
    name: 'Levadura fresca de panadería',
    protein: 8.4,
    slug: 'levadura-fresca-de-panaderia',
    source: 'usda'
  }
];

export const PANTRY_NAMES_EN_GB: Record<string, string> = {
  'aceite-de-aguacate': 'Avocado oil',
  'aceite-de-cacahuete': 'Peanut oil',
  'aceite-de-guindilla': 'Chilli oil',
  'aceite-de-lino': 'Flaxseed oil',
  'aceite-de-nuez': 'Walnut oil',
  'aceite-de-oliva-suave': 'Mild olive oil',
  'aceite-de-sesamo': 'Sesame oil',
  'aceitunas-rellenas-de-anchoa': 'Anchovy-stuffed olives',
  'agar-agar': 'Agar-agar',
  'ajo-en-polvo': 'Garlic powder',
  'albahaca-seca': 'Dried basil',
  'alcachofas-en-conserva': 'Tinned artichokes',
  'alga-kombu': 'Kombu seaweed',
  'alga-nori': 'Nori seaweed',
  'alga-wakame': 'Wakame seaweed',
  amaranto: 'Amaranth',
  'anis-en-grano': 'Aniseed',
  'anis-estrellado': 'Star anise',
  'arandanos-deshidratados': 'Dried cranberries',
  'arroz-basmati-crudo': 'Basmati rice',
  'arroz-bomba-crudo': 'Bomba rice',
  'arroz-hinchado': 'Puffed rice',
  'arroz-integral-crudo': 'Brown rice',
  'arroz-jazmin-crudo': 'Jasmine rice',
  'arroz-largo-crudo': 'Long-grain rice',
  'arroz-negro-crudo': 'Black rice',
  'arroz-para-sushi': 'Sushi rice',
  'arroz-salvaje-cocido': 'Cooked wild rice',
  'arroz-salvaje-crudo': 'Wild rice',
  'arroz-vaporizado': 'Parboiled rice',
  'avena-en-grano': 'Oat groats',
  azafran: 'Saffron',
  'azucar-glas': 'Icing sugar',
  'azucar-moreno': 'Brown sugar',
  'barritas-de-cereales': 'Cereal bars',
  'barritas-de-proteinas': 'Protein bars',
  bicarbonato: 'Bicarbonate of soda',
  'bizcochos-de-soletilla': 'Sponge fingers',
  'brotes-de-bambu': 'Bamboo shoots',
  'bulgur-crudo': 'Bulgur wheat',
  'cabello-de-angel': 'Angel hair pumpkin jam',
  'caldo-dashi': 'Dashi stock',
  'caldo-de-carne': 'Beef stock',
  'caldo-de-pescado': 'Fish stock',
  'canela-en-rama': 'Cinnamon sticks',
  'cardamomo-molido': 'Ground cardamom',
  'castanas-asadas': 'Roasted chestnuts',
  'cayena-molida': 'Ground cayenne',
  'cebada-cocida': 'Cooked barley',
  'cebada-perlada': 'Pearl barley',
  'cebolla-en-polvo': 'Onion powder',
  'cebolletas-en-vinagre': 'Pickled onions',
  'cereales-de-chocolate': 'Chocolate breakfast cereal',
  'cereales-integrales': 'Wholegrain breakfast cereal',
  'champinones-en-conserva': 'Tinned mushrooms',
  'chile-chipotle-seco': 'Dried chipotle chilli',
  chimichurri: 'Chimichurri',
  'chips-de-chocolate': 'Chocolate chips',
  'chips-de-verduras': 'Vegetable crisps',
  'chocolate-blanco': 'White chocolate',
  'chocolate-con-almendras': 'Chocolate with almonds',
  'chocolate-con-leche': 'Milk chocolate',
  'chocolate-de-cobertura': 'Cooking chocolate',
  'chocolate-negro-85': 'Dark chocolate 85%',
  chucrut: 'Sauerkraut',
  'chutney-de-mango': 'Mango chutney',
  'cilantro-molido': 'Ground coriander',
  'cinco-especias-chinas': 'Chinese five spice',
  'ciruelas-pasas': 'Prunes',
  'clavo-molido': 'Ground cloves',
  'colorante-alimentario': 'Paella food colouring',
  'concentrado-de-tomate': 'Tomato purée',
  'copos-de-centeno': 'Rye flakes',
  'copos-de-espelta': 'Spelt flakes',
  crackers: 'Crackers',
  'crema-de-almendras': 'Almond butter',
  'crema-de-anacardos': 'Cashew butter',
  'crema-de-avellanas-y-cacao': 'Chocolate hazelnut spread',
  'crema-de-coco': 'Coconut cream',
  'crema-de-pistacho': 'Pistachio butter',
  'crema-de-vinagre-balsamico': 'Balsamic glaze',
  'cuscus-crudo': 'Couscous',
  datiles: 'Dates',
  'dulce-de-membrillo': 'Quince paste',
  edulcorante: 'Sweetener (erythritol)',
  'eneldo-seco': 'Dried dill',
  'espaguetis-secos': 'Spaghetti',
  'esparragos-blancos-en-conserva': 'Tinned white asparagus',
  'espelta-cocida': 'Cooked spelt',
  'espelta-en-grano': 'Spelt grain',
  espirulina: 'Spirulina',
  'estragon-seco': 'Dried tarragon',
  'fecula-de-patata': 'Potato starch',
  fenogreco: 'Fenugreek',
  'fideos-de-arroz-secos': 'Dried rice noodles',
  'fideos-de-cristal': 'Glass noodles',
  'fideos-finos': 'Fine noodles (fideos)',
  'fideos-soba': 'Soba noodles',
  freekeh: 'Freekeh',
  'galletas-de-avena': 'Oat biscuits',
  'galletas-de-mantequilla': 'Butter biscuits',
  'galletas-digestive': 'Digestive biscuits',
  'galletas-maria': 'Maria biscuits',
  'galletas-rellenas-de-chocolate': 'Chocolate sandwich biscuits',
  'galletas-sin-gluten': 'Gluten-free biscuits',
  'garam-masala': 'Garam masala',
  'garbanzos-tostados': 'Roasted chickpeas',
  'gelatina-de-sabores': 'Flavoured jelly powder',
  'gluten-de-trigo': 'Vital wheat gluten',
  gochujang: 'Gochujang',
  granola: 'Granola',
  'guindilla-seca': 'Dried chilli',
  'guindillas-en-vinagre': 'Pickled chillies',
  'guisantes-en-conserva': 'Tinned peas',
  'habas-en-conserva': 'Tinned broad beans',
  'harina-de-algarroba': 'Carob flour',
  'harina-de-arroz': 'Rice flour',
  'harina-de-centeno': 'Rye flour',
  'harina-de-coco': 'Coconut flour',
  'harina-de-espelta': 'Spelt flour',
  'harina-de-fuerza': 'Strong bread flour',
  'harina-de-garbanzo': 'Chickpea flour',
  'harina-de-maiz': 'Cornmeal',
  'harina-de-trigo-sarraceno': 'Buckwheat flour',
  'harina-integral': 'Wholemeal flour',
  'harina-para-tempura': 'Tempura flour',
  harissa: 'Harissa',
  'hierbabuena-seca': 'Dried mint',
  'hierbas-provenzales': 'Herbes de Provence',
  'higos-secos': 'Dried figs',
  jackfruit: 'Tinned jackfruit',
  'judias-verdes-en-conserva': 'Tinned green beans',
  kikos: 'Toasted corn kernels (kikos)',
  kimchi: 'Kimchi',
  'leche-de-coco': 'Tinned coconut milk',
  'leche-de-coco-ligera': 'Light coconut milk',
  'levadura-fresca-de-panaderia': 'Fresh yeast',
  'levadura-seca-de-panaderia': 'Dried yeast',
  'macarrones-secos': 'Macaroni',
  'manteca-de-cerdo': 'Lard',
  margarina: 'Margarine',
  'masa-filo': 'Filo pastry',
  mejorana: 'Marjoram',
  'menestra-en-conserva': 'Tinned mixed vegetables',
  'mermelada-de-frutos-rojos': 'Berry jam',
  'mermelada-de-melocoton': 'Peach jam',
  'mermelada-de-naranja': 'Orange marmalade',
  'mermelada-light': 'Reduced-sugar jam',
  'miel-de-cana': 'Cane molasses',
  mijo: 'Millet',
  'mijo-cocido': 'Cooked millet',
  miso: 'Miso',
  'mix-de-frutos-secos': 'Mixed nuts',
  'mojo-picon': 'Mojo picón sauce',
  'mojo-verde': 'Mojo verde',
  'mostaza-antigua': 'Wholegrain mustard',
  'mostaza-de-miel': 'Honey mustard',
  nachos: 'Tortilla chips',
  'nata-vegetal-de-avena': 'Oat cream',
  'nata-vegetal-de-soja': 'Soya cream',
  'nibs-de-cacao': 'Cacao nibs',
  'noodles-de-trigo': 'Wheat noodles',
  'noodles-udon': 'Udon noodles',
  noquis: 'Gnocchi',
  'nueces-de-brasil': 'Brazil nuts',
  'nueces-de-macadamia': 'Macadamia nuts',
  'nueces-pecanas': 'Pecans',
  'obleas-de-empanadillas': 'Empanadilla pastry discs',
  orejones: 'Dried apricots',
  palmitos: 'Palm hearts',
  'palomitas-de-maiz': 'Popcorn kernels',
  'palomitas-hechas': 'Ready-made popcorn',
  'pan-de-higo': 'Fig loaf',
  'pan-rallado-sin-gluten': 'Gluten-free breadcrumbs',
  panela: 'Panela (unrefined cane sugar)',
  panko: 'Panko breadcrumbs',
  'papel-de-arroz': 'Rice paper',
  pasas: 'Raisins',
  'pasta-de-anchoas': 'Anchovy paste',
  'pasta-de-curry-rojo': 'Red curry paste',
  'pasta-de-curry-verde': 'Green curry paste',
  'pasta-de-garbanzos': 'Chickpea pasta',
  'pasta-de-lentejas': 'Lentil pasta',
  'pasta-de-tamarindo': 'Tamarind paste',
  'pasta-fresca-al-huevo': 'Fresh egg pasta',
  'pasta-integral-seca': 'Wholewheat pasta',
  'pasta-sin-gluten': 'Gluten-free pasta',
  'pastilla-de-caldo': 'Chicken stock cube',
  'pastilla-de-caldo-de-verduras': 'Vegetable stock cube',
  'patatas-fritas-de-bolsa': 'Crisps',
  'perejil-seco': 'Dried parsley',
  'pesto-rojo': 'Red pesto',
  'pesto-vegano': 'Vegan pesto',
  'pimenton-ahumado': 'Smoked paprika',
  'pimenton-picante': 'Hot paprika',
  'pimienta-blanca': 'White pepper',
  'pimienta-de-jamaica': 'Allspice',
  'pimienta-negra': 'Black pepper',
  'pimienta-rosa': 'Pink peppercorns',
  'pimiento-del-piquillo': 'Piquillo peppers',
  'pimientos-asados-en-conserva': 'Jarred roasted peppers',
  pinones: 'Pine nuts',
  'pisto-en-conserva': 'Tinned pisto',
  'placas-de-lasana': 'Lasagne sheets',
  polenta: 'Polenta',
  'polenta-cocida': 'Cooked polenta',
  pretzels: 'Pretzels',
  psyllium: 'Psyllium husk',
  'queso-vegano': 'Vegan cheese',
  'quinoa-cruda': 'Quinoa',
  'quinoa-hinchada': 'Puffed quinoa',
  'ras-el-hanout': 'Ras el hanout',
  'raviolis-frescos': 'Fresh ravioli',
  'remolacha-en-conserva': 'Tinned beetroot',
  'romero-seco': 'Dried rosemary',
  'sal-gruesa': 'Coarse salt',
  'salsa-agridulce': 'Sweet and sour sauce',
  'salsa-bolonesa-envasada': 'Jarred bolognese sauce',
  'salsa-brava': 'Brava sauce',
  'salsa-carbonara-envasada': 'Jarred carbonara sauce',
  'salsa-cesar': 'Caesar dressing',
  'salsa-de-arandanos': 'Cranberry sauce',
  'salsa-de-chile-dulce': 'Sweet chilli sauce',
  'salsa-de-ostras': 'Oyster sauce',
  'salsa-de-pescado': 'Fish sauce',
  'salsa-de-queso': 'Cheese sauce',
  'salsa-de-soja-baja-en-sal': 'Reduced-salt soy sauce',
  'salsa-de-tomate-para-pizza': 'Pizza sauce',
  'salsa-de-yogur': 'Yoghurt sauce',
  'salsa-hoisin': 'Hoisin sauce',
  'salsa-pico-de-gallo': 'Pico de gallo salsa',
  'salsa-ponzu': 'Ponzu sauce',
  'salsa-romesco': 'Romesco sauce',
  'salsa-satay': 'Satay sauce',
  'salsa-tartara': 'Tartare sauce',
  'salsa-teriyaki': 'Teriyaki sauce',
  'salsa-worcestershire': 'Worcestershire sauce',
  'salvado-de-avena': 'Oat bran',
  'salvado-de-trigo': 'Wheat bran',
  'salvia-seca': 'Dried sage',
  'sazonador-para-tacos': 'Taco seasoning',
  'semillas-de-amapola': 'Poppy seeds',
  'semillas-de-canamo': 'Hemp seeds',
  'semillas-de-hinojo': 'Fennel seeds',
  'semillas-de-mostaza': 'Mustard seeds',
  'semola-de-trigo': 'Semolina',
  'sirope-de-arce': 'Maple syrup',
  'sirope-de-datiles': 'Date syrup',
  'sofrito-envasado': 'Jarred sofrito',
  sumac: 'Sumac',
  tamari: 'Tamari',
  tapioca: 'Tapioca',
  'tomate-entero-pelado': 'Tinned peeled tomatoes',
  'tomate-seco-en-aceite': 'Sun-dried tomatoes in oil',
  'tomate-troceado-en-conserva': 'Tinned chopped tomatoes',
  'tomillo-seco': 'Dried thyme',
  tortellini: 'Tortellini',
  'trigo-sarraceno': 'Buckwheat',
  'trigo-sarraceno-cocido': 'Cooked buckwheat',
  'vinagre-balsamico': 'Balsamic vinegar',
  'vinagre-blanco': 'White vinegar',
  'vinagre-de-arroz': 'Rice vinegar',
  'vinagre-de-vino-blanco': 'White wine vinegar',
  'vinagreta-envasada': 'Bottled vinaigrette',
  'vino-blanco': 'White wine (for cooking)',
  'vino-tinto': 'Red wine (for cooking)',
  wasabi: 'Wasabi paste',
  zaatar: "Za'atar"
};
