import type { IngredientSeed } from './types';

/**
 * Fresh vegetables, herbs and fruit beyond the starter set. Macros per 100 g of
 * edible portion, from BEDCA/USDA composition tables. Herbs and leaves sit
 * below the kcal-ratio floor in `seed.test.ts`; their numbers are still real.
 */
export const PRODUCE: readonly IngredientSeed[] = [
  // ── Leaves and brassicas ──────────────────────────────────────────────
  { carbs: 3.7, category: 'produce', fat: 0.2, fiber: 1.6, kcal: 19, name: 'Acelga', protein: 1.8, slug: 'acelga', source: 'usda' },
  { carbs: 5.8, category: 'produce', fat: 0.1, fiber: 2.5, kcal: 25, name: 'Col blanca', protein: 1.3, slug: 'col-blanca', source: 'usda' },
  { carbs: 7.4, category: 'produce', fat: 0.2, fiber: 2.1, kcal: 31, name: 'Lombarda', protein: 1.4, slug: 'lombarda', source: 'usda' },
  {
    carbs: 8.9,
    category: 'produce',
    fat: 0.3,
    fiber: 3.8,
    kcal: 43,
    name: 'Coles de Bruselas',
    protein: 3.4,
    slug: 'coles-de-bruselas',
    source: 'usda'
  },
  { carbs: 3.2, category: 'produce', fat: 0.2, fiber: 1.2, kcal: 16, name: 'Col china', protein: 1.2, slug: 'col-china', source: 'usda' },
  { carbs: 2.2, category: 'produce', fat: 0.2, fiber: 1, kcal: 13, name: 'Pak choi', protein: 1.5, slug: 'pak-choi', source: 'usda' },
  { carbs: 5, category: 'produce', fat: 0.3, fiber: 2, kcal: 25, name: 'Romanesco', protein: 1.9, slug: 'romanesco', source: 'usda' },
  { carbs: 6.6, category: 'produce', fat: 0.4, fiber: 2.6, kcal: 34, name: 'Bimi', protein: 2.8, slug: 'bimi', source: 'usda' },
  { carbs: 7.1, category: 'produce', fat: 0.3, fiber: 3.2, kcal: 32, name: 'Grelos', protein: 1.5, slug: 'grelos', source: 'usda' },
  { carbs: 6.2, category: 'produce', fat: 0.1, fiber: 3.6, kcal: 27, name: 'Colinabo', protein: 1.7, slug: 'colinabo', source: 'usda' },
  { carbs: 3.4, category: 'produce', fat: 0.2, fiber: 3.1, kcal: 17, name: 'Endibia', protein: 1.2, slug: 'endibia', source: 'usda' },
  { carbs: 3.6, category: 'produce', fat: 0.4, fiber: 0, kcal: 21, name: 'Canónigos', protein: 2, slug: 'canonigos', source: 'usda' },
  { carbs: 1.3, category: 'produce', fat: 0.1, fiber: 0.5, kcal: 11, name: 'Berros', protein: 2.3, slug: 'berros', source: 'usda' },
  { carbs: 3.3, category: 'produce', fat: 0.3, fiber: 2.1, kcal: 17, name: 'Lechuga romana', protein: 1.2, slug: 'lechuga-romana', source: 'usda' },
  { carbs: 3, category: 'produce', fat: 0.1, fiber: 1.2, kcal: 14, name: 'Lechuga iceberg', protein: 0.9, slug: 'lechuga-iceberg', source: 'usda' },
  { carbs: 3.5, category: 'produce', fat: 0.3, fiber: 1.8, kcal: 20, name: 'Mezcla de brotes tiernos', protein: 2, slug: 'mezcla-de-brotes' },
  { carbs: 3.1, category: 'produce', fat: 0.7, fiber: 0, kcal: 21, name: 'Borraja', protein: 1.8, slug: 'borraja', source: 'usda' },
  { carbs: 4.1, category: 'produce', fat: 0.1, fiber: 1.6, kcal: 17, name: 'Cardo', protein: 0.7, slug: 'cardo', source: 'usda' },
  // ── Other vegetables ──────────────────────────────────────────────────
  { carbs: 7.3, category: 'produce', fat: 0.2, fiber: 3.1, kcal: 31, name: 'Hinojo', protein: 1.2, slug: 'hinojo', source: 'usda' },
  {
    carbs: 3.9,
    category: 'produce',
    fat: 0.1,
    fiber: 2.1,
    kcal: 20,
    name: 'Espárrago blanco',
    protein: 2.2,
    slug: 'esparrago-blanco',
    source: 'usda'
  },
  { carbs: 11.7, category: 'produce', fat: 0.6, fiber: 4.2, kcal: 72, name: 'Habas frescas', protein: 5.6, slug: 'habas-frescas', source: 'usda' },
  {
    carbs: 14.4,
    category: 'produce',
    fat: 0.4,
    fiber: 5.7,
    kcal: 81,
    name: 'Guisantes frescos',
    protein: 5.4,
    slug: 'guisantes-frescos',
    source: 'usda'
  },
  { carbs: 7.5, category: 'produce', fat: 0.2, fiber: 2.6, kcal: 42, name: 'Tirabeques', protein: 2.8, slug: 'tirabeques', source: 'usda' },
  {
    allergens: [{ key: 'soy', presence: 'may_contain' }],
    carbs: 5.9,
    category: 'produce',
    fat: 0.2,
    fiber: 1.8,
    kcal: 30,
    name: 'Brotes de soja',
    protein: 3,
    slug: 'brotes-de-soja',
    source: 'usda'
  },
  { carbs: 7.5, category: 'produce', fat: 0.2, fiber: 3.2, kcal: 33, name: 'Okra', protein: 1.9, slug: 'okra', source: 'usda' },
  { carbs: 6.8, category: 'produce', fat: 0.5, fiber: 2.5, kcal: 34, name: 'Seta shiitake', protein: 2.2, slug: 'seta-shiitake', source: 'usda' },
  { carbs: 6.1, category: 'produce', fat: 0.4, fiber: 2.3, kcal: 33, name: 'Seta de ostra', protein: 3.3, slug: 'seta-ostra', source: 'usda' },
  { carbs: 3.3, category: 'produce', fat: 0.4, fiber: 2.4, kcal: 26, name: 'Boletus', protein: 3.1, slug: 'boletus' },
  { carbs: 3.3, category: 'produce', fat: 0.3, fiber: 1, kcal: 22, name: 'Setas variadas', protein: 3.1, slug: 'setas-variadas', source: 'usda' },
  { carbs: 3.9, category: 'produce', fat: 0.3, fiber: 1.3, kcal: 22, name: 'Champiñón portobello', protein: 2.1, slug: 'portobello', source: 'usda' },
  { carbs: 3.9, category: 'produce', fat: 0.2, fiber: 1.2, kcal: 18, name: 'Tomate cherry', protein: 0.9, slug: 'tomate-cherry', source: 'usda' },
  { carbs: 3.9, category: 'produce', fat: 0.2, fiber: 1.2, kcal: 18, name: 'Tomate pera', protein: 0.9, slug: 'tomate-pera', source: 'usda' },
  {
    carbs: 6.3,
    category: 'produce',
    fat: 0.2,
    fiber: 0.9,
    kcal: 27,
    name: 'Pimiento amarillo',
    protein: 1,
    slug: 'pimiento-amarillo',
    source: 'usda'
  },
  { carbs: 5.5, category: 'produce', fat: 0.3, fiber: 2, kcal: 27, name: 'Pimientos de Padrón', protein: 1.3, slug: 'pimiento-de-padron' },
  {
    carbs: 8.8,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.4,
    fiber: 1.5,
    gramsPerUnit: 5,
    kcal: 40,
    name: 'Guindilla fresca',
    protein: 1.9,
    slug: 'guindilla-fresca',
    source: 'usda'
  },
  {
    carbs: 6.5,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.4,
    fiber: 2.8,
    gramsPerUnit: 15,
    kcal: 29,
    name: 'Jalapeño',
    protein: 0.9,
    slug: 'jalapeno',
    source: 'usda'
  },
  { carbs: 9.3, category: 'produce', fat: 0.1, fiber: 1.7, kcal: 40, name: 'Cebolla morada', protein: 1.1, slug: 'cebolla-morada', source: 'usda' },
  { carbs: 7.5, category: 'produce', fat: 0.1, fiber: 0.9, kcal: 32, name: 'Cebolla dulce', protein: 0.8, slug: 'cebolla-dulce', source: 'usda' },
  { carbs: 9, category: 'produce', fat: 0.3, fiber: 1.7, kcal: 45, name: 'Ajo tierno', protein: 2, slug: 'ajo-tierno' },
  { carbs: 17.8, category: 'produce', fat: 0.8, fiber: 2, kcal: 80, name: 'Jengibre fresco', protein: 1.8, slug: 'jengibre-fresco', source: 'usda' },
  { carbs: 10, category: 'produce', fat: 0.2, fiber: 2, kcal: 44, name: 'Remolacha cocida', protein: 1.7, slug: 'remolacha-cocida', source: 'usda' },
  {
    allergens: [{ key: 'celery' }],
    carbs: 9.2,
    category: 'produce',
    fat: 0.3,
    fiber: 1.8,
    kcal: 42,
    name: 'Apionabo',
    protein: 1.5,
    slug: 'apionabo',
    source: 'usda'
  },
  { carbs: 18, category: 'produce', fat: 0.3, fiber: 4.9, kcal: 75, name: 'Chirivía', protein: 1.2, slug: 'chirivia', source: 'usda' },
  { carbs: 38.1, category: 'produce', fat: 0.3, fiber: 1.8, kcal: 160, name: 'Yuca', protein: 1.4, slug: 'yuca', source: 'usda' },
  {
    carbs: 18.7,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 1.4,
    fiber: 2,
    gramsPerUnit: 150,
    kcal: 86,
    name: 'Mazorca de maíz',
    protein: 3.3,
    slug: 'mazorca-de-maiz',
    source: 'usda'
  },
  { carbs: 36.7, category: 'produce', fat: 0.1, fiber: 2.2, kcal: 152, name: 'Plátano macho', protein: 1.2, slug: 'platano-macho', source: 'usda' },
  // ── Fresh herbs ───────────────────────────────────────────────────────
  { carbs: 8.4, category: 'produce', fat: 0.7, fiber: 6.8, kcal: 44, name: 'Hierbabuena fresca', protein: 3.3, slug: 'hierbabuena', source: 'usda' },
  { carbs: 2.6, category: 'produce', fat: 0.6, fiber: 1.6, kcal: 23, name: 'Albahaca fresca', protein: 3.1, slug: 'albahaca-fresca', source: 'usda' },
  { carbs: 7, category: 'produce', fat: 1.1, fiber: 2.1, kcal: 43, name: 'Eneldo fresco', protein: 3.5, slug: 'eneldo-fresco', source: 'usda' },
  { carbs: 4.3, category: 'produce', fat: 0.7, fiber: 2.5, kcal: 30, name: 'Cebollino', protein: 3.3, slug: 'cebollino', source: 'usda' },
  { carbs: 20.7, category: 'produce', fat: 5.9, fiber: 14.1, kcal: 131, name: 'Romero fresco', protein: 3.3, slug: 'romero-fresco', source: 'usda' },
  { carbs: 24.4, category: 'produce', fat: 1.7, fiber: 14, kcal: 101, name: 'Tomillo fresco', protein: 5.6, slug: 'tomillo-fresco', source: 'usda' },
  // ── Fruit ─────────────────────────────────────────────────────────────
  {
    carbs: 10.5,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.2,
    fiber: 2.8,
    gramsPerUnit: 60,
    kcal: 30,
    name: 'Lima',
    protein: 0.7,
    slug: 'lima',
    source: 'usda'
  },
  {
    carbs: 10.7,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.1,
    fiber: 1.6,
    gramsPerUnit: 250,
    kcal: 42,
    name: 'Pomelo',
    protein: 0.8,
    slug: 'pomelo',
    source: 'usda'
  },
  {
    carbs: 13.3,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.3,
    fiber: 1.8,
    gramsPerUnit: 80,
    kcal: 53,
    name: 'Mandarina',
    protein: 0.8,
    slug: 'mandarina',
    source: 'usda'
  },
  {
    carbs: 18.7,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 1.2,
    fiber: 4,
    gramsPerUnit: 250,
    kcal: 83,
    name: 'Granada',
    protein: 1.7,
    slug: 'granada',
    source: 'usda'
  },
  {
    carbs: 19.2,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.3,
    fiber: 2.9,
    gramsPerUnit: 50,
    kcal: 74,
    name: 'Higo',
    protein: 0.8,
    slug: 'higo',
    source: 'usda'
  },
  { carbs: 17.7, category: 'produce', fat: 0.7, fiber: 3, kcal: 75, name: 'Chirimoya', protein: 1.6, slug: 'chirimoya', source: 'usda' },
  {
    carbs: 18.6,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.2,
    fiber: 3.6,
    gramsPerUnit: 170,
    kcal: 70,
    name: 'Caqui',
    protein: 0.6,
    slug: 'caqui',
    source: 'usda'
  },
  {
    carbs: 11.4,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.3,
    fiber: 1.4,
    gramsPerUnit: 60,
    kcal: 46,
    name: 'Ciruela',
    protein: 0.7,
    slug: 'ciruela',
    source: 'usda'
  },
  { carbs: 16, category: 'produce', fat: 0.2, fiber: 2.1, kcal: 63, name: 'Cereza', protein: 1.1, slug: 'cereza', source: 'usda' },
  {
    carbs: 11.1,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.4,
    fiber: 2,
    gramsPerUnit: 35,
    kcal: 48,
    name: 'Albaricoque',
    protein: 1.4,
    slug: 'albaricoque',
    source: 'usda'
  },
  {
    carbs: 10.6,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.3,
    fiber: 1.7,
    gramsPerUnit: 140,
    kcal: 44,
    name: 'Nectarina',
    protein: 1.1,
    slug: 'nectarina',
    source: 'usda'
  },
  {
    carbs: 9.5,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.2,
    fiber: 1.5,
    gramsPerUnit: 100,
    kcal: 39,
    name: 'Paraguayo',
    protein: 0.9,
    slug: 'paraguayo',
    source: 'usda'
  },
  {
    carbs: 15,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.4,
    fiber: 1.6,
    gramsPerUnit: 200,
    kcal: 60,
    name: 'Mango',
    protein: 0.8,
    slug: 'mango',
    source: 'usda'
  },
  { carbs: 13.1, category: 'produce', fat: 0.1, fiber: 1.4, kcal: 50, name: 'Piña', protein: 0.5, slug: 'pina', source: 'usda' },
  { carbs: 10.8, category: 'produce', fat: 0.3, fiber: 1.7, kcal: 43, name: 'Papaya', protein: 0.5, slug: 'papaya', source: 'usda' },
  {
    carbs: 23.4,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.7,
    fiber: 10.4,
    gramsPerUnit: 18,
    kcal: 97,
    name: 'Maracuyá',
    protein: 2.2,
    slug: 'maracuya',
    source: 'usda'
  },
  { carbs: 15.2, category: 'produce', fat: 33.5, fiber: 9, kcal: 354, name: 'Coco fresco', protein: 3.3, slug: 'coco-fresco', source: 'usda' },
  { carbs: 14.5, category: 'produce', fat: 0.3, fiber: 2.4, kcal: 57, name: 'Arándanos', protein: 0.7, slug: 'arandano', source: 'usda' },
  { carbs: 11.9, category: 'produce', fat: 0.7, fiber: 6.5, kcal: 52, name: 'Frambuesas', protein: 1.2, slug: 'frambuesa', source: 'usda' },
  { carbs: 9.6, category: 'produce', fat: 0.5, fiber: 5.3, kcal: 43, name: 'Moras', protein: 1.4, slug: 'mora', source: 'usda' },
  { carbs: 13.8, category: 'produce', fat: 0.2, fiber: 4.3, kcal: 56, name: 'Grosellas', protein: 1.4, slug: 'grosella', source: 'usda' },
  { carbs: 45.5, category: 'produce', fat: 2.3, fiber: 8.1, kcal: 213, name: 'Castañas', protein: 2.4, slug: 'castana', source: 'usda' },
  { carbs: 15.3, category: 'produce', fat: 0.1, fiber: 1.9, kcal: 57, name: 'Membrillo', protein: 0.4, slug: 'membrillo', source: 'usda' },
  { carbs: 12.1, category: 'produce', fat: 0.2, fiber: 1.7, kcal: 47, name: 'Níspero', protein: 0.4, slug: 'nispero', source: 'usda' },
  { carbs: 8.2, category: 'produce', fat: 0.2, fiber: 0.9, kcal: 34, name: 'Melón cantalupo', protein: 0.8, slug: 'melon-cantalupo', source: 'usda' },
  // ── Second pass ───────────────────────────────────────────────────────
  {
    carbs: 2.3,
    category: 'produce',
    fat: 0.2,
    fiber: 0.9,
    kcal: 13,
    name: 'Lechuga hoja de roble',
    protein: 1.3,
    slug: 'lechuga-hoja-de-roble',
    source: 'usda'
  },
  {
    carbs: 2.1,
    category: 'produce',
    fat: 0.7,
    fiber: 1.9,
    kcal: 23,
    name: 'Brotes de alfalfa',
    protein: 4,
    slug: 'brotes-de-alfalfa',
    source: 'usda'
  },
  {
    carbs: 11.7,
    category: 'produce',
    fat: 0.1,
    fiber: 2,
    kcal: 45,
    name: 'Calabaza cacahuete',
    protein: 1,
    slug: 'calabaza-cacahuete',
    source: 'usda'
  },
  {
    carbs: 4.6,
    category: 'produce',
    fat: 0.2,
    fiber: 1.7,
    kcal: 20,
    name: 'Pimiento italiano',
    protein: 0.9,
    slug: 'pimiento-italiano',
    source: 'usda'
  },
  { carbs: 17.5, category: 'produce', fat: 0.1, fiber: 2.1, kcal: 77, name: 'Patata nueva', protein: 2, slug: 'patata-nueva', source: 'usda' },
  { carbs: 4.1, category: 'produce', fat: 0.1, fiber: 1.6, kcal: 18, name: 'Rábano daikon', protein: 0.6, slug: 'daikon', source: 'usda' },
  {
    carbs: 55,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 12,
    fiber: 30,
    gramsPerUnit: 4,
    kcal: 280,
    name: 'Pimiento choricero seco',
    protein: 12,
    slug: 'pimiento-choricero'
  },
  { carbs: 55, category: 'produce', defaultUnit: 'unit', fat: 12, fiber: 30, gramsPerUnit: 3, kcal: 280, name: 'Ñora', protein: 12, slug: 'nora' },
  {
    carbs: 9.6,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.5,
    fiber: 3.6,
    gramsPerUnit: 100,
    kcal: 41,
    name: 'Higo chumbo',
    protein: 0.7,
    slug: 'higo-chumbo',
    source: 'usda'
  },
  { carbs: 16.5, category: 'produce', fat: 0.4, fiber: 1.3, kcal: 66, name: 'Lichis', protein: 0.8, slug: 'lichi', source: 'usda' },
  {
    carbs: 13,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.4,
    fiber: 3,
    gramsPerUnit: 300,
    kcal: 60,
    name: 'Pitaya',
    protein: 1.2,
    slug: 'pitaya'
  },
  {
    carbs: 25.3,
    category: 'produce',
    defaultUnit: 'unit',
    fat: 0.5,
    fiber: 0,
    gramsPerUnit: 20,
    kcal: 99,
    name: 'Hierba limón',
    protein: 1.8,
    slug: 'hierba-limon',
    source: 'usda'
  },
  { carbs: 6.1, category: 'produce', fat: 0.4, fiber: 2.3, kcal: 33, name: 'Seta de cardo', protein: 3.3, slug: 'seta-de-cardo', source: 'usda' },
  { carbs: 3.3, category: 'produce', fat: 0.4, fiber: 2, kcal: 22, name: 'Níscalos', protein: 1.8, slug: 'niscalos' }
];

export const PRODUCE_NAMES_EN_GB: Record<string, string> = {
  acelga: 'Chard',
  'ajo-tierno': 'Green garlic',
  'albahaca-fresca': 'Fresh basil',
  albaricoque: 'Apricot',
  apionabo: 'Celeriac',
  arandano: 'Blueberries',
  berros: 'Watercress',
  bimi: 'Tenderstem broccoli',
  boletus: 'Porcini mushroom',
  borraja: 'Borage',
  'brotes-de-alfalfa': 'Alfalfa sprouts',
  'brotes-de-soja': 'Bean sprouts',
  'calabaza-cacahuete': 'Butternut squash',
  canonigos: "Lamb's lettuce",
  caqui: 'Persimmon',
  cardo: 'Cardoon',
  castana: 'Chestnuts',
  'cebolla-dulce': 'Sweet onion',
  'cebolla-morada': 'Red onion',
  cebollino: 'Chives',
  cereza: 'Cherries',
  chirimoya: 'Custard apple',
  chirivia: 'Parsnip',
  ciruela: 'Plum',
  'coco-fresco': 'Fresh coconut',
  'col-blanca': 'White cabbage',
  'col-china': 'Chinese cabbage',
  'coles-de-bruselas': 'Brussels sprouts',
  colinabo: 'Kohlrabi',
  daikon: 'Daikon radish',
  endibia: 'Endive',
  'eneldo-fresco': 'Fresh dill',
  'esparrago-blanco': 'White asparagus',
  frambuesa: 'Raspberries',
  granada: 'Pomegranate',
  grelos: 'Turnip greens',
  grosella: 'Redcurrants',
  'guindilla-fresca': 'Fresh chilli',
  'guisantes-frescos': 'Fresh peas',
  'habas-frescas': 'Fresh broad beans',
  'hierba-limon': 'Lemongrass',
  hierbabuena: 'Fresh mint',
  higo: 'Fig',
  'higo-chumbo': 'Prickly pear',
  hinojo: 'Fennel',
  jalapeno: 'Jalapeño pepper',
  'jengibre-fresco': 'Fresh ginger',
  'lechuga-hoja-de-roble': 'Oak leaf lettuce',
  'lechuga-iceberg': 'Iceberg lettuce',
  'lechuga-romana': 'Romaine lettuce',
  lichi: 'Lychees',
  lima: 'Lime',
  lombarda: 'Red cabbage',
  mandarina: 'Mandarin',
  mango: 'Mango',
  maracuya: 'Passion fruit',
  'mazorca-de-maiz': 'Corn on the cob',
  'melon-cantalupo': 'Cantaloupe melon',
  membrillo: 'Quince',
  'mezcla-de-brotes': 'Mixed baby leaves',
  mora: 'Blackberries',
  nectarina: 'Nectarine',
  niscalos: 'Saffron milk cap mushrooms',
  nispero: 'Loquat',
  nora: 'Ñora dried pepper',
  okra: 'Okra',
  'pak-choi': 'Pak choi',
  papaya: 'Papaya',
  paraguayo: 'Flat peach',
  'patata-nueva': 'New potatoes',
  'pimiento-amarillo': 'Yellow pepper',
  'pimiento-choricero': 'Dried choricero pepper',
  'pimiento-de-padron': 'Padrón peppers',
  'pimiento-italiano': 'Italian green pepper',
  pina: 'Pineapple',
  pitaya: 'Dragon fruit',
  'platano-macho': 'Plantain',
  pomelo: 'Grapefruit',
  portobello: 'Portobello mushroom',
  'remolacha-cocida': 'Cooked beetroot',
  romanesco: 'Romanesco',
  'romero-fresco': 'Fresh rosemary',
  'seta-de-cardo': 'King oyster mushroom',
  'seta-ostra': 'Oyster mushroom',
  'seta-shiitake': 'Shiitake mushroom',
  'setas-variadas': 'Mixed mushrooms',
  tirabeques: 'Mangetout',
  'tomate-cherry': 'Cherry tomatoes',
  'tomate-pera': 'Plum tomato',
  'tomillo-fresco': 'Fresh thyme',
  yuca: 'Cassava'
};
