import type { IngredientSeed } from './types';

/**
 * Meat, poultry, fish, seafood, eggs and the plant proteins, beyond the
 * starter set. Cuts carry `meat` or `pork` — the allergen links say nothing
 * about them — and everything from the sea carries `fish`, `crustaceans` or
 * `molluscs`, which is how it becomes fish or shellfish to the substitution
 * rule. A mixed mince is pork before it is beef: the rule needs the stricter
 * class. Fresh prawns and langoustines carry `sulphites` as `may_contain`; on
 * a Spanish fish counter the preservative is the norm and the label decides.
 */
export const PROTEIN: readonly IngredientSeed[] = [
  // ── Beef and veal ─────────────────────────────────────────────────────
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 14, kcal: 200, name: 'Entrecot de ternera', protein: 19, slug: 'entrecot-de-ternera' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 18, kcal: 230, name: 'Chuletón de ternera', protein: 18, slug: 'chuleton-de-ternera' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 15, kcal: 210, name: 'Falda de ternera', protein: 18, slug: 'falda-de-ternera' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 5, kcal: 130, name: 'Morcillo de ternera', protein: 20, slug: 'morcillo-de-ternera' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 4.5, kcal: 125, name: 'Redondo de ternera', protein: 21, slug: 'redondo-de-ternera' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 4, kcal: 120, name: 'Filete de ternera', protein: 21, slug: 'filete-de-ternera' },
  { allergens: [{ key: 'gluten', presence: 'may_contain' }], carbs: 1, category: 'protein', classes: ['meat'], defaultUnit: 'unit', fat: 17, gramsPerUnit: 120, kcal: 220, name: 'Hamburguesa de ternera', protein: 17, slug: 'hamburguesa-de-ternera' },
  { carbs: 3.9, category: 'protein', classes: ['meat'], fat: 3.6, kcal: 135, name: 'Hígado de ternera', protein: 20, slug: 'higado-de-ternera' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 19, kcal: 250, name: 'Rabo de toro', protein: 19, slug: 'rabo-de-toro' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 8.5, kcal: 150, name: 'Carrillera de ternera', protein: 18, slug: 'carrillera-de-ternera' },
  { carbs: 0.5, category: 'protein', classes: ['pork'], fat: 18, kcal: 230, name: 'Carne picada mixta', protein: 17, slug: 'carne-picada-mixta' },
  // ── Lamb ──────────────────────────────────────────────────────────────
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 18, kcal: 230, name: 'Pierna de cordero', protein: 17, slug: 'pierna-de-cordero' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 24, kcal: 280, name: 'Chuletas de cordero', protein: 16, slug: 'chuletas-de-cordero' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 23, kcal: 280, name: 'Cordero picado', protein: 17, slug: 'cordero-picado' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 21, kcal: 250, name: 'Paletilla de cordero', protein: 16, slug: 'paletilla-de-cordero' },
  // ── Pork ──────────────────────────────────────────────────────────────
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 21, kcal: 260, name: 'Secreto de cerdo', protein: 18, slug: 'secreto-de-cerdo' },
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 18, kcal: 230, name: 'Presa ibérica', protein: 18, slug: 'presa-iberica' },
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 2.5, kcal: 110, name: 'Solomillo de cerdo', protein: 22, slug: 'solomillo-de-cerdo' },
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 14, kcal: 200, name: 'Chuleta de cerdo', protein: 19, slug: 'chuleta-de-cerdo' },
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 19, kcal: 240, name: 'Carne picada de cerdo', protein: 17, slug: 'carne-picada-de-cerdo' },
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 12, kcal: 180, name: 'Carrillera de cerdo', protein: 17, slug: 'carrillera-de-cerdo' },
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 17, kcal: 220, name: 'Codillo de cerdo', protein: 17, slug: 'codillo-de-cerdo' },
  { carbs: 0.5, category: 'protein', classes: ['pork'], fat: 10, kcal: 170, name: 'Lacón', protein: 20, slug: 'lacon' },
  { carbs: 0.5, category: 'protein', classes: ['pork'], defaultUnit: 'slice', fat: 33, gramsPerUnit: 15, kcal: 350, name: 'Bacon', protein: 13, slug: 'bacon' },
  { allergens: [{ key: 'gluten', presence: 'may_contain' }, { key: 'sulphites', presence: 'may_contain' }], carbs: 2, category: 'protein', classes: ['pork'], defaultUnit: 'unit', fat: 27, gramsPerUnit: 60, kcal: 300, name: 'Salchichas frescas', protein: 13, slug: 'salchichas-frescas' },
  { carbs: 1, category: 'protein', classes: ['pork'], fat: 36, kcal: 420, name: 'Salchichón', protein: 24, slug: 'salchichon' },
  { carbs: 2, category: 'protein', classes: ['pork'], fat: 38, kcal: 430, name: 'Fuet', protein: 22, slug: 'fuet' },
  { carbs: 0.5, category: 'protein', classes: ['pork'], fat: 8, kcal: 210, name: 'Lomo embuchado', protein: 35, slug: 'lomo-embuchado' },
  { carbs: 1, category: 'protein', classes: ['pork'], defaultUnit: 'tbsp', fat: 57, gramsPerUnit: 15, kcal: 550, name: 'Sobrasada', protein: 10, slug: 'sobrasada' },
  { carbs: 15, category: 'protein', classes: ['pork'], fat: 24, kcal: 320, name: 'Morcilla de arroz', protein: 12, slug: 'morcilla' },
  { carbs: 1, category: 'protein', classes: ['pork'], fat: 25, kcal: 280, name: 'Butifarra', protein: 14, slug: 'butifarra' },
  { carbs: 3, category: 'protein', classes: ['pork'], defaultUnit: 'slice', fat: 27, gramsPerUnit: 20, kcal: 300, name: 'Mortadela', protein: 13, slug: 'mortadela' },
  { carbs: 0.5, category: 'protein', classes: ['pork'], fat: 28, kcal: 375, name: 'Jamón ibérico', protein: 30, slug: 'jamon-iberico' },
  // ── Poultry and game ──────────────────────────────────────────────────
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 16, kcal: 220, name: 'Alitas de pollo', protein: 18, slug: 'alitas-de-pollo' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 12, kcal: 180, name: 'Contramuslo de pollo deshuesado', protein: 18, slug: 'contramuslo-de-pollo' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 14, kcal: 200, name: 'Pollo entero', protein: 18, slug: 'pollo-entero' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 8, kcal: 150, name: 'Pollo picado', protein: 19, slug: 'pollo-picado' },
  { carbs: 0.7, category: 'protein', classes: ['meat'], fat: 4.8, kcal: 120, name: 'Hígado de pollo', protein: 17, slug: 'higado-de-pollo' },
  { allergens: [{ key: 'gluten', presence: 'may_contain' }], carbs: 3, category: 'protein', classes: ['meat'], defaultUnit: 'unit', fat: 15, gramsPerUnit: 50, kcal: 200, name: 'Salchichas de pollo', protein: 14, slug: 'salchichas-de-pollo' },
  { carbs: 2, category: 'protein', classes: ['meat'], defaultUnit: 'slice', fat: 2.5, gramsPerUnit: 20, kcal: 105, name: 'Fiambre de pollo', protein: 18, slug: 'fiambre-de-pollo' },
  { carbs: 2, category: 'protein', classes: ['meat'], defaultUnit: 'slice', fat: 2, gramsPerUnit: 20, kcal: 100, name: 'Fiambre de pavo', protein: 18, slug: 'fiambre-de-pavo' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 1, kcal: 105, name: 'Pechuga de pavo', protein: 23, slug: 'pechuga-de-pavo' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 8, kcal: 150, name: 'Pavo picado', protein: 20, slug: 'pavo-picado' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 9, kcal: 160, name: 'Muslo de pavo', protein: 19, slug: 'muslo-de-pavo' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 14, kcal: 200, name: 'Magret de pato', protein: 19, slug: 'magret-de-pato' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 23, kcal: 300, name: 'Confit de pato', protein: 22, slug: 'confit-de-pato' },
  { carbs: 0, category: 'protein', classes: ['meat'], defaultUnit: 'unit', fat: 12, gramsPerUnit: 150, kcal: 190, name: 'Codorniz', protein: 20, slug: 'codorniz' },
  // ── Eggs ──────────────────────────────────────────────────────────────
  { allergens: [{ key: 'eggs' }], carbs: 0.4, category: 'protein', defaultUnit: 'unit', fat: 11, gramsPerUnit: 10, kcal: 158, name: 'Huevo de codorniz', protein: 13, slug: 'huevo-de-codorniz' },
  // ── Fresh fish ────────────────────────────────────────────────────────
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 4, kcal: 130, name: 'Atún fresco', protein: 23, slug: 'atun-fresco' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 6, kcal: 140, name: 'Bonito', protein: 21, slug: 'bonito' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 4, kcal: 120, name: 'Trucha', protein: 20, slug: 'trucha' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 3, kcal: 95, name: 'Rodaballo', protein: 16, slug: 'rodaballo' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1, kcal: 75, name: 'Rape', protein: 16, slug: 'rape' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1.5, kcal: 90, name: 'Mero', protein: 19, slug: 'mero' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 4, kcal: 120, name: 'Pez espada', protein: 20, slug: 'pez-espada' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 12, kcal: 190, name: 'Caballa', protein: 19, slug: 'caballa' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 5, kcal: 130, name: 'Boquerones', protein: 20, slug: 'boquerones' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 6, kcal: 130, name: 'Jurel', protein: 19, slug: 'jurel' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 4, kcal: 110, name: 'Palometa', protein: 18, slug: 'palometa' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1, kcal: 80, name: 'Pescadilla', protein: 17, slug: 'pescadilla' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1.2, kcal: 85, name: 'Rosada', protein: 18, slug: 'rosada' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1.7, kcal: 96, name: 'Tilapia', protein: 20, slug: 'tilapia' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1.3, kcal: 80, name: 'Gallo', protein: 17, slug: 'gallo' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1.3, kcal: 85, name: 'Lenguado', protein: 18, slug: 'lenguado' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 5, kcal: 120, name: 'Salmonete', protein: 19, slug: 'salmonete' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 0.7, kcal: 82, name: 'Bacalao fresco', protein: 18, slug: 'bacalao-fresco' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 3, kcal: 290, name: 'Bacalao en salazón', protein: 63, slug: 'bacalao-en-salazon' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 3.5, kcal: 100, name: 'Besugo', protein: 17, slug: 'besugo' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1.5, kcal: 90, name: 'Corvina', protein: 19, slug: 'corvina' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1, kcal: 90, name: 'Perca', protein: 19, slug: 'perca' },
  // ── Preserved and smoked fish ─────────────────────────────────────────
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 11, kcal: 200, name: 'Atún en aceite', protein: 25, slug: 'atun-en-aceite' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 16, kcal: 240, name: 'Ventresca de atún', protein: 23, slug: 'ventresca-de-atun' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 13, kcal: 210, name: 'Sardinas en aceite', protein: 24, slug: 'sardinas-en-aceite' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 10, kcal: 180, name: 'Caballa en conserva', protein: 22, slug: 'caballa-en-conserva' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', defaultUnit: 'unit', fat: 10, gramsPerUnit: 4, kcal: 200, name: 'Anchoas en salazón', protein: 28, slug: 'anchoas-en-salazon' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 10, kcal: 180, name: 'Salmón ahumado', protein: 22, slug: 'salmon-ahumado' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 7, kcal: 150, name: 'Trucha ahumada', protein: 21, slug: 'trucha-ahumada' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 3, kcal: 120, name: 'Bacalao ahumado', protein: 23, slug: 'bacalao-ahumado' },
  { allergens: [{ key: 'fish' }, { key: 'gluten', presence: 'may_contain' }, { key: 'eggs', presence: 'may_contain' }, { key: 'soy', presence: 'may_contain' }], carbs: 11, category: 'protein', fat: 3, kcal: 100, name: 'Gulas', protein: 8, slug: 'gulas' },
  { allergens: [{ key: 'fish' }, { key: 'gluten' }, { key: 'eggs', presence: 'may_contain' }, { key: 'crustaceans', presence: 'may_contain' }], carbs: 12, category: 'protein', fat: 1, kcal: 95, name: 'Palitos de cangrejo (surimi)', protein: 8, slug: 'surimi' },
  { allergens: [{ key: 'molluscs' }], carbs: 4, category: 'protein', fat: 11, kcal: 170, name: 'Mejillones en escabeche', protein: 14, slug: 'mejillones-en-escabeche' },
  { allergens: [{ key: 'molluscs' }], carbs: 2, category: 'protein', fat: 1.5, kcal: 80, name: 'Berberechos al natural', protein: 14, slug: 'berberechos-al-natural' },
  { allergens: [{ key: 'molluscs' }], carbs: 2, category: 'protein', fat: 2, kcal: 90, name: 'Navajas al natural', protein: 16, slug: 'navajas-al-natural' },
  // ── Fresh seafood ─────────────────────────────────────────────────────
  { allergens: [{ key: 'molluscs' }], carbs: 0.7, category: 'protein', fat: 1, kcal: 80, name: 'Sepia', protein: 16, slug: 'sepia' },
  { allergens: [{ key: 'molluscs' }], carbs: 0.7, category: 'protein', fat: 1.2, kcal: 80, name: 'Chipirones', protein: 16, slug: 'chipirones' },
  { allergens: [{ key: 'molluscs' }], carbs: 2.2, category: 'protein', fat: 1, kcal: 82, name: 'Pulpo fresco', protein: 15, slug: 'pulpo-fresco' },
  { allergens: [{ key: 'crustaceans' }, { key: 'sulphites', presence: 'may_contain' }], carbs: 0.5, category: 'protein', fat: 1.5, kcal: 90, name: 'Langostinos', protein: 18, slug: 'langostinos' },
  { allergens: [{ key: 'crustaceans' }, { key: 'sulphites', presence: 'may_contain' }], carbs: 0.5, category: 'protein', fat: 1.2, kcal: 90, name: 'Cigalas', protein: 18, slug: 'cigalas' },
  { allergens: [{ key: 'crustaceans' }], carbs: 0, category: 'protein', fat: 1.2, kcal: 85, name: 'Cangrejo', protein: 18, slug: 'cangrejo' },
  { allergens: [{ key: 'crustaceans' }], carbs: 0.5, category: 'protein', fat: 0.9, kcal: 90, name: 'Bogavante', protein: 19, slug: 'bogavante' },
  { allergens: [{ key: 'molluscs' }], carbs: 2, category: 'protein', fat: 1.5, kcal: 80, name: 'Berberechos', protein: 14, slug: 'berberechos' },
  { allergens: [{ key: 'molluscs' }], carbs: 2, category: 'protein', fat: 2, kcal: 90, name: 'Navajas', protein: 16, slug: 'navajas' },
  { allergens: [{ key: 'molluscs' }], carbs: 3, category: 'protein', fat: 0.8, kcal: 90, name: 'Vieiras', protein: 17, slug: 'vieiras' },
  { allergens: [{ key: 'molluscs' }], carbs: 3, category: 'protein', fat: 0.8, kcal: 85, name: 'Zamburiñas', protein: 16, slug: 'zamburinas' },
  { allergens: [{ key: 'molluscs' }], carbs: 4, category: 'protein', defaultUnit: 'unit', fat: 2.5, gramsPerUnit: 15, kcal: 70, name: 'Ostras', protein: 9, slug: 'ostras' },
  // ── Plant proteins and pulses ─────────────────────────────────────────
  { allergens: [{ key: 'soy' }], carbs: 2, category: 'protein', fat: 3, kcal: 55, name: 'Tofu sedoso', protein: 5, slug: 'tofu-sedoso' },
  { allergens: [{ key: 'soy' }], carbs: 1.5, category: 'protein', fat: 7, kcal: 130, name: 'Tofu ahumado', protein: 15, slug: 'tofu-ahumado' },
  { allergens: [{ key: 'soy' }], carbs: 2, category: 'protein', fat: 2.5, kcal: 110, name: 'Heura', protein: 20, slug: 'heura' },
  { allergens: [{ key: 'soy' }, { key: 'gluten', presence: 'may_contain' }], carbs: 8, category: 'protein', defaultUnit: 'unit', fat: 10, gramsPerUnit: 100, kcal: 190, name: 'Hamburguesa vegetal', protein: 15, slug: 'hamburguesa-vegetal' },
  { carbs: 5, category: 'protein', defaultUnit: 'tbsp', fat: 5, gramsPerUnit: 10, kcal: 380, name: 'Proteína de guisante en polvo', protein: 80, slug: 'proteina-de-guisante' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 8, category: 'protein', defaultUnit: 'tbsp', fat: 6, gramsPerUnit: 10, kcal: 400, name: 'Proteína de suero en polvo', protein: 80, slug: 'proteina-de-suero' },
  { carbs: 52, category: 'protein', fat: 1.5, fiber: 11, kcal: 340, name: 'Lentejas secas', protein: 24, slug: 'lentejas-secas' },
  { carbs: 55, category: 'protein', fat: 6, fiber: 12, kcal: 360, name: 'Garbanzos secos', protein: 20, slug: 'garbanzos-secos' },
  { carbs: 50, category: 'protein', fat: 1.5, fiber: 15, kcal: 330, name: 'Alubias blancas secas', protein: 21, slug: 'alubias-blancas-secas' },
  { carbs: 52, category: 'protein', fat: 1.2, fiber: 15, kcal: 335, name: 'Alubias pintas secas', protein: 21, slug: 'alubias-pintas-secas' },
  { carbs: 52, category: 'protein', fat: 1.2, fiber: 15, kcal: 335, name: 'Judiones', protein: 21, slug: 'judiones' },
  { carbs: 57, category: 'protein', fat: 0.5, fiber: 13, kcal: 330, name: 'Azukis', protein: 20, slug: 'azukis' },
  { carbs: 59, category: 'protein', fat: 1.2, fiber: 16, kcal: 345, name: 'Judía mungo', protein: 24, slug: 'judia-mungo' },
  { allergens: [{ key: 'soy' }], carbs: 30, category: 'protein', fat: 20, fiber: 9, kcal: 440, name: 'Soja en grano', protein: 36, slug: 'soja-en-grano' },
  { allergens: [{ key: 'lupin' }], carbs: 8, category: 'protein', fat: 2.5, fiber: 3, kcal: 120, name: 'Altramuces', protein: 16, slug: 'altramuces' },
  { carbs: 58, category: 'protein', fat: 1, fiber: 22, kcal: 340, name: 'Guisantes secos partidos', protein: 24, slug: 'guisantes-secos-partidos' },
  { carbs: 58, category: 'protein', fat: 1.5, fiber: 15, kcal: 340, name: 'Habas secas', protein: 26, slug: 'habas-secas' },
  { carbs: 22, category: 'protein', fat: 0.5, fiber: 6.4, kcal: 125, name: 'Judías rojas cocidas', protein: 8.7, slug: 'judias-rojas-cocidas' },
  { carbs: 23.7, category: 'protein', fat: 0.5, fiber: 8.7, kcal: 130, name: 'Alubias negras cocidas', protein: 8.9, slug: 'alubias-negras-cocidas' },
  { allergens: [{ key: 'soy' }], carbs: 10, category: 'protein', fat: 9, fiber: 6, kcal: 170, name: 'Soja cocida', protein: 16, slug: 'soja-cocida' },
  // ── Second pass ───────────────────────────────────────────────────────
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 20, kcal: 250, name: 'Costilla de ternera', protein: 17, slug: 'costilla-de-ternera' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 5, kcal: 130, name: 'Ternera para guisar', protein: 20, slug: 'ternera-para-guisar' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 8, kcal: 150, name: 'Cabrito', protein: 19, slug: 'cabrito' },
  { carbs: 0, category: 'protein', classes: ['meat'], defaultUnit: 'unit', fat: 3.5, gramsPerUnit: 200, kcal: 120, name: 'Perdiz', protein: 22, slug: 'perdiz' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 3, kcal: 120, name: 'Carne de ciervo', protein: 22, slug: 'carne-de-ciervo' },
  { allergens: [{ key: 'molluscs' }], carbs: 2, category: 'protein', fat: 1.4, kcal: 90, name: 'Caracoles', protein: 16, slug: 'caracoles' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1.5, kcal: 80, name: 'Bacaladilla', protein: 16, slug: 'bacaladilla' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 2.5, kcal: 95, name: 'Congrio', protein: 18, slug: 'congrio' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1, kcal: 90, name: 'Raya', protein: 20, slug: 'raya' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 0.8, kcal: 80, name: 'Abadejo', protein: 18, slug: 'abadejo' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 3, kcal: 110, name: 'Fletán', protein: 20, slug: 'fletan' },
  { allergens: [{ key: 'fish' }], carbs: 1, category: 'protein', fat: 2.5, kcal: 110, name: 'Huevas de merluza', protein: 20, slug: 'huevas-de-merluza' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 3, kcal: 190, name: 'Mojama', protein: 40, slug: 'mojama' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 9, kcal: 170, name: 'Melva en conserva', protein: 22, slug: 'melva-en-conserva' },
  { allergens: [{ key: 'fish' }], carbs: 1, category: 'protein', fat: 7.5, kcal: 150, name: 'Atún en escabeche', protein: 20, slug: 'atun-en-escabeche' },
  { allergens: [{ key: 'molluscs' }], carbs: 3, category: 'protein', fat: 1.5, kcal: 80, name: 'Almejas al natural', protein: 13, slug: 'almejas-al-natural' },
  { allergens: [{ key: 'molluscs' }], carbs: 4, category: 'protein', fat: 9, kcal: 150, name: 'Calamares en su tinta', protein: 14, slug: 'calamares-en-su-tinta' },
  { allergens: [{ key: 'crustaceans' }, { key: 'sulphites', presence: 'may_contain' }], carbs: 0.5, category: 'protein', fat: 2, kcal: 95, name: 'Gambón', protein: 18, slug: 'gambon' },
  { allergens: [{ key: 'crustaceans' }], carbs: 0, category: 'protein', fat: 2, kcal: 100, name: 'Centollo', protein: 19, slug: 'centollo' },
  { allergens: [{ key: 'soy' }, { key: 'gluten' }], carbs: 8, category: 'protein', defaultUnit: 'unit', fat: 12, gramsPerUnit: 50, kcal: 200, name: 'Salchichas vegetales', protein: 14, slug: 'salchichas-vegetales' },
  { allergens: [{ key: 'soy' }, { key: 'gluten' }], carbs: 22, category: 'protein', fat: 10, kcal: 230, name: 'Nuggets vegetales', protein: 12, slug: 'nuggets-vegetales' },
  { carbs: 15, category: 'protein', fat: 1.5, fiber: 6, kcal: 100, name: 'Frijoles refritos', protein: 6, slug: 'frijoles-refritos' }
];

export const PROTEIN_NAMES_EN_GB: Record<string, string> = {
  abadejo: 'Pollock',
  'alitas-de-pollo': 'Chicken wings',
  'almejas-al-natural': 'Tinned clams',
  altramuces: 'Lupin beans',
  'alubias-blancas-secas': 'Dried white beans',
  'alubias-negras-cocidas': 'Cooked black beans',
  'alubias-pintas-secas': 'Dried pinto beans',
  'anchoas-en-salazon': 'Salted anchovies',
  'atun-en-aceite': 'Tuna in oil',
  'atun-en-escabeche': 'Tuna in escabeche',
  'atun-fresco': 'Fresh tuna',
  azukis: 'Adzuki beans',
  bacaladilla: 'Blue whiting',
  'bacalao-ahumado': 'Smoked cod',
  'bacalao-en-salazon': 'Salt cod',
  'bacalao-fresco': 'Fresh cod',
  bacon: 'Bacon',
  berberechos: 'Cockles',
  'berberechos-al-natural': 'Tinned cockles',
  besugo: 'Sea bream (besugo)',
  bogavante: 'Lobster',
  bonito: 'Bonito',
  boquerones: 'Fresh anchovies',
  butifarra: 'Butifarra sausage',
  caballa: 'Mackerel',
  'caballa-en-conserva': 'Tinned mackerel',
  cabrito: 'Kid goat',
  'calamares-en-su-tinta': 'Squid in its ink',
  cangrejo: 'Crab',
  caracoles: 'Snails',
  'carne-de-ciervo': 'Venison',
  'carne-picada-de-cerdo': 'Pork mince',
  'carne-picada-mixta': 'Mixed beef and pork mince',
  'carrillera-de-cerdo': 'Pork cheek',
  'carrillera-de-ternera': 'Beef cheek',
  centollo: 'Spider crab',
  chipirones: 'Baby squid',
  'chuleta-de-cerdo': 'Pork chop',
  'chuletas-de-cordero': 'Lamb chops',
  'chuleton-de-ternera': 'Rib steak',
  cigalas: 'Langoustines',
  'codillo-de-cerdo': 'Pork knuckle',
  codorniz: 'Quail',
  'confit-de-pato': 'Duck confit',
  congrio: 'Conger eel',
  'contramuslo-de-pollo': 'Boneless chicken thigh',
  'cordero-picado': 'Lamb mince',
  corvina: 'Meagre (corvina)',
  'costilla-de-ternera': 'Beef short ribs',
  'entrecot-de-ternera': 'Entrecôte steak',
  'falda-de-ternera': 'Beef flank',
  'fiambre-de-pavo': 'Turkey cold cuts',
  'fiambre-de-pollo': 'Chicken cold cuts',
  'filete-de-ternera': 'Beef steak',
  fletan: 'Halibut',
  'frijoles-refritos': 'Refried beans',
  fuet: 'Fuet sausage',
  gallo: 'Megrim',
  gambon: 'Argentine red shrimp',
  'garbanzos-secos': 'Dried chickpeas',
  'guisantes-secos-partidos': 'Split peas',
  gulas: 'Gulas (surimi eels)',
  'habas-secas': 'Dried broad beans',
  'hamburguesa-de-ternera': 'Beef burger',
  'hamburguesa-vegetal': 'Veggie burger',
  heura: 'Heura',
  'higado-de-pollo': 'Chicken liver',
  'higado-de-ternera': "Calf's liver",
  'huevas-de-merluza': 'Hake roe',
  'huevo-de-codorniz': 'Quail egg',
  'jamon-iberico': 'Iberian ham',
  'judia-mungo': 'Mung beans',
  'judias-rojas-cocidas': 'Cooked red kidney beans',
  judiones: 'Butter beans',
  jurel: 'Horse mackerel',
  lacon: 'Cured pork shoulder (lacón)',
  langostinos: 'King prawns',
  lenguado: 'Sole',
  'lentejas-secas': 'Dried lentils',
  'lomo-embuchado': 'Cured pork loin',
  'magret-de-pato': 'Duck breast',
  'mejillones-en-escabeche': 'Pickled mussels',
  'melva-en-conserva': 'Tinned frigate tuna (melva)',
  mero: 'Grouper',
  mojama: 'Salt-cured tuna (mojama)',
  morcilla: 'Black pudding (morcilla)',
  'morcillo-de-ternera': 'Beef shin',
  mortadela: 'Mortadella',
  'muslo-de-pavo': 'Turkey thigh',
  navajas: 'Razor clams',
  'navajas-al-natural': 'Tinned razor clams',
  'nuggets-vegetales': 'Vegetable nuggets',
  ostras: 'Oysters',
  'paletilla-de-cordero': 'Lamb shoulder',
  palometa: 'Pomfret',
  'pavo-picado': 'Turkey mince',
  'pechuga-de-pavo': 'Turkey breast',
  perca: 'Perch',
  perdiz: 'Partridge',
  pescadilla: 'Whiting',
  'pez-espada': 'Swordfish',
  'pierna-de-cordero': 'Leg of lamb',
  'pollo-entero': 'Whole chicken',
  'pollo-picado': 'Chicken mince',
  'presa-iberica': 'Iberian pork shoulder steak',
  'proteina-de-guisante': 'Pea protein powder',
  'proteina-de-suero': 'Whey protein powder',
  'pulpo-fresco': 'Fresh octopus',
  'rabo-de-toro': 'Oxtail',
  rape: 'Monkfish',
  raya: 'Skate',
  'redondo-de-ternera': 'Beef round',
  rodaballo: 'Turbot',
  rosada: 'Pink cusk-eel (rosada)',
  'salchichas-de-pollo': 'Chicken sausages',
  'salchichas-frescas': 'Fresh pork sausages',
  'salchichas-vegetales': 'Vegetarian sausages',
  salchichon: 'Salchichón sausage',
  'salmon-ahumado': 'Smoked salmon',
  salmonete: 'Red mullet',
  'sardinas-en-aceite': 'Sardines in oil',
  'secreto-de-cerdo': 'Pork secreto',
  sepia: 'Cuttlefish',
  sobrasada: 'Sobrasada',
  'soja-cocida': 'Cooked soya beans',
  'soja-en-grano': 'Dried soya beans',
  'solomillo-de-cerdo': 'Pork tenderloin',
  surimi: 'Crab sticks (surimi)',
  'ternera-para-guisar': 'Stewing beef',
  tilapia: 'Tilapia',
  'tofu-ahumado': 'Smoked tofu',
  'tofu-sedoso': 'Silken tofu',
  trucha: 'Trout',
  'trucha-ahumada': 'Smoked trout',
  'ventresca-de-atun': 'Tuna belly',
  vieiras: 'Scallops',
  zamburinas: 'Queen scallops'
};
