import type { IngredientSeed } from './types';

/**
 * Starter catalogue for the Spanish/Mediterranean market. Macros are **per 100 g**
 * of edible portion, rounded to one decimal, sourced from BEDCA/USDA composition
 * tables. They exist so a plan's nutrition is looked up, not invented by a model.
 *
 * `gramsPerUnit` is what turns "2 huevos" into grams without a guess — set it on
 * anything a person counts rather than weighs.
 *
 * Adding rows here is safe and expected. Changing an existing row's macros is
 * not: meals snapshot their macros at generation time, so historical plans keep
 * the numbers the user actually ate, but the row still feeds every future plan.
 */
export const STARTER: readonly IngredientSeed[] = [
  // ── Produce ───────────────────────────────────────────────────────────
  { carbs: 3.9, category: 'produce', fat: 0.2, fiber: 1.2, kcal: 18, name: 'Tomate fresco', protein: 0.9, slug: 'tomate', source: 'usda' },
  { carbs: 9.3, category: 'produce', fat: 0.1, fiber: 1.7, kcal: 40, name: 'Cebolla', protein: 1.1, slug: 'cebolla', source: 'usda' },
  { carbs: 6, category: 'produce', fat: 0.3, fiber: 2.1, kcal: 26, name: 'Pimiento rojo', protein: 1, slug: 'pimiento-rojo', source: 'usda' },
  { carbs: 9.6, category: 'produce', fat: 0.2, fiber: 2.8, kcal: 41, name: 'Zanahoria', protein: 0.9, slug: 'zanahoria', source: 'usda' },
  { carbs: 3.6, category: 'produce', fat: 0.4, fiber: 2.2, kcal: 23, name: 'Espinaca', protein: 2.9, slug: 'espinaca', source: 'usda' },
  { carbs: 6.6, category: 'produce', fat: 0.4, fiber: 2.6, kcal: 34, name: 'Brócoli', protein: 2.8, slug: 'brocoli', source: 'usda' },
  { carbs: 3.1, category: 'produce', fat: 0.3, fiber: 1, kcal: 17, name: 'Calabacín', protein: 1.2, slug: 'calabacin', source: 'usda' },
  { carbs: 17.5, category: 'produce', fat: 0.1, fiber: 2.1, kcal: 77, name: 'Patata', protein: 2, slug: 'patata', source: 'usda' },
  { carbs: 20.1, category: 'produce', fat: 0.1, fiber: 3, kcal: 86, name: 'Boniato', protein: 1.6, slug: 'boniato', source: 'usda' },
  { carbs: 8.5, category: 'produce', fat: 14.7, fiber: 6.7, kcal: 160, name: 'Aguacate', protein: 2, slug: 'aguacate', source: 'usda' },
  { carbs: 13.6, category: 'produce', defaultUnit: 'unit', fat: 0.1, fiber: 2.4, gramsPerUnit: 180, kcal: 57, name: 'Manzana', protein: 0.3, slug: 'manzana', source: 'usda' },
  { carbs: 22.8, category: 'produce', defaultUnit: 'unit', fat: 0.3, fiber: 2.6, gramsPerUnit: 120, kcal: 89, name: 'Plátano', protein: 1.1, slug: 'platano', source: 'usda' },
  { carbs: 11.8, category: 'produce', defaultUnit: 'unit', fat: 0.1, fiber: 2.4, gramsPerUnit: 130, kcal: 47, name: 'Naranja', protein: 0.9, slug: 'naranja', source: 'usda' },
  { carbs: 7.7, category: 'produce', fat: 0.3, fiber: 2, kcal: 32, name: 'Fresa', protein: 0.7, slug: 'fresa', source: 'usda' },
  { carbs: 33.1, category: 'produce', fat: 0.5, fiber: 2.1, kcal: 149, name: 'Ajo', protein: 6.4, slug: 'ajo', source: 'usda' },
  { carbs: 2.9, category: 'produce', fat: 0.1, fiber: 1.3, kcal: 15, name: 'Lechuga', protein: 1.4, slug: 'lechuga', source: 'usda' },
  { carbs: 3.6, category: 'produce', fat: 0.1, fiber: 0.5, kcal: 15, name: 'Pepino', protein: 0.7, slug: 'pepino', source: 'usda' },
  { carbs: 3.3, category: 'produce', fat: 0.3, fiber: 1, kcal: 22, name: 'Champiñón', protein: 3.1, slug: 'champinon', source: 'usda' },
  { allergens: [{ key: 'celery' }], carbs: 3, category: 'produce', fat: 0.2, fiber: 1.6, kcal: 14, name: 'Apio', protein: 0.7, slug: 'apio', source: 'usda' },
  { carbs: 4.6, category: 'produce', fat: 0.2, fiber: 1.7, kcal: 20, name: 'Pimiento verde', protein: 0.9, slug: 'pimiento-verde', source: 'usda' },
  { carbs: 5.9, category: 'produce', fat: 0.2, fiber: 3, kcal: 25, name: 'Berenjena', protein: 1, slug: 'berenjena', source: 'usda' },
  { carbs: 5, category: 'produce', fat: 0.3, fiber: 2, kcal: 25, name: 'Coliflor', protein: 1.9, slug: 'coliflor', source: 'usda' },
  { carbs: 4.4, category: 'produce', fat: 1.5, fiber: 4.1, kcal: 35, name: 'Col rizada', protein: 2.9, slug: 'col-rizada', source: 'usda' },
  { carbs: 7, category: 'produce', fat: 0.2, fiber: 2.7, kcal: 31, name: 'Judía verde', protein: 1.8, slug: 'judia-verde', source: 'usda' },
  { carbs: 14.2, category: 'produce', fat: 0.3, fiber: 1.8, kcal: 61, name: 'Puerro', protein: 1.5, slug: 'puerro', source: 'usda' },
  { carbs: 3.6, category: 'produce', fat: 0.7, fiber: 1.6, kcal: 25, name: 'Rúcula', protein: 2.6, slug: 'rucula', source: 'usda' },
  { carbs: 3.4, category: 'produce', fat: 0.2, fiber: 3.1, kcal: 17, name: 'Escarola', protein: 1.2, slug: 'escarola', source: 'usda' },
  { carbs: 9.6, category: 'produce', fat: 0.2, fiber: 2.8, kcal: 43, name: 'Remolacha', protein: 1.6, slug: 'remolacha', source: 'usda' },
  { carbs: 3.4, category: 'produce', fat: 0.1, fiber: 1.6, kcal: 16, name: 'Rábano', protein: 0.7, slug: 'rabano', source: 'usda' },
  { carbs: 6.4, category: 'produce', fat: 0.1, fiber: 1.8, kcal: 28, name: 'Nabo', protein: 0.9, slug: 'nabo', source: 'usda' },
  { carbs: 10.5, category: 'produce', defaultUnit: 'unit', fat: 0.1, fiber: 5.4, gramsPerUnit: 120, kcal: 47, name: 'Alcachofa', protein: 3.3, slug: 'alcachofa', source: 'usda' },
  { carbs: 3.9, category: 'produce', defaultUnit: 'unit', fat: 0.1, fiber: 2.1, gramsPerUnit: 20, kcal: 20, name: 'Espárrago verde', protein: 2.2, slug: 'esparrago-verde', source: 'usda' },
  { carbs: 6.5, category: 'produce', fat: 0.1, fiber: 0.5, kcal: 26, name: 'Calabaza', protein: 1, slug: 'calabaza', source: 'usda' },
  { carbs: 21, category: 'produce', fat: 1.5, fiber: 2.4, kcal: 96, name: 'Maíz dulce cocido', protein: 3.4, slug: 'maiz-dulce', source: 'usda' },
  { carbs: 16.8, category: 'produce', fat: 0.1, fiber: 3.2, kcal: 72, name: 'Chalota', protein: 2.5, slug: 'chalota', source: 'usda' },
  { carbs: 7.3, category: 'produce', fat: 0.2, fiber: 2.6, kcal: 32, name: 'Cebolleta', protein: 1.8, slug: 'cebolleta', source: 'usda' },
  { carbs: 6.3, category: 'produce', fat: 0.8, fiber: 3.3, kcal: 36, name: 'Perejil fresco', protein: 3, slug: 'perejil', source: 'usda' },
  { carbs: 3.7, category: 'produce', fat: 0.5, fiber: 2.8, kcal: 23, name: 'Cilantro fresco', protein: 2.1, slug: 'cilantro', source: 'usda' },
  { carbs: 9.3, category: 'produce', defaultUnit: 'unit', fat: 0.3, fiber: 2.8, gramsPerUnit: 100, kcal: 29, name: 'Limón', protein: 1.1, slug: 'limon', source: 'usda' },
  { carbs: 18.1, category: 'produce', fat: 0.2, fiber: 0.9, kcal: 69, name: 'Uva', protein: 0.7, slug: 'uva', source: 'usda' },
  { carbs: 9.5, category: 'produce', defaultUnit: 'unit', fat: 0.2, fiber: 1.5, gramsPerUnit: 150, kcal: 39, name: 'Melocotón', protein: 0.9, slug: 'melocoton', source: 'usda' },
  { carbs: 15.2, category: 'produce', defaultUnit: 'unit', fat: 0.1, fiber: 3.1, gramsPerUnit: 170, kcal: 57, name: 'Pera', protein: 0.4, slug: 'pera', source: 'usda' },
  { carbs: 14.7, category: 'produce', defaultUnit: 'unit', fat: 0.5, fiber: 3, gramsPerUnit: 75, kcal: 61, name: 'Kiwi', protein: 1.1, slug: 'kiwi', source: 'usda' },
  { carbs: 9.1, category: 'produce', fat: 0.1, fiber: 0.8, kcal: 36, name: 'Melón', protein: 0.5, slug: 'melon', source: 'usda' },
  { carbs: 7.5, category: 'produce', fat: 0.1, fiber: 0.4, kcal: 30, name: 'Sandía', protein: 0.6, slug: 'sandia', source: 'usda' },

  // ── Protein ───────────────────────────────────────────────────────────
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 2.6, kcal: 120, name: 'Pechuga de pollo', protein: 22.5, slug: 'pechuga-de-pollo', source: 'usda' },
  { carbs: 0.2, category: 'protein', classes: ['meat'], fat: 16.6, kcal: 221, name: 'Muslo de pollo', protein: 16.5, slug: 'muslo-de-pollo', source: 'usda' },
  { carbs: 0.1, category: 'protein', classes: ['meat'], fat: 1.9, kcal: 115, name: 'Pavo fresco', protein: 22.6, slug: 'pavo', source: 'usda' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 4.1, kcal: 135, name: 'Ternera magra', protein: 22.9, slug: 'ternera-magra', source: 'usda' },
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 6.9, kcal: 155, name: 'Lomo de cerdo', protein: 21.6, slug: 'lomo-de-cerdo', source: 'usda' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 13.4, kcal: 208, name: 'Salmón fresco', protein: 20.4, slug: 'salmon', source: 'usda' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 1, kcal: 82, name: 'Merluza fresca', protein: 17.8, slug: 'merluza' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 0.8, kcal: 116, name: 'Atún al natural', protein: 25.5, slug: 'atun-al-natural', source: 'usda' },
  { allergens: [{ key: 'crustaceans' }], carbs: 0, category: 'protein', fat: 0.5, kcal: 85, name: 'Gambas frescas', protein: 20.1, slug: 'gambas', source: 'usda' },
  { allergens: [{ key: 'molluscs' }], carbs: 3.7, category: 'protein', fat: 2.2, kcal: 86, name: 'Mejillón', protein: 11.9, slug: 'mejillon', source: 'usda' },
  { allergens: [{ key: 'eggs' }], carbs: 0.7, category: 'protein', defaultUnit: 'unit', fat: 9.5, gramsPerUnit: 58, kcal: 143, name: 'Huevo', protein: 12.6, slug: 'huevo', source: 'usda' },
  { allergens: [{ key: 'soy' }], carbs: 2.8, category: 'protein', fat: 8.7, fiber: 2.3, kcal: 144, name: 'Tofu firme', protein: 17.3, slug: 'tofu-firme', source: 'usda' },
  { carbs: 27.4, category: 'protein', fat: 2.6, fiber: 7.6, kcal: 164, name: 'Garbanzos cocidos', protein: 8.9, slug: 'garbanzos-cocidos', source: 'usda' },
  { carbs: 20.1, category: 'protein', fat: 0.4, fiber: 7.9, kcal: 116, name: 'Lentejas cocidas', protein: 9, slug: 'lentejas-cocidas', source: 'usda' },
  { carbs: 25.1, category: 'protein', fat: 0.3, fiber: 6.3, kcal: 139, name: 'Alubias blancas cocidas', protein: 9.7, slug: 'alubias-blancas-cocidas', source: 'usda' },
  { carbs: 0.5, category: 'protein', classes: ['pork'], fat: 14, kcal: 248, name: 'Jamón serrano', protein: 30.1, slug: 'jamon-serrano', source: 'bedca' },
  { carbs: 1.5, category: 'protein', classes: ['pork'], fat: 3, kcal: 101, name: 'Jamón cocido', protein: 17, slug: 'jamon-cocido', source: 'bedca' },
  { carbs: 3.8, category: 'protein', classes: ['pork'], fat: 25.1, kcal: 296, name: 'Chorizo', protein: 13.6, slug: 'chorizo', source: 'usda' },
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 53, kcal: 518, name: 'Panceta', protein: 9.3, slug: 'panceta', source: 'usda' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 6.5, kcal: 153, name: 'Solomillo de ternera', protein: 22.1, slug: 'solomillo-de-ternera', source: 'usda' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 10, kcal: 176, name: 'Carne picada de ternera', protein: 20, slug: 'carne-picada-de-ternera', source: 'usda' },
  { carbs: 0, category: 'protein', classes: ['pork'], fat: 23.4, kcal: 277, name: 'Costillas de cerdo', protein: 15.5, slug: 'costillas-de-cerdo', source: 'usda' },
  { carbs: 0, category: 'protein', classes: ['meat'], fat: 5.5, kcal: 136, name: 'Conejo', protein: 20.1, slug: 'conejo', source: 'usda' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 0.7, kcal: 78, name: 'Bacalao desalado', protein: 17.8, slug: 'bacalao-desalado', source: 'bedca' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 3, kcal: 103, name: 'Dorada', protein: 19, slug: 'dorada', source: 'bedca' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 2, kcal: 97, name: 'Lubina', protein: 18.4, slug: 'lubina', source: 'usda' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'protein', fat: 11, kcal: 179, name: 'Sardina', protein: 20, slug: 'sardina', source: 'bedca' },
  { allergens: [{ key: 'molluscs' }], carbs: 3.1, category: 'protein', fat: 1.4, kcal: 92, name: 'Calamar', protein: 15.6, slug: 'calamar', source: 'usda' },
  { allergens: [{ key: 'molluscs' }], carbs: 2, category: 'protein', fat: 1, kcal: 89, name: 'Pulpo cocido', protein: 18, slug: 'pulpo-cocido', source: 'bedca' },
  { allergens: [{ key: 'molluscs' }], carbs: 3.6, category: 'protein', fat: 1, kcal: 86, name: 'Almeja', protein: 14.7, slug: 'almeja', source: 'usda' },
  { allergens: [{ key: 'eggs' }], carbs: 0.7, category: 'protein', defaultUnit: 'unit', fat: 0.2, gramsPerUnit: 33, kcal: 52, name: 'Clara de huevo', protein: 10.9, slug: 'clara-de-huevo', source: 'usda' },
  { allergens: [{ key: 'soy' }], carbs: 8.9, category: 'protein', fat: 5.2, fiber: 5.2, kcal: 121, name: 'Edamame cocido', protein: 11.9, slug: 'edamame-cocido', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 4, category: 'protein', fat: 1.9, fiber: 0.6, kcal: 133, name: 'Seitán', protein: 25, slug: 'seitan', source: 'usda' },
  { allergens: [{ key: 'soy' }], carbs: 7.6, category: 'protein', fat: 10.8, fiber: 0, kcal: 192, name: 'Tempeh', protein: 20.3, slug: 'tempeh', source: 'usda' },
  { carbs: 26.2, category: 'protein', fat: 0.7, fiber: 9, kcal: 143, name: 'Alubias pintas cocidas', protein: 9, slug: 'alubias-pintas-cocidas', source: 'usda' },

  // ── Dairy ─────────────────────────────────────────────────────────────
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4, category: 'dairy', fat: 5, kcal: 97, name: 'Yogur griego natural', protein: 9, slug: 'yogur-griego-natural', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 7.7, category: 'dairy', fat: 0.2, kcal: 56, name: 'Yogur natural desnatado', protein: 5.7, slug: 'yogur-natural-desnatado', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4.8, category: 'dairy', defaultUnit: 'ml', fat: 2, kcal: 50, name: 'Leche semidesnatada', protein: 3.3, slug: 'leche-semidesnatada', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 3.4, category: 'dairy', fat: 4.3, kcal: 98, name: 'Requesón', protein: 11.1, slug: 'requeson' },
  { allergens: [{ key: 'milk' }], carbs: 1.3, category: 'dairy', fat: 33.1, kcal: 402, name: 'Queso curado', protein: 25, slug: 'queso-curado' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 0, category: 'dairy', fat: 21.1, kcal: 264, name: 'Queso fresco de cabra', protein: 18.5, slug: 'queso-fresco-de-cabra', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4.8, category: 'dairy', defaultUnit: 'ml', fat: 3.2, kcal: 61, name: 'Leche entera', protein: 3.1, slug: 'leche-entera', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 5, category: 'dairy', defaultUnit: 'ml', fat: 0.1, kcal: 34, name: 'Leche desnatada', protein: 3.4, slug: 'leche-desnatada', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 2.4, category: 'dairy', fat: 22.1, kcal: 299, name: 'Queso mozzarella', protein: 22.2, slug: 'queso-mozzarella', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 3.2, category: 'dairy', fat: 25, kcal: 392, name: 'Queso parmesano', protein: 35.8, slug: 'queso-parmesano', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 3, category: 'dairy', fat: 8, kcal: 132, name: 'Queso de Burgos', protein: 12, slug: 'queso-de-burgos', source: 'bedca' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 3.4, category: 'dairy', fat: 4.3, kcal: 98, name: 'Queso cottage', protein: 11.1, slug: 'queso-cottage', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 3.7, category: 'dairy', defaultUnit: 'ml', fat: 19.1, kcal: 195, name: 'Nata para cocinar', protein: 3, slug: 'nata-para-cocinar', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 0.1, category: 'dairy', defaultUnit: 'tbsp', fat: 81.1, gramsPerUnit: 14, kcal: 717, name: 'Mantequilla con sal', protein: 0.8, slug: 'mantequilla', source: 'usda' },
  { allergens: [{ key: 'milk' }, { key: 'lactose' }], carbs: 4.5, category: 'dairy', defaultUnit: 'ml', fat: 3.5, kcal: 63, name: 'Kéfir', protein: 3.3, slug: 'kefir', source: 'bedca' },

  // ── Pantry ────────────────────────────────────────────────────────────
  { carbs: 28.6, category: 'pantry', fat: 0.2, fiber: 0, kcal: 130, name: 'Arroz blanco cocido', protein: 2.4, slug: 'arroz-blanco-cocido', source: 'usda' },
  { carbs: 23.5, category: 'pantry', fat: 0.8, fiber: 1.8, kcal: 112, name: 'Arroz integral cocido', protein: 2.3, slug: 'arroz-integral-cocido', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 30.9, category: 'pantry', fat: 0.9, fiber: 1.8, kcal: 158, name: 'Pasta cocida', protein: 5.8, slug: 'pasta-cocida', source: 'usda' },
  { carbs: 21.3, category: 'pantry', fat: 1.9, fiber: 2.8, kcal: 120, name: 'Quinoa cocida', protein: 4.4, slug: 'quinoa-cocida', source: 'usda' },
  { allergens: [{ key: 'gluten', presence: 'may_contain' }], carbs: 67.7, category: 'pantry', fat: 6.5, fiber: 10.1, kcal: 379, name: 'Copos de avena', protein: 13.2, slug: 'copos-de-avena', source: 'usda' },
  { carbs: 0, category: 'pantry', defaultUnit: 'tbsp', fat: 100, gramsPerUnit: 13.5, kcal: 884, name: 'Aceite de oliva virgen extra', protein: 0, slug: 'aceite-de-oliva-virgen-extra', source: 'usda' },
  { allergens: [{ key: 'tree_nuts' }], carbs: 21.6, category: 'pantry', fat: 49.9, fiber: 12.5, kcal: 579, name: 'Almendras', protein: 21.1, slug: 'almendras', source: 'usda' },
  { allergens: [{ key: 'tree_nuts' }], carbs: 13.7, category: 'pantry', fat: 65.2, fiber: 6.7, kcal: 654, name: 'Nueces', protein: 15.2, slug: 'nueces', source: 'usda' },
  { carbs: 42.1, category: 'pantry', fat: 30.7, fiber: 34.4, kcal: 486, name: 'Semillas de chía', protein: 16.5, slug: 'semillas-de-chia', source: 'usda' },
  { allergens: [{ key: 'sesame' }], carbs: 23.4, category: 'pantry', fat: 49.7, fiber: 11.8, kcal: 573, name: 'Sésamo', protein: 17.7, slug: 'sesamo', source: 'usda' },
  { carbs: 9, category: 'pantry', fat: 0.2, fiber: 1.9, kcal: 38, name: 'Tomate triturado', protein: 1.6, slug: 'tomate-triturado', source: 'usda' },
  { allergens: [{ key: 'mustard' }], carbs: 5.8, category: 'pantry', defaultUnit: 'tsp', fat: 3.3, fiber: 4, gramsPerUnit: 5, kcal: 60, name: 'Mostaza de Dijon', protein: 3.7, slug: 'mostaza-de-dijon', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 72, category: 'pantry', fat: 5.3, fiber: 4.5, kcal: 395, name: 'Pan rallado', protein: 13.3, slug: 'pan-rallado', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 76.3, category: 'pantry', fat: 1, fiber: 2.7, kcal: 364, name: 'Harina de trigo', protein: 10.3, slug: 'harina-de-trigo', source: 'usda' },
  { allergens: [{ key: 'gluten', presence: 'may_contain' }], carbs: 65.7, category: 'pantry', fat: 9.1, fiber: 6.5, kcal: 404, name: 'Harina de avena', protein: 14.7, slug: 'harina-de-avena', source: 'usda' },
  { allergens: [{ key: 'tree_nuts' }], carbs: 14, category: 'pantry', fat: 50, fiber: 10, kcal: 590, name: 'Harina de almendra', protein: 21, slug: 'harina-de-almendra', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 23.2, category: 'pantry', fat: 0.2, fiber: 1.4, kcal: 112, name: 'Cuscús cocido', protein: 3.8, slug: 'cuscus-cocido', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 18.6, category: 'pantry', fat: 0.2, fiber: 4.5, kcal: 83, name: 'Bulgur cocido', protein: 3.1, slug: 'bulgur-cocido', source: 'usda' },
  { carbs: 24, category: 'pantry', fat: 0.2, fiber: 1, kcal: 108, name: 'Fideos de arroz cocidos', protein: 1.8, slug: 'fideos-de-arroz-cocidos', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 30.1, category: 'pantry', fat: 1.7, fiber: 3.9, kcal: 149, name: 'Pasta integral cocida', protein: 6, slug: 'pasta-integral-cocida', source: 'usda' },
  { carbs: 20, category: 'pantry', fat: 0.4, fiber: 8, kcal: 120, name: 'Lentejas rojas cocidas', protein: 9, slug: 'lentejas-rojas-cocidas', source: 'usda' },
  { allergens: [{ key: 'soy' }], carbs: 8, category: 'pantry', fat: 1, fiber: 6, kcal: 113, name: 'Soja texturizada cocida', protein: 18, slug: 'soja-texturizada', source: 'usda' },
  { allergens: [{ key: 'tree_nuts' }], carbs: 30.2, category: 'pantry', fat: 43.9, fiber: 3.3, kcal: 553, name: 'Anacardos', protein: 18.2, slug: 'anacardos', source: 'usda' },
  { allergens: [{ key: 'tree_nuts' }], carbs: 27.2, category: 'pantry', fat: 45.3, fiber: 10.6, kcal: 560, name: 'Pistachos', protein: 20.2, slug: 'pistachos', source: 'usda' },
  { allergens: [{ key: 'tree_nuts' }], carbs: 16.7, category: 'pantry', fat: 60.8, fiber: 9.7, kcal: 628, name: 'Avellanas', protein: 14.9, slug: 'avellanas', source: 'usda' },
  { allergens: [{ key: 'peanuts' }, { key: 'tree_nuts', presence: 'may_contain' }], carbs: 16.1, category: 'pantry', fat: 49.2, fiber: 8.5, kcal: 567, name: 'Cacahuetes', protein: 25.8, slug: 'cacahuetes', source: 'usda' },
  { allergens: [{ key: 'tree_nuts', presence: 'may_contain' }], carbs: 20, category: 'pantry', fat: 51.5, fiber: 8.6, kcal: 584, name: 'Pipas de girasol', protein: 20.8, slug: 'pipas-de-girasol', source: 'usda' },
  { allergens: [{ key: 'tree_nuts', presence: 'may_contain' }], carbs: 10.7, category: 'pantry', fat: 49, fiber: 6, kcal: 559, name: 'Semillas de calabaza', protein: 30.2, slug: 'semillas-de-calabaza', source: 'usda' },
  { allergens: [{ key: 'tree_nuts', presence: 'may_contain' }], carbs: 28.9, category: 'pantry', fat: 42.2, fiber: 27.3, kcal: 534, name: 'Semillas de lino', protein: 18.3, slug: 'semillas-de-lino', source: 'usda' },
  { allergens: [{ key: 'sesame' }], carbs: 21.2, category: 'pantry', defaultUnit: 'tbsp', fat: 53.8, fiber: 9.3, gramsPerUnit: 15, kcal: 595, name: 'Tahini', protein: 17, slug: 'tahini', source: 'usda' },
  { allergens: [{ key: 'peanuts' }, { key: 'tree_nuts', presence: 'may_contain' }], carbs: 22.3, category: 'pantry', defaultUnit: 'tbsp', fat: 51.4, fiber: 5, gramsPerUnit: 16, kcal: 598, name: 'Mantequilla de cacahuete', protein: 22.2, slug: 'mantequilla-de-cacahuete', source: 'usda' },
  { carbs: 0, category: 'pantry', defaultUnit: 'tbsp', fat: 100, gramsPerUnit: 13.5, kcal: 884, name: 'Aceite de girasol', protein: 0, slug: 'aceite-de-girasol', source: 'usda' },
  { carbs: 0, category: 'pantry', defaultUnit: 'tbsp', fat: 99.1, gramsPerUnit: 13.5, kcal: 892, name: 'Aceite de coco', protein: 0, slug: 'aceite-de-coco', source: 'usda' },
  { carbs: 0.9, category: 'pantry', defaultUnit: 'tbsp', fat: 0, gramsPerUnit: 15, kcal: 21, name: 'Vinagre de manzana', protein: 0, slug: 'vinagre-de-manzana', source: 'usda' },
  { carbs: 1, category: 'pantry', defaultUnit: 'tbsp', fat: 0, gramsPerUnit: 15, kcal: 5, name: 'Vinagre de Jerez', protein: 0.2, slug: 'vinagre-de-jerez', source: 'bedca' },
  { carbs: 11, category: 'pantry', fat: 4, fiber: 1.5, kcal: 86, name: 'Tomate frito', protein: 1.5, slug: 'tomate-frito', source: 'bedca' },
  { carbs: 0.4, category: 'pantry', classes: ['meat'], defaultUnit: 'ml', fat: 0.2, kcal: 6, name: 'Caldo de pollo', protein: 0.6, slug: 'caldo-de-pollo', source: 'usda' },
  { carbs: 1, category: 'pantry', defaultUnit: 'ml', fat: 0.1, kcal: 6, name: 'Caldo de verduras', protein: 0.2, slug: 'caldo-de-verduras', source: 'usda' },
  { allergens: [{ key: 'gluten', presence: 'may_contain' }], carbs: 84, category: 'pantry', fat: 0.9, fiber: 3, kcal: 372, name: 'Copos de maíz', protein: 7, slug: 'copos-de-maiz', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 66, category: 'pantry', fat: 6, fiber: 8, kcal: 358, name: 'Muesli', protein: 10, slug: 'muesli', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 51.8, category: 'pantry', fat: 9.7, fiber: 13.2, kcal: 360, name: 'Germen de trigo', protein: 23.1, slug: 'germen-de-trigo', source: 'usda' },
  { carbs: 28, category: 'pantry', defaultUnit: 'tsp', fat: 0, gramsPerUnit: 4, kcal: 112, name: 'Levadura química', protein: 0, slug: 'levadura-quimica', source: 'usda' },
  { carbs: 91.3, category: 'pantry', fat: 0.1, fiber: 0.9, kcal: 381, name: 'Maicena', protein: 0.3, slug: 'maicena', source: 'usda' },
  { carbs: 28.2, category: 'pantry', fat: 0.3, fiber: 0.4, kcal: 130, name: 'Arroz basmati cocido', protein: 2.7, slug: 'arroz-basmati-cocido', source: 'usda' },
  { allergens: [{ key: 'soy' }, { key: 'gluten' }], carbs: 4.9, category: 'pantry', defaultUnit: 'tbsp', fat: 0.6, fiber: 0.8, gramsPerUnit: 15, kcal: 53, name: 'Salsa de soja', protein: 8.1, slug: 'salsa-de-soja', source: 'usda' },

  // ── Bakery ────────────────────────────────────────────────────────────
  { allergens: [{ key: 'gluten' }], carbs: 42.7, category: 'bakery', defaultUnit: 'slice', fat: 3.5, fiber: 6, gramsPerUnit: 40, kcal: 252, name: 'Pan integral', protein: 12.4, slug: 'pan-integral', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 49.3, category: 'bakery', defaultUnit: 'unit', fat: 7.6, fiber: 2.4, gramsPerUnit: 60, kcal: 297, name: 'Tortilla de trigo', protein: 8, slug: 'tortilla-de-trigo', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 54.5, category: 'bakery', defaultUnit: 'slice', fat: 4, fiber: 2.9, gramsPerUnit: 30, kcal: 290, name: 'Pan blanco', protein: 9, slug: 'pan-blanco', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 48.3, category: 'bakery', defaultUnit: 'slice', fat: 3.3, fiber: 5.8, gramsPerUnit: 35, kcal: 259, name: 'Pan de centeno', protein: 8.5, slug: 'pan-de-centeno', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 54.5, category: 'bakery', defaultUnit: 'slice', fat: 4, fiber: 2.9, gramsPerUnit: 25, kcal: 290, name: 'Pan de molde', protein: 9, slug: 'pan-de-molde', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 52.4, category: 'bakery', defaultUnit: 'unit', fat: 1.3, fiber: 1.6, gramsPerUnit: 90, kcal: 264, name: 'Bagel', protein: 10.6, slug: 'bagel', source: 'usda' },
  { carbs: 45, category: 'bakery', defaultUnit: 'unit', fat: 3.4, fiber: 3.4, gramsPerUnit: 25, kcal: 233, name: 'Tortitas de maíz', protein: 5.7, slug: 'tortitas-de-maiz', source: 'usda' },
  { carbs: 81.5, category: 'bakery', defaultUnit: 'unit', fat: 2.8, fiber: 4.2, gramsPerUnit: 9, kcal: 387, name: 'Tortitas de arroz', protein: 8.2, slug: 'tortitas-de-arroz', source: 'usda' },
  { allergens: [{ key: 'gluten' }], carbs: 73, category: 'bakery', defaultUnit: 'unit', fat: 7, fiber: 3.5, gramsPerUnit: 5, kcal: 399, name: 'Picos de pan', protein: 11, slug: 'picos-de-pan', source: 'bedca' },
  { allergens: [{ key: 'gluten' }], carbs: 50.1, category: 'bakery', defaultUnit: 'unit', fat: 3.9, fiber: 1.8, gramsPerUnit: 60, kcal: 279, name: 'Pan de hamburguesa', protein: 9.8, slug: 'pan-de-hamburguesa', source: 'usda' },
  { allergens: [{ key: 'gluten' }, { key: 'milk' }, { key: 'eggs' }], carbs: 45.8, category: 'bakery', defaultUnit: 'unit', fat: 21, fiber: 2.6, gramsPerUnit: 60, kcal: 406, name: 'Croissant', protein: 8.2, slug: 'croissant', source: 'usda' },
  { allergens: [{ key: 'gluten' }, { key: 'milk' }, { key: 'eggs' }], carbs: 41.4, category: 'bakery', defaultUnit: 'unit', fat: 11.4, fiber: 2.7, gramsPerUnit: 40, kcal: 296, name: 'Magdalena', protein: 6.9, slug: 'magdalena', source: 'usda' },

  // ── Frozen ────────────────────────────────────────────────────────────
  { carbs: 13.6, category: 'frozen', fat: 0.4, fiber: 4.5, kcal: 77, name: 'Guisantes congelados', protein: 5.2, slug: 'guisantes-congelados', source: 'usda' },
  { carbs: 7.5, category: 'frozen', fat: 0.2, fiber: 2.6, kcal: 33, name: 'Judía verde congelada', protein: 1.8, slug: 'judia-verde-congelada', source: 'usda' },
  { carbs: 4.8, category: 'frozen', fat: 0.3, fiber: 3, kcal: 26, name: 'Brócoli congelado', protein: 2.8, slug: 'brocoli-congelado', source: 'usda' },
  { carbs: 4.2, category: 'frozen', fat: 0.6, fiber: 2.9, kcal: 29, name: 'Espinacas congeladas', protein: 3.6, slug: 'espinacas-congeladas', source: 'usda' },
  { carbs: 20.7, category: 'frozen', fat: 0.8, fiber: 2.1, kcal: 88, name: 'Maíz congelado', protein: 3, slug: 'maiz-congelado', source: 'usda' },
  { carbs: 13.5, category: 'frozen', fat: 0.5, fiber: 4, kcal: 72, name: 'Mix de verduras congelado', protein: 3.3, slug: 'mix-de-verduras-congelado', source: 'usda' },
  { carbs: 12, category: 'frozen', fat: 0.4, fiber: 4, kcal: 55, name: 'Frutos rojos congelados', protein: 0.8, slug: 'frutos-rojos-congelados', source: 'usda' },
  { allergens: [{ key: 'fish' }], carbs: 0, category: 'frozen', fat: 1, kcal: 77, name: 'Filete de merluza congelado', protein: 17, slug: 'filete-de-merluza-congelado', source: 'bedca' },

  // ── Beverages ─────────────────────────────────────────────────────────
  { allergens: [{ key: 'tree_nuts' }], carbs: 1.3, category: 'beverages', defaultUnit: 'ml', fat: 1, kcal: 15, name: 'Leche de almendra', protein: 0.4, slug: 'leche-de-almendra', source: 'usda' },
  { allergens: [{ key: 'gluten', presence: 'may_contain' }], carbs: 6.7, category: 'beverages', defaultUnit: 'ml', fat: 1.5, fiber: 0.8, kcal: 44, name: 'Leche de avena', protein: 1, slug: 'leche-de-avena', source: 'usda' },
  { allergens: [{ key: 'soy' }], carbs: 1.7, category: 'beverages', defaultUnit: 'ml', fat: 1.6, fiber: 0.5, kcal: 33, name: 'Leche de soja', protein: 2.9, slug: 'leche-de-soja', source: 'usda' },
  { carbs: 0, category: 'beverages', defaultUnit: 'ml', fat: 0, kcal: 1, name: 'Café solo', protein: 0.1, slug: 'cafe-solo', source: 'usda' },
  { carbs: 0, category: 'beverages', defaultUnit: 'ml', fat: 0, kcal: 1, name: 'Té verde', protein: 0.2, slug: 'te-verde', source: 'usda' },

  // ── Other ─────────────────────────────────────────────────────────────
  { carbs: 82.4, category: 'other', classes: ['animal'], defaultUnit: 'tbsp', fat: 0, gramsPerUnit: 21, kcal: 304, name: 'Miel', protein: 0.3, slug: 'miel', source: 'usda' },
  { carbs: 100, category: 'other', defaultUnit: 'tsp', fat: 0, gramsPerUnit: 4.2, kcal: 387, name: 'Azúcar blanco', protein: 0, slug: 'azucar-blanco', source: 'usda' },
  { carbs: 76.4, category: 'other', defaultUnit: 'tbsp', fat: 0.5, gramsPerUnit: 21, kcal: 310, name: 'Sirope de agave', protein: 0.1, slug: 'sirope-de-agave', source: 'usda' },
  { carbs: 68.9, category: 'other', defaultUnit: 'tbsp', fat: 0.1, fiber: 1.1, gramsPerUnit: 20, kcal: 278, name: 'Mermelada de fresa', protein: 0.4, slug: 'mermelada-de-fresa', source: 'usda' },
  { carbs: 57.9, category: 'other', defaultUnit: 'tbsp', fat: 13.7, fiber: 37, gramsPerUnit: 5, kcal: 228, name: 'Cacao en polvo puro', protein: 19.6, slug: 'cacao-en-polvo-puro', source: 'usda' },
  { allergens: [{ key: 'milk', presence: 'may_contain' }, { key: 'tree_nuts', presence: 'may_contain' }], carbs: 45.9, category: 'other', fat: 42.6, fiber: 10.9, kcal: 598, name: 'Chocolate negro 70%', protein: 7.8, slug: 'chocolate-negro-70', source: 'usda' },
  { carbs: 0.3, category: 'other', defaultUnit: 'tbsp', fat: 0, gramsPerUnit: 15, kcal: 19, name: 'Vinagre de vino tinto', protein: 0, slug: 'vinagre-de-vino-tinto', source: 'usda' },
  { carbs: 6, category: 'other', defaultUnit: 'unit', fat: 10.9, fiber: 1.6, gramsPerUnit: 4, kcal: 116, name: 'Aceitunas negras', protein: 0.8, slug: 'aceitunas-negras', source: 'usda' },
  { carbs: 3.8, category: 'other', defaultUnit: 'unit', fat: 12.8, fiber: 3.3, gramsPerUnit: 4, kcal: 136, name: 'Aceitunas verdes', protein: 1.4, slug: 'aceitunas-verdes', source: 'bedca' },
  { carbs: 4.9, category: 'other', defaultUnit: 'tbsp', fat: 0.9, fiber: 3.2, gramsPerUnit: 9, kcal: 23, name: 'Alcaparras', protein: 2.4, slug: 'alcaparras', source: 'usda' },
  { carbs: 2.4, category: 'other', defaultUnit: 'unit', fat: 0.3, fiber: 1, gramsPerUnit: 15, kcal: 12, name: 'Pepinillos en vinagre', protein: 0.5, slug: 'pepinillos-en-vinagre', source: 'usda' },
  { carbs: 27.4, category: 'other', defaultUnit: 'tbsp', fat: 0.1, fiber: 0.3, gramsPerUnit: 17, kcal: 101, name: 'Kétchup', protein: 1, slug: 'ketchup', source: 'usda' },
  { allergens: [{ key: 'eggs' }], carbs: 0.6, category: 'other', defaultUnit: 'tbsp', fat: 74.8, gramsPerUnit: 14, kcal: 680, name: 'Mayonesa', protein: 1, slug: 'mayonesa', source: 'usda' },
  { allergens: [{ key: 'mustard' }], carbs: 5.8, category: 'other', defaultUnit: 'tsp', fat: 3.3, fiber: 4, gramsPerUnit: 5, kcal: 60, name: 'Mostaza amarilla', protein: 3.7, slug: 'mostaza-amarilla', source: 'usda' },
  { allergens: [{ key: 'eggs' }], carbs: 2, category: 'other', defaultUnit: 'tbsp', fat: 45, gramsPerUnit: 14, kcal: 418, name: 'Salsa alioli', protein: 1.2, slug: 'salsa-alioli', source: 'bedca' },
  { allergens: [{ key: 'tree_nuts' }, { key: 'milk' }], carbs: 10.1, category: 'other', defaultUnit: 'tbsp', fat: 37.6, fiber: 1.8, gramsPerUnit: 16, kcal: 418, name: 'Pesto genovese', protein: 9.8, slug: 'pesto-genovese', source: 'usda' },
  { allergens: [{ key: 'sesame' }], carbs: 15, category: 'other', defaultUnit: 'tbsp', fat: 17.8, fiber: 5.5, gramsPerUnit: 15, kcal: 237, name: 'Hummus', protein: 7.8, slug: 'hummus', source: 'usda' },
  { carbs: 6, category: 'other', fat: 14, fiber: 5, kcal: 157, name: 'Guacamole', protein: 1.8, slug: 'guacamole', source: 'usda' },
  { carbs: 0.8, category: 'other', defaultUnit: 'tsp', fat: 0.8, fiber: 0.6, gramsPerUnit: 5, kcal: 12, name: 'Salsa picante tipo tabasco', protein: 1.3, slug: 'salsa-picante-tabasco', source: 'usda' },
  { carbs: 40.8, category: 'other', defaultUnit: 'tbsp', fat: 0.6, fiber: 0.9, gramsPerUnit: 17, kcal: 172, name: 'Salsa barbacoa', protein: 0.8, slug: 'salsa-barbacoa', source: 'usda' },
  { carbs: 19.2, category: 'other', defaultUnit: 'tsp', fat: 0.9, fiber: 2.2, gramsPerUnit: 6, kcal: 93, name: 'Salsa sriracha', protein: 1.9, slug: 'salsa-sriracha', source: 'usda' },
  { carbs: 55.8, category: 'other', defaultUnit: 'tsp', fat: 14, fiber: 53.2, gramsPerUnit: 2, kcal: 325, name: 'Curry en polvo', protein: 14.3, slug: 'curry-en-polvo', source: 'usda' },
  { carbs: 54, category: 'other', defaultUnit: 'tsp', fat: 12.9, fiber: 34.9, gramsPerUnit: 2, kcal: 282, name: 'Pimentón dulce', protein: 14.1, slug: 'pimenton-dulce', source: 'usda' },
  { carbs: 44.2, category: 'other', defaultUnit: 'tsp', fat: 22.3, fiber: 10.5, gramsPerUnit: 2, kcal: 375, name: 'Comino molido', protein: 17.8, slug: 'comino-molido', source: 'usda' },
  { carbs: 68.9, category: 'other', defaultUnit: 'tsp', fat: 4.3, fiber: 42.5, gramsPerUnit: 1, kcal: 265, name: 'Orégano seco', protein: 9, slug: 'oregano-seco', source: 'usda' },
  { carbs: 80.6, category: 'other', defaultUnit: 'tsp', fat: 1.2, fiber: 53.1, gramsPerUnit: 2.5, kcal: 247, name: 'Canela molida', protein: 4, slug: 'canela-molida', source: 'usda' },
  { carbs: 49.3, category: 'other', defaultUnit: 'tsp', fat: 36.3, fiber: 20.8, gramsPerUnit: 2, kcal: 525, name: 'Nuez moscada', protein: 5.8, slug: 'nuez-moscada', source: 'usda' },
  { carbs: 71.6, category: 'other', defaultUnit: 'tsp', fat: 4.2, fiber: 14.1, gramsPerUnit: 2, kcal: 335, name: 'Jengibre en polvo', protein: 9, slug: 'jengibre-en-polvo', source: 'usda' },
  { carbs: 67.1, category: 'other', defaultUnit: 'tsp', fat: 3.2, fiber: 22.7, gramsPerUnit: 3, kcal: 312, name: 'Cúrcuma molida', protein: 9.7, slug: 'curcuma-molida', source: 'usda' },
  { carbs: 75, category: 'other', defaultUnit: 'unit', fat: 8.4, fiber: 26.3, gramsPerUnit: 0.2, kcal: 313, name: 'Laurel', protein: 7.6, slug: 'laurel', source: 'usda' },
  { carbs: 0, category: 'other', defaultUnit: 'pinch', fat: 0, gramsPerUnit: 0.5, kcal: 0, name: 'Sal', protein: 0, slug: 'sal', source: 'usda' },
  { carbs: 36, category: 'other', defaultUnit: 'tbsp', fat: 8, fiber: 20, gramsPerUnit: 5, kcal: 416, name: 'Levadura nutricional', protein: 50, slug: 'levadura-nutricional', source: 'usda' },
  { carbs: 0, category: 'other', classes: ['animal'], fat: 0.1, kcal: 335, name: 'Gelatina neutra', protein: 85.6, slug: 'gelatina-neutra', source: 'usda' },
  { carbs: 13, category: 'other', defaultUnit: 'tsp', fat: 0.1, gramsPerUnit: 4.2, kcal: 53, name: 'Extracto de vainilla', protein: 0.1, slug: 'extracto-de-vainilla', source: 'usda' },
  { carbs: 23.6, category: 'other', fat: 64.5, fiber: 16.3, kcal: 660, name: 'Coco rallado', protein: 6.9, slug: 'coco-rallado', source: 'usda' }
];
