import 'ui/styles/colors';
import 'ui/styles/variables';
import 'ui/styles/base';
import 'ui/styles/classnames';

import 'styles/globals.css';
import 'styles/variables.css';

import { font } from 'ui/fonts';
import { Toaster } from 'ui/components/Toaster';

import { Header } from 'components/Header';

import type { Metadata } from 'next';
import type { ReactNode } from 'react';

export const metadata: Metadata = { description: 'Generated by TRC template', title: 'Mini | Docs' };

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html className={font.variable} lang="en">
      <body>
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
